### ISSUE TITLE
MUSIT identificationQualifier

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#1]
MUSIT has moved the identificationQualifier "aff." and "cf." out of the scientificName
and added a new column to the data-views (and data dump-files) IDENTIFICATIONPRECISION (with values "1" and "null").

This type of information is important for the ongoing red-listing work coordinated by NBIC.

Action: add IPT mapping for musit:IDENTIFICATIONPRECISION to dwc: dwc:identificationVerificationStatus
Todo: map must:"identification-qualifier" to dwc:identificationQualifier if made available.

**Comment by dagendresen** [comment]
Good overview of open nomenclature qualifiers from:
Sigovini, M., Keppel, E., and Tagliapietra, D. (2016). Open nomenclature in the biodiversity era. Methods Ecol. Evol. 7, 1217–1225. [doi: 10.1111/2041-210X.12594](https://doi.org/10.1111/2041-210X.12594)

**Comment by rukayaj** [comment]
Is there anything left that we still need to do for this task?

**Comment by dagendresen** [comment]
I believe that the current mapping of identificationQualifier with values provided = "1" is not correct.
However, ADB wants to get it this way for the current ongoing Red List work...

The best would be for MUSIT to provide the actual identificationQualifier strings ;-)

**Comment by dagendresen** [comment]
On another side topic. I found while updating the IPT-mapping across ALL the MUSIT herbaria that identifying each and all herbaria was not so easy. I suggest making a table along the lines of the one I included above for MUSIT collections in the Wiki? With hyperlinks to the IPT admin for the datasets...?
