### ISSUE TITLE
UiA Vascular plant herbarium (KMN)

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#10]
The UiA Vascular plant herbarium (KMN) is now published from UiO Natural History Museum
Maybe we should try to re-connect this dataset to the correct publisher.

UiA Vascular plant herbarium (KMN)
https://doi.org/10.15468/2g6i0v
https://ipt.gbif.no/manage/resource.do?r=kmn_vascular

UiA Natural History Museum and Botanical Garden
https://www.gbif.org/publisher/826d1920-7f5c-4091-a84e-668aa2e35b61
https://registry.gbif.org/organization/826d1920-7f5c-4091-a84e-668aa2e35b61
https://www.wikidata.org/wiki/Q3375341

And while we are at it, there is a duplicate registration in the GBIF registry:
https://registry.gbif.org/organization/search?q=agder

Propose to completely delete this:
https://registry.gbif.org/organization/033300fa-8e41-45a1-a96c-d9d8a63843a3

**Comment by rukayaj** [comment]
Thanks Dag! 

I've reconnected [https://doi.org/10.15468/2g6i0v](https://doi.org/10.15468/2g6i0v) to the correct publisher. Marie asks for us to contact the duplicate registration administrative contact via email (ekspedisjonen.naturmuseet@kristiansand.kommune.no) and ask them if it's ok to delete the duplicate Agder Natural History Museum. I will do that now, hopefully they still check that email...

**Comment by dagendresen** [comment]
(Copy to GitHub)
I believe the website and emails changed to @uia.no when the naturmuseum moved "owner" from the municipality to the university -- only a few years back
naturmuseum-ekspedisjon@uia.no
https://www.uia.no/naturmuseum-og-botanisk-hage

**Comment by rukayaj** [comment]
Ok thanks, I have sent an email letting them know we want to delete the duplicate

**Comment by dagendresen** [comment]
Maybe rather Raul Ramirez would know more than the "ekspedisjon" (front-desk)...
Maybe also ask if he is the appropriate contact point...
PS: Raul completed his PhD at UiO-NHMO Tøyen in 2015.

https://www.uia.no/kk/profil/raulr
raul.ramirez@uia.no

https://www.uia.no/kk/tlf?search=&dep=41&fag=

**Comment by rukayaj** [comment]
I deleted https://registry.gbif.org/organization/033300fa-8e41-45a1-a96c-d9d8a63843a3 and updated the name of https://www.gbif.org/publisher/826d1920-7f5c-4091-a84e-668aa2e35b61.
