### ISSUE TITLE
Image hosting solution for GBIF Norway

### ISSUE THREAD

**Issue by rukayaj** [gbif-norway/helpdesk#100]
Think about thumbnails/resizing, API access to images, persistent identifiers, ...?

Possible solutions: 
- Flickr - I found this https://www.flickr.com/help/forum/en-us/72157685280433883/ which sounds like you can't use flickr for image hosting, and I remember finding this last time too
- Netlify cloud storage solution for images - their hosting looks pretty cool too https://www.netlify.com/products/large-media/
- Digital Ocean Spaces has a built in option to turn asset hosting into a proper cdn https://www.digitalocean.com/products/spaces

Anyone else have any ideas for it?

**Comment by dagendresen** [comment]
If I understand right -- "Don't use your account to host web graphics or as a replacement for a content distribution network." is NOT what we would do anyway. We would want to archive actual photos, not graphics to make a website look nice...???

**Comment by dagendresen** [comment]
I recall that [Meise Botanical Garden](https://zenodo.org/communities/meisebotanicgarden/about/) was [using Zenodo to archive photos](https://zenodo.org/search?page=1&size=20&q=Belgium%20Herbarium%20of%20Meise%20Botanic%20Garden&file_type=jpg&file_type=png&type=image&keywords=Herbarium&subtype=photo)
Example (?) https://zenodo.org/record/2864809#.YkxFejdBzzc

**Comment by rukayaj** [comment]
> If I understand right -- "Don't use your account to host web graphics or as a replacement for a content distribution network." -- "generic graphic elements of web page designs, logos, banners, icons, and other non-photographic elements" -- is NOT what we would do anyway. We would want to archive actual photos, not graphics to make a website look nice...???

I think that the GBIF caching mechanism (for the images to appear on GBIF) might count as us hosting the images, even though it's GBIF cached...? I am not sure, but anyway if we end up hosting the images on the hosted portal or something similar then it will count as 'hosted' I guess?

**Comment by dagendresen** [comment]
[OpenUp!](https://pro.europeana.eu/project/openup) --> [Europeana](https://www.europeana.eu/en/search?view=grid&query=%22OpenUp%21%22)
[Norvegiana](https://norvegianablog.wordpress.com/) --> [Europeana](https://www.europeana.eu/en)

**Comment by rukayaj** [comment]
I think this is actually the same problem as the data backups/hosting. We should store images on a server or in a cloud service bucket which is backed up and secure, and use a cdn e.g. https://imagekit.io/ or https://imageengine.io/ for image resizing and delivery. 

I just trialed imageengine and it seemed to work ok, it creates a custom imageengine domain for your images and you can add resize/crop/etc via the URL so it does it on the fly. I think it's also supposed to do some device detection/image adjustment but perhaps you have to use their react or vue plugins for that. 

We would need to point our persistent identifiers at the new CDN domain, which would then (if it is not already cached there) retrieve the image from our servers.

**Comment by dagendresen** [comment]
> We could possibly point our persistent identifiers at the new CDN domain
Do we have persistent identifiers declared for the images? I hope the materialSampleID persistent identifiers would not be redirected to the image files (or image file metadata) :-D

> do we trust USIT to host all the MUSIT specimen images
I guess this is completely up to the museums - if THEY trust MUSIT to host the images. Not our responsibility?

**Comment by rukayaj** [comment]
> Do we have persistent identifiers declared for the images? I hope the materialSampleID persistent identifiers would not be redirected to the image files (or image file metadata) :-D

We have purl urls for some of our images in this format: https://purl.archive.org/gbifnorway/img/[imageUUID].jpg. We don't have them for all images yet.

> I guess this is completely up to the museums - if THEY trust MUSIT to host the images. Not our responsibility?

Hmm... I suppose so, but I'm not sure about this, it's not really our responsibility to e.g. back up Ukrainian IPTs either, but we think it's worthwhile so we do it. But on the other hand the IPT backups aren't very big, and the MUSIT specimen images are. Hmm...

**Comment by dagendresen** [comment]
We might want to explore the new [Sigma2 Research Data Archive](https://www.sigma2.no/project-new-research-data-archive) -- to explore if it might also have research image hosting facilitation...?

**Comment by rukayaj** [comment]
https://github.com/gbif-norway/documentation/wiki/Image-hosting I think we kind of have something working for this now, described here in the wiki page.
