### ISSUE TITLE
2022-04-28 Node kick off meeting planning

### ISSUE THREAD

**Issue by rukayaj** [gbif-norway/helpdesk#102]
I made a folder on Google drive here https://drive.google.com/drive/folders/1eLhs9YzjqXhsMnGad0uEnyC7sSkQOC0Z, and I added some draft slides for WP4. But maybe there's somewhere else already that I missed where the draft program document is?

Is there a confirmed participant list somewhere that I didn't see in the doc, or should we send out a calendar reminder to everyone?

Useful links:
Work plan: https://docs.google.com/document/d/1v7Pp9SrXw2LpDobVc-v7qnVErDrMNbFRf9pryp6UdPI/edit#
Draft program: https://docs.google.com/document/d/1aI5jyEIrW1yYLvYgEAM9bRpYB05-7v-N9HjElIv1k9E/edit#
Contract: https://osf.io/t469m/

**Comment by dagendresen** [comment]
I have [included a table](https://docs.google.com/document/d/1aI5jyEIrW1yYLvYgEAM9bRpYB05-7v-N9HjElIv1k9E/edit#heading=h.1auvcgnph701) of who received the calendar invitation to the meeting and how they have responded. We can update the calendar invitation as a reminder after Easter, early next week.
Thanks for making the [shared GDrive folder](https://drive.google.com/drive/folders/1eLhs9YzjqXhsMnGad0uEnyC7sSkQOC0Z?usp=sharing)!
