### ISSUE TITLE
Datasets from the Norwegian Polar Institute

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#104]
Doreen Kohlbach <Doreen.Kohlbach@npolar.no> of the Norwegian Polar Institute is asking for support to publish her datasets in GBIF.

ORCID = https://orcid.org/0000-0002-9245-2500
ROR ID = https://ror.org/03avf6522

Datasets (remember to cite the source DOI - if moving them to the IPT!)
https://data.npolar.no/dataset/37159527-50ec-45fb-85ba-7c55b0d3169c  --> [[on IPT.no]](https://ipt.gbif.no/manage/resource?r=hbis_sterols_nansen_legacy_q4)
https://data.npolar.no/dataset/941be8cc-207f-4f42-a078-98e58649d4b0 --> [[on IPT.no]](https://ipt.gbif.no/manage/resource?r=hbis_sterols_nansen_legacy_q3)
https://data.npolar.no/dataset/d436b683-5d79-4044-8f82-f252ed9f54cf
https://data.npolar.no/dataset/40c7af2a-b4a2-4d19-b00d-fdd6e76f140e
https://data.npolar.no/dataset/53bfa233-db4e-4db3-bed1-b56ab444f78b

Doreen describes these datasets on the NPDC data portal to already be in DwC-A format!
Verified that the datasets are already on the node IPT!

Todo: check if we can maybe publish directly from the NPDC DOI endpoint (maybe instead of through the IPT?). They have very specifically expressed that they DO want to use their own dataset DOI - and that they are not particularly happy for a new GBIF dataset DOI to take priority above their own DOI...

**Comment by rukayaj** [comment]
Ah, I didn't see you made an issue for this. Thanks. I have published all of these now:

https://www.gbif.org/dataset/baa7d7c9-8b9b-4378-91fb-b82522dfbf32
https://www.gbif.org/dataset/7fcf1da7-2c7a-4e69-a60d-efa5f0b4ec77
https://www.gbif.org/dataset/021366ac-62e5-4acc-a439-4c37b3288d87
https://www.gbif.org/dataset/95e464b4-e286-414b-9c59-6fdc9a4afc14
https://www.gbif.org/dataset/34ed3819-a996-47ad-bc36-ee0a8471a57d

For the resourceRelationship link, this is what Luke said in an earlier email:
> RelatedResources extension: links the measurements to the occurrences. This is only necessary where you have community measurements, where one measurement needs to be linked to multiple occurrences.

So it's related to community measurements, and I think it's correct to be using the resourceRelationship extension. I've just added some explanation in there, that this is a measurement for a community of organisms. It's not in every dataset either just a few.
