### ISSUE TITLE
TDWG 2022 - 17–21 October. Sofia, Bulgaria.

### ISSUE THREAD

**Issue by rukayaj** [gbif-norway/helpdesk#105]
Last year I missed the early registration deadline, so I'm making this issue to remind us. Do we want to have a poster or talk perhaps? We could try and get some beta version of the annotator interface in place so we could present that? 

[Register](https://events.pensoft.net/events/tdwg-2022-hybrid-conference) for TDWG 2022 - Early registration for in-person attendance ends 22 July 2022 (extended 1 week!)

[Call for Abstract Submission](https://www.tdwg.org/conferences/2022/call-for-abstracts/) - Deadline 1 July 2022

https://www.tdwg.org/conferences/2022/

**Comment by dagendresen** [comment]
[Early bird registration](https://events.pensoft.net/events/tdwg-2022-hybrid-conference) to TDWG 2022 is 400€ (350€ with member discount). Regular registration is only 50€ more, while virtual online participation is 120€ (70€ w discount).

I have now contacted TDWG and requested an invoice to register GBIF Norway as a member of TDWG. TDWG members can get a discount (of 50€) for up to 5 people. Node members can contact helpdesk@gbif.no to get the discount code.

I already have an individual TDWG membership (with the same registration discount). And I have now registered for the conference for in-person attendance. (So we still will have the node discount code for a full 5 people).

Hope all node staff also will consider registering and attending the TDWG 2022 conference in Sofia Bulgaria from 17 to 21 October! (You can send the travel invoice to the University of Oslo after the conference).

**Comment by dagendresen** [comment]
I suggest we try to write an abstract for our PURL:UUID, urn:uuid:UUID persistent identifier mechanism. Where we "listen"/monitor to the Dwc-A data stream from all the Norwegian data publishers and create the PID resolver end-points for the correctly formated PURL:UUIDs and urn:uuid:UUID identifier strings that we discover. With an update from the similar TDWG 2014 abstract available at http://doi.org/10.13140/2.1.4516.9606 ([See also the 2016 blog post](https://dagendresen.wordpress.com/2016/07/13/persistent-identifiers-at-gbif-no/))

Maybe interesting with an abstract on the progress on marine data mobilization?

Maybe an abstract with the results from the BioDATA (2018-2022) project!

Other/additional abstract suggestions are of course certainly most welcome!

This/these could be either a poster(s) or a plenary talk(s)...

**Comment by rukayaj** [comment]
So we could have a poster, based on the other abstract - saying that this is what we learned so far:

- Workflow + how the api is working
- problems + solutions
- handles vs purls, and problems with purls
- statistics of stability of our identifiers

**Comment by rukayaj** [comment]
Submitted for technical review

**Comment by rukayaj** [comment]
- stats on stability of uuids vs dwc triplets (what records get "deleted"?)

**Comment by dagendresen** [comment]
### First, and most important - confirm the `stability` of the PIDs
--> track and enumerate what records `lose` their PIDs (urn:UUIDs), in other, words data records for the same collection specimen published/updated with another PID in the update cycle
--> we need somehow to track if the data record describes the same physical specimen (to validate if the PID really is stable, if the PID is working the PID alone is ensuring stable identity!!!)
--> if the same PID suddenly represents a different physical specimen is an **_extremely severe failure_**!!!
--> if the same physical specimen is represented by a different and new PID should obviously be avoided - and stopped from happening again (and all such PIDs must linked together with a sameAs, exactMatch, or similar statement)

### Second, use the stable PIDs to explore the stability of non-PID identifiers
--> such as the stability of catalogNumber, recordNumber, collectionCode, institutionCode, etc...
--> explore the stability of the GBIF occurrenceKey (can also utilize the GBIF occurrenceKey above in the routines to validate the stable identity for the PIDs from our data publishers!)
--> could maybe even for fun explore if the occurrenceKeys or the data publisher-provided PIDs are more stable... :-)

**Comment by rukayaj** [comment]
Some more interesting questions: 

QR code validation - does the qr code match up to the materialSampleID (the uuid currently stored in the other identifiers field) ? Which specimens do NOT have qr codes?

**Comment by dagendresen** [comment]
We could test for collection specimens images including the QR code or data matrix for the urn:UUID published as materialSampleID and validate that this is the SAME.

**Comment by dagendresen** [comment]
Another very interesting [TDWG 2022 abstract on Specimen identifiers](https://doi.org/10.3897/biss.6.94625)!

Here [Mulcahy](https://doi.org/10.3897/biss.6.94625) focuses on linking specimen-derived material and data together using the Digital Extended Specimen concept. Mentioning the `DYSFUNCTIONAL` DwC triplet for linking data and voucher specimen --> But not actually mentioning the need for linking the Digital Extended Specimen persistently to its physical counterpart, the real-life specimen. Which (I do hope) is the main topic of [our abstract](https://doi.org/10.3897/biss.6.91585)... (?). The persistent and stable link to the actual real-life physical voucher specimen could become the VERY weak link in these approaches (if not addressed and solved). https://doi.org/10.3897/biss.6.91585

See also the [respective TDWG session](https://biss.pensoft.net/browse_user_collection_documents?collection_id=394) for linked similar abstracts.

See also the GBIF Call for proposals to help mature and test how specimens are handled in GBIF’s emerging unified data model, deadline 2nd October 2022, https://www.gbif.org/news/2ZQI4f1AtimpT5gd3qk9pd/call-for-proposals-to-help-mature-and-test-how-specimens-are-handled-in-gbifs-emerging-unified-data-model

**Comment by rukayaj** [comment]
I forgot about the poster :D they said I can try and get it done by Wednesday

**Comment by dagendresen** [comment]
Happy trip! Enjoy!!! 🤩 PS: Michal mentioned the poster is not really about identifiers anyway 😁 😝 😜 🤖
