### ISSUE TITLE
Geocase/geological collections publishing

### ISSUE THREAD

**Issue by rukayaj** [gbif-norway/helpdesk#109]
Eirik wants to get the geological collections published on https://geocase.eu/. Geocase were asking for either DwC format, or ABCD (+ EFG) https://geocase.eu/efg which means cooooomplicated xml, which E and I agree does not really make sense for the simple data that we have. 

So seeing as it's going to be DwC, Eirik was asking about the possibility of using the IPT to make the eml, and map and generate the data. And we have such a nice easy way to spin up IPTs now and so much space to fill on Sigma2 I suggest we just spin up an IPT for geological collections, and that can be used for geocase's harvesting :)

**Comment by rukayaj** [comment]
I set up https://uio-geology.ipt.gbif.no/

**Comment by rukayaj** [comment]
Just so we remember - yesterday we removed this uio-geology ipt again and decided to just put it on the main IPT. Also we made Irina an acc there, and she will publish the data (but I think not register with GBIF). 

Their data is in an MS Access db. We showed them how to export to excel, and then import that into the ipt and fill in the metadata and do the mapping - they might need to do something about date formatting here, if so I think they said they were going to get help from Vidar. 

For the mapping - they are going to do what makes sense to them and then work it out with geocase. 

So I think for the moment we have done what we can, we can reopen if we need to help them more.

**Comment by dagendresen** [comment]
When I visit https://uio-geology.ipt.gbif.no/ I get "NET::ERR_CERT_AUTHORITY_INVALID" error message... :-)

**Comment by dagendresen** [comment]
CETAF invites for a GEOCASe Workshop

[Register Here](https://forms.gle/ZVHTfDLWwzoaXvvu9)

 

Location: Naturalis,[ Darwinweg 2, 2333 CR Leiden, Netherlands](https://goo.gl/maps/4Q7NTxcaH1y7b4Am7)

Date/Duration: Two Half-day event, DAY 1: 26th June 2023 (12:30 - 17:30 CEST); DAY 2:  (9:00 - 13:00)

Hosts: Naturalis & CETAF Earth Science Group

[Preliminary Agenda](https://docs.google.com/document/d/1FhKG-4IKjHn1oERRqb35Lq-s9cNTaLFtesnFE5ntwkU/edit):

[New GeoCASe Manual (Draft](https://docs.google.com/document/d/1Xs9BdS-2H1RAZ-4iy_FX9o_NloimSpcl-e3lszRTu3g/edit)):

Benefits of attending the workshop

The main objective of the workshop is to spread knowledge about the use of the BioCASe software and to mobilize geological specimen data to GeoCASe. By the end of the workshop, the participants will:

know how to set-up a new dataset
Map the data to the ABCD-EFG standard, and
mobilise it to GeoCASe
This is a great opportunity to gain practical experience. Participants will bring at least one of their own Earth Science data sets, and then will be shown step-by-step how to export the data to GeoCASe.

The work shop will have limited capacity, 1st come 1st serve basis. CETAF and DiSSCo members will be given priority.
Participant will have to pay for their own accommodation and travel. Lunch and Coffee Breaks will be provided by Naturalis.
Please read the Preliminary Agenda (Below) for further information and prerequisites for the workshop.

**Comment by rukayaj** [comment]
> When I visit https://uio-geology.ipt.gbif.no/ I get "NET::ERR_CERT_AUTHORITY_INVALID" error message... :-)

Yes, we took it down:

> Just so we remember - yesterday we removed this uio-geology ipt again and decided to just put it on the main IPT. Also we made Irina an acc there, and she will publish the data (but I think not register with GBIF).

The url for Irina's dataset is: https://ipt.gbif.no/resource?r=uio-geology-international-rock

**Comment by rukayaj** [comment]
I forgot about the geocase workshop, I don't think anyone attended it. But the dataset is published so I think it's ok to close this issue again, or is there something we should do here?
