### ISSUE TITLE
DNV GL dataset -- OpenPSD report feedback on geo-coordinate issues

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#11]
From the GBIF CESP feedback to the OpenPSD final report:

>The DNV dataset is associated with a number of flags relating to coordinates. For example, around 20,000 records have invalid coordinates such as this record (https://www.gbif.org/occurrence/2623177439) where the coordinates fields contain the value “inf”.
>**Recommended action**: Would it be possible to check coordinates for this dataset?

**Comment by rukayaj** [comment]
When they say "check", do you understand what I mean?  I am not sure if they mean exclude/don't publish records without coordinates, or that we should ask DNV to georeference these records?

**Comment by dagendresen** [comment]
I guess they mean doing something with the geocoordinate strings reported as "inf". (Simply making these "inf" values NULL).
<img width="400" alt="Screenshot 2021-02-26 at 15 33 17" src="https://user-images.githubusercontent.com/4330242/109313367-6d337780-7848-11eb-8ab2-d4ddb55cade6.png">

Maybe these are some output from a function converting from the UTM zone 33N (EPSG:32633) geocoordinates indicated as the verbatim format.

**Comment by dagendresen** [comment]
I added occurrenceStatus = present
Doing something with the country is more demanding because there are multiple countries that the points in the sea are interpreted as... maybe be bold and just "claim" all the respective waters as Norway :-D

**Comment by dagendresen** [comment]
I had a meeting with OBIS after the previous GBIF Community webinar -- and will attend a meeting with OBIS and Colombia organized by the secretariat soon. The topic of "oceans" as more relevant than "countries" is sure to be relevant.

Recall that also Kjell Bjørklund was much more interested in "oceans" than "countries" for the Radiolaria dataset.

**Comment by rukayaj** [comment]
Republished with NULL instead of inf
