### ISSUE TITLE
Excel files with multiple sheets into IPT

### ISSUE THREAD

**Issue by lhmarsden** [gbif-norway/helpdesk#113]
Hi all,

I hope you are enjoying the summer.

I have an Excel sheet with three sheets; one for an event core, one for an occurrence extension, one for a measurementorfacts extension. I am trying to create a DwCA out of it using a test node of the IPT 
https://ipt-test.gbif.no/

I 'connect' the source data the first time and choose the 'Event Core' sheet, then proceed to map the columns to DwC terms. I then try to connect the same file again, with the aim of selecting a different sheet. However, this isn't possible. Instead, when I select the same file for the second time, it asks me if I want to overwrite the first file. Hence, I can't upload two sheets from the same file.

Including multiple sheets for different cores and extensions in the same file seems like a sensible thing to do, and GBIF templates are even structured this way. So am I missing something on how to upload these data? 

Of course I could separate the sheets into different files... but surely I shouldn't have to.

Cheers

Lue

**Comment by rukayaj** [comment]
Hi! I believe it's just not possible to select different sheets as you describe. We usually convert excel files to csv and have one csv per sheet. It is kind of annoying to not be able to select multiple sheets, but excel does some funny things with dates sometimes so more often than not csv just saves time. 

The other thing you could do is just copy and rename your xlsx file.  So keep all the sheets in one file, copy that file 3 times with 3 different names, and upload each of them. Or you could not bother with copying, just upload the file, then rename it on your computer and upload it again, then rename it again on your computer and upload it a third time. It doesn't matter that it's the exact same file, the important thing is the name will be different.

**Comment by lhmarsden** [comment]
Thanks for the quick reply @rukayaj. I am creating a tool to extract metadata from the Nansen Legacy metadata catalogue (https://sios-svalbard.org/aen/tools) and dump them into the 3 sheets of this XLSX file. The researcher still has to do some checking, correcting and adding things, so storing them in a single XLSX file is convenient for them I think.

I will advise them to export each sheet into CSV files before they upload them.

Cheers!

**Comment by lhmarsden** [comment]
Another related questions; I don't see an option to add an occurrence extension. on the DwC Mappings dropdown list. Is this possible?

**Comment by rukayaj** [comment]
Hmm it should be there. Do you want to zoom quickly?

**Comment by lhmarsden** [comment]
Sure :)

**Comment by rukayaj** [comment]
Join Zoom Meeting
https://uio.zoom.us/j/4769565894?pwd=TWg5L05vZnJNbWl1R3IyZ3R2Zk13Zz09

**Comment by rukayaj** [comment]
Test IPT didn't have the occurrence extension installed, we just fixed it
