### ISSUE TITLE
GBIF Node branding logo - for the footer of the node home page

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#115]
GBIF has created a new [GBIF Node branding logo](https://www.gbif.org/logos) for us to [add in the footer](https://assets.ctfassets.net/uo17ejk9rkwj/47acC3NY0cphRIaqyoWJoV/43f2b12afc527a975efdf9384aa87f8f/node-logo-guidelines.pdf) of the [node home page](https://www.gbif.no/).

I have started by adding the new branding logo simply in the right-side sidebar.

Maybe we manage to get the logo also into the page footer?

![GBIF Node logo](https://user-images.githubusercontent.com/4330242/188174978-16e22d71-4d7a-4883-81fc-b5b05b4aeb03.png)

**Comment by dagendresen** [comment]
Not super-urgent, but to look at when time allows :-)

**Comment by rukayaj** [comment]
We had a meeting about this today and the UiO web team are going to handle it for us.

**Comment by rukayaj** [comment]
@MichalTorma fixed this a while ago now I think?
