### ISSUE TITLE
Bulk collections dataset from NHM

### ISSUE THREAD

**Issue by rukayaj** [gbif-norway/helpdesk#117]
The collection consists mostly of bulk-samples - so this makes some of the datafields more challenging - e.g. when there are more than one taxa in one sample.
The collection is registered in GRSciColl; "Collection for bulk- and project material".

The database for the collection is so far only an excel-sheet, e.g: 

| catalogNumber | institutionCode | collectionCode | kingdom | Phylum | class | order | infraorder | family | genus | specificEpithet | identificationRemarks | verbatimIdentification | PreservedSpecimen | recordedBy | identifiedBy | continent | country | stateProvince | county | locality | verbatimLocality | decimalLongitude | decimalLatitude | eventDate | verbatimEventDate | materialSampleID |
|---------------|-----------------|----------------|---------|--------|-------|-------|------------|--------|-------|-----------------|-----------------------|------------------------|-------------------|------------|--------------|-----------|---------|---------------|--------|----------|------------------|------------------|-----------------|-----------|-------------------|------------------|
| 658 | NHMO | BULK | Animalia | Arthropoda  | Thecostraca  | Balanomorpha  |  | Balanidae     | Balanus |        |  |                                                                                                                                                                           | Bulk of organisms preserved in ethanol      | Immanuel Vigeland    |                   |  | Singapore? |          |  |                      | 67a. Asbest plate. After 9.                                                 |  |  | 02/07/1965 |                      | http://purl.org/nhmuio/id/A57D28C3-6082-12A2-9F86-111061A7032E  |
| 659 | NHMO | BULK | Animalia | Annelida    | Polychaeta   |               |  |               |         |        |  |                                                                                                                                                                           | Bulk of organisms preserved in ethanol      | Immanuel Vigeland    |                   |  | Singapore? |          |  |                      | Bulk-sample collected from SFI (Skipsteknisk forskningsinstitutt) test raft |  |  | 1965       |                      | http://purl.org/nhmuio/id/A5A01A14-6082-12A2-99F2-1211FB479C61  |
| 660 | NHMO | BULK | Animalia | Evertebrata |              |               |  |               |         |        |  |                                                                                                                                                                           | Bulk of organisms preserved in ethanol      | E. Hansen, D. Distad |                   |  |            |          |  |                      | Norwegian expedition. 17.2.193, 1928. Slepetrekk. (191).  No '59.           |  |  | 1928       |                      | http://purl.org/nhmuio/id/A5C02535-6082-12A2-93A0-1BD8B33D7549  |
| 661 | NHMO | BULK | Animalia | Evertebrata |              |               |  |               |         |        |  |                                                                                                                                                                           | Bulk of organisms preserved in ethanol      | Immanuel Vigeland    |                   |  |            |          |  | Norwegia expeditioin | Port Lockeroy                                                               |  |  |            |                      | http://purl.org/nhmuio/id/A5E894C6-6082-12A2-9936-1622532FF4B8  |
| 662 | NHMO | BULK | Animalia | Evertebrata |              |               |  |               |         |        |  |                                                                                                                                                                           | Bulk of organisms preserved in ethanol      | Immanuel Vigeland    |                   |  |            |          |  | 71 2 S, 12  W        | 71gr 2 S, 12 gr  W (?)                                                      |  |  |            | des. 191.            | http://purl.org/nhmuio/id/A6FFAA16-6082-12A2-94D2-15B739D14C6C  |
| 663 | NHMO | BULK | Animalia | Evertebrata |              |               |  |               |         |        |  |                                                                                                                                                                           | Bulk of organisms preserved in ethanol      | Immanuel Vigeland    |                   |  |            |          |  | 71 2 S, 12 16 W      | S.B. 71gr 2 CxL 12 gr 16min (hovedetikett). Kapt Ring.                      |  |  | 16/12/1928 | 17.2.193, 16.12.1928 | http://purl.org/nhmuio/id/A73F9947-6082-12A2-9394-1A6D53AC25AA  |
| 664 | NHMO | BULK | Animalia | Evertebrata |              |               |  |               |         |        |  |                                                                                                                                                                           | Bulk of organisms preserved in ethanol      | Immanuel Vigeland    |                   |  |            |          |  | Port Lockeroy        |                                                                             |  |  |            |                      | http://purl.org/nhmuio/id/A7687E08-6082-12A2-9B91-184EB26BBB38  |
| 665 | NHMO | BULK | Animalia | Evertebrata |              |               |  |               |         |        |  | Serupoedlaria. Bicillarina.                                                                                                                                               | Bulk of organisms preserved in ethanol      | Immanuel Vigeland    |                   |  |            |          |  |                      | Spitzbergen expedition?                                                     |  |  |            |                      | http://purl.org/nhmuio/id/A777E759-6082-12A2-9E42-14E767A2CE66  |
| 666 | NHMO | BULK | Animalia | Bryozoa     | Gymnomaelata | Cheilostomata |  | Mucronellidae | Porella | sacata |  |                                                                                                                                                                           | Bulk of organisms preserved in ethanol      | Immanuel Vigeland    |                   |  |            |          |  |                      |                                                                             |  |  |            |                      | http://purl.org/nhmuio/id/A7A3642B-6082-12A2-983A-1FC0D13A6272  |
| 667 | NHMO | BULK | Animalia | Bryozoa     |              |               |  |               |         |        |  | 1. Electra pilosa var. Detata. 2. Electra pilosa var. Verticillata. 3. Saropocallaria reptans. 4. Cellaporella haline. 5. Alcyoridium hirsutum. 6. Flustrallidra hispida. | Organism or bulk of organisms preserved dry | Immanuel Vigeland    | Immanuel Vigeland |  | Sweden     | Bohuslän |  |                      |                                                                             |  |  | 1941       |                      | http://purl.org/nhmuio/id/A9669802-6082-12A2-93A4-112FD2AEF462  |
| 668 | NHMO | BULK | Animalia | Bryozoa     |              |               |  |               |         |        |  | Valkeria uva                                                                                                                                                              | Organism or bulk of organisms preserved dry | Immanuel Vigeland    | F. Borg           |  |            |          |  | Halland, Vaderø      |                                                                             |  |  |            | 199?                 | http://purl.org/nhmuio/id/AA2E7BEA-6082-12A2-9D2F-1B21D4B513DD  |

**Comment by gunnhilm** [comment]
I was hoping that we could keep each entry as one record, even though there are several taxa, and mention them by the highest common level, e.g. "Bryozoa" for sample 667. There are several taxa in many of the samples, maybe in most of them, but its just for some that I have made a note about which they are. Generally we haven't recorded (or do not know) what the taxa are. Is this feasible, within GBIFs framework, to register bulks like this, with only the highest common taxonomic level mentioned? We can of course delete this kind of information from the verbatimIdentification-field. It is more "additional arbitrary information", not recorded in a systematic fashion, and I guess there is no dwc-field for that.

**Comment by dagendresen** [comment]
I agree entirely that dwc:MaterialSample entries (including notably the environment samples for eDNA) would often be bulk samples composed of multiple taxa, or even no taxa at all! I hope the new GBIF data model under development and enabling the move away from the Occurrence model straight-jacket will enable better representation of such bulk samples -- soonish!

**Comment by dagendresen** [comment]
And if a bulk sample includes a mixture of organisms from multiple kingdoms, I think that the super-class `biota` is completely legitimate to use
https://www.catalogueoflife.org/data/taxon/5T6MX
https://www.gbif.org/species/170809336

**Comment by rukayaj** [comment]
Thanks dag! Ok that sounds like a good move then, we keep 1 row per bulk sample, as you've got it, and use biota or whatever higher taxonomic level.

**Comment by rukayaj** [comment]
Published https://www.gbif.org/dataset/a6e3fb90-33f7-446b-82d8-5eef4480f5f1
