### ISSUE TITLE
GGBN and Material Sample (core) data model

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#12]
Question from Yi Ming Gan <ymgan@naturalsciences.be> on 2021-02-25:

Maybe you @rukayaj and/or Lars Erik want to share some details on how we publish the DNA bank to GGBN (and GBIF)?

>I work with Anton Van de Putte and he told me that you are familiar with Material sample extension for Darwin Core. So I received a dataset which I wonder could fit with the extension and I would like to have your opinion in fitting this dataset into Darwin Core if you don’t mind.

>Amphipod trap caught amphipods. Pictures are taken for these amphipods. Each amphipod is treated like this:
>- A pleopod is taken from whole individual and preserved in allprotect reagent
>- A pleopod is taken from whole individual and preserved in RNA/DNA shield reagent
>- The whole individual is freeze at -20’C

>How would you model this type of data?

>Would occurrence core + simple multimedia extension for the image + GGBN’s material sample extension for pleopod + GGBN’s preservation extension for the preservation method make sense? 
It will still mean that each pleopod is still an occurrence record with basisOfRecord == MaterialSample and preservation method should falls under “preparations” field.

>I also noticed that Material Sample extension is meant for Material Sample Core which I have never heard of?? So I am not sure if this is something that makes sense or whether the extension can be used this way?
Your input will be very much appreciated.

**Comment by dagendresen** [comment]
The MaterialSample in Darwin Core is a ["class/category"](http://rs.tdwg.org/dwc/terms/MaterialSample) [1] -- but there is no ["core"](https://rs.gbif.org/core/) developed for the GBIF infrastructure (yet) [2]. However, there is a (GBIF) [MaterialSample core in the "sandbox"](https://rs.gbif.org/sandbox/core/dwc_material_sample.xml) [3] (since 2015!) -- but development looks very unfortunate to have stalled. Currently, there are more recent and very interesting development around the [MIXS Sample ("extension")](https://rs.gbif.org/sandbox/extension/mixs_sample_2020_06_23.xml) [4] -- which might (I hope) develop into a "MaterialSample"/"MIXS-sample" core model in GBIF...???

[1] http://rs.tdwg.org/dwc/terms/MaterialSample
[2] https://rs.gbif.org/core/
[3] https://rs.gbif.org/sandbox/core/dwc_material_sample.xml
[4] https://rs.gbif.org/sandbox/extension/mixs_sample_2020_06_23.xml

**Comment by rukayaj** [comment]
I think the occurrence core + simple multimedia extension, combined with the GGBN extensions that Yi Ming suggests for  her use case does make sense.

Lars Erik uses the following:
GGBN Material Sample Extension [https://rs.gbif.org/extension/ggbn/materialsample.xml](url)
GGBN Preparation Extension [https://rs.gbif.org/extension/ggbn/preparation.xml](url)
GGBN Preservation Extension [https://rs.gbif.org/extension/ggbn/preservation.xml](url)
GGBN Amplification Extension [https://rs.gbif.org/extension/ggbn/amplification.xml](url)

I am not exactly sure what it is, but he has a system where he exports a Darwin Core Archive file directly from Corema and we host it at https://data.gbif.no/ggbn/ggbn/, and there is some kind of import process I think for GGBN from there. And he publishes the same DwCA through the IPT for GBIF. 

She might want to look at e.g. https://ipt.gbif.no/resource?r=o_dna_arthropods for an example, too.

**Comment by 79-6d** [comment]
Hey, thank you so much for making an issue Dag and thank you so much for the very informative comment, Rukayaj! The example is extremely helpful!! 

There is no sequences associated with the dataset because the sequencing is halted, at least for now. 

If I model the data according to the example, I might lose overall information on the amphipod (samplingProtocol = trap), so what do you think about the following approach? 

occurrenceID | scientificName | eventID | parentEventID | basisOfRecord | preparations | samplingProtocol | occurrenceRemarks
---|---|---|---|---|---|---|---
occ1 | Charcotia obesa | 1 | | HumanObservation | | amphipod trap |
occ2 | Charcotia obesa | 2 | 1 | PreservedSpecimen | Frozen, -20'C | | whole individual from eventID=1
occ3 | Charcotia obesa | 3 | 1 | MaterialSample | allprotect reagent | | pleopod subsampled from individual in eventID=1
occ4 | Charcotia obesa | 4 | 1 | MaterialSample | RNA/DNA reagent | | pleopod subsampled from individual in eventID=1

Thank you so much!!

**Comment by dagendresen** [comment]
Your example looks good to me. I would have added an organismID for the same individual animal across all respective data records.

Your example demonstrates well the limitations of the "star-schema" model of the Darwin Core Archive. Your dataset would fit very well to the Event core -- but then the star schema restricts your possibilities to link anything to the material samples, such as multimedia and sequence data.

I assume your eventID 1 includes more animals than only "occ1"?

What we did for some marine datasets was to publish the events in a different separate dataset. And link to the eventIDs from the Occurrence core datasets with the specimens. e.g. https://doi.org/10.15468/hwvr0m

**Comment by 79-6d** [comment]
> Your example looks good to me. I would have added an organismID for the same individual animal across all respective data records.

Oh yes, indeed, that sounds like a great idea! Thank you!

> Your example demonstrates well the limitations of the "star-schema" model of the Darwin Core Archive. Your dataset would fit very well to the Event core -- but then the star schema restricts your possibilities to link anything to the material samples, such as multimedia and sequence data.

Precisely.

> I assume your eventID 1 includes more animals than only "occ1"?

Yes indeed. I guess if `organismID` is to be included, each organism will be a separate occurrence record with individualCount = 1?

> What we did for some marine datasets was to publish the events in a different separate dataset. And link to the eventIDs from the Occurrence core datasets with the specimens. e.g. https://doi.org/10.15468/hwvr0m

I see!! I just had a look at the datasets, but I might have missed it, how are the occurrences linked to the sampling events in this case?

**Comment by rukayaj** [comment]
Hi! I'm sorry, your last few questions slipped under the radar. No, I don't think that you need organisms stored separately as occurrence records if you use `organismID`. 

The corresponding occurrence dataset relating to this event dataset is on our IPT here https://ipt.gbif.no/resource?r=polychaeta and I can see that it actually doesn't seem to be linking back to the eventIDs, unless I'm missing something. But the IPT still seems to let you publish an eventID mapping even when you are using the Occurrence core. 

So you could try the above, or you could try using resourceRelationship in the occurrence dataset, see https://dwc.tdwg.org/terms/#resourcerelationship. You would need to add the occurrenceID, the related eventID (does not matter that it's not in the same dataset), and relationshipOfResource would be something like "collected during" or similar.

I hope that helps!

**Comment by dagendresen** [comment]
The intersection between an Organism and an Event is what the Occurrence is. And when using the Occurrence-core model each Occurrence would a new data record. Adding organismID enables tracking the same Organism between the data records.

For the Polychaeta Event-core dataset - I believe the intention was to reuse the same eventID UUID in the museum collection datasets, as the specimens become digitized. Not sure how well this is followed up though :-)

**Comment by rukayaj** [comment]
@79-6d Just checking up to see how things are going. If you need any more advice please re-open this issue :)

**Comment by 79-6d** [comment]
My apologies for late reply! Thank you so much Rukayaj and Dag, all the advice and examples here have been incredibly helpful!! 

I don't think I have anymore questions at least for the moment! I will model the data according to your advice. Thank you so much for everything!! It's very much appreciated! I will re-open the issue if I need more advice.
