### ISSUE TITLE
Datasets from Øvre Heimdalsvatn

### ISSUE THREAD

**Issue by vidarbakken** [gbif-norway/helpdesk#127]
Together with John Brittain (retired researcher from HNM)  I have started a project to publish three datasets from Øvre Heimdalsvatn in GBIF. This first was published today, and we continue with the two others. The datasets cover small animals (e.g. amphipods) and fishes in freshwater.

First dataset published: https://www.gbif.org/dataset/ddd3f80e-6e16-4db5-b26e-c72e8755bf5f

**Comment by vidarbakken** [comment]
Also noted that an Extended MeasurementsorFacts extension is correctly displayed in GBIF.org! I have a sample-event dataset where the measurements of the animals are connected to the occurrence table (eMoF).

**Comment by rukayaj** [comment]
Yes, it's a pity they still don't index it though, so you can't search for measurementOrFacts.

**Comment by vidarbakken** [comment]
The second dataset is published:
https://www.gbif.org/dataset/3ce58192-816c-48d2-8fa0-1f62648526ce

**Comment by rukayaj** [comment]
Is this the dataset you were talking about in the office on Friday, @vidarbakken? Which will need two occurrence sheets mapped to 1 event sheet?

**Comment by vidarbakken** [comment]
Yes, there are three excel spreadshets in total. The last one contains four different tabs with data related to the same stations (events). I must check this in more detail before I can say that I need two occurrence tables. It is also an option to make them as different datasets.

**Comment by vidarbakken** [comment]
Now we have published six datasets from Øvre Heimdalen and this project is completed. John Brittain was an excellent assistent to prepare all the metadata and explain the contents of the datasets.
