### ISSUE TITLE
NMBU MINA Data and Stats Forum 26th April 2023

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#128]
### [Data and Stats Forum](https://github.com/NMBU-Data-Science/MINA_DSF) at [NMBU MINA](https://www.nmbu.no/fakultet/mina)

Contact point: [Reed April Mckay](https://www.nmbu.no/ans/reed.april.mckay)

> Presentation of GBIF and the importance of data repositories / open science in biodiversity disciplines for the
Data and Stats Forum at MINA NMBU on March 29th at or April 26th at 12:00 via Zoom or Teams. Usually, a brief introduction, then a guest speaker talks for anywhere between 15 – 30 minutes. Usually, this works best if there are also some examples/exercises for people to work through, however, anything you are willing to share would be most welcome!

* [NMBU in the GBIF portal](https://www.gbif.org/publisher/8256e897-3a17-4a2d-8bf8-54cf22b624bd) ([42 datasets](https://www.gbif.org/dataset/search?publishing_org=8256e897-3a17-4a2d-8bf8-54cf22b624bd))
* Dataset contact at NMBU (2022-): Zeba Zeba
* Dataset contact at NMBU (2019): Mahdieh Tourani
* Dataset contact at NMBU (2015-2019): Mari Steinert

> Happy to confirm 26th April for a presentation and a bring-your-own-data workshop. I will suggest for one of my colleagues at the GBIF Node to join for supporting the workshop.

**Comment by dagendresen** [comment]
Reed:
> Once you have some ideas for how you would like to run the workshop, it would be wonderful if you could write a brief description that I could share and advertise through the forum

**Comment by dagendresen** [comment]
### Access to biodiversity data via the Global Biodiversity Information Facility - GBIF

GBIF—the Global Biodiversity Information Facility—is an international network and data infrastructure funded by the world's governments and aimed at providing anyone, anywhere, open access to data about all types of life on Earth. Data available through the GBIF portal are primarily distribution data on plants, animals, fungi, and microbes for the world, and scientific names data. The workshop will demonstrate how you can access different types of biodiversity data published through the GBIF platform. And we will also have a brief "bring-your-own-data" workshop to demonstrate how you can publish your own research data to the GBIF platform and get a dataset DOI with data citation tracking services to follow what your dataset is reused for and by whom.

**Comment by dagendresen** [comment]
> Usually, this works best if there are also some examples/exercises for people to work through, however, anything you are willing to share would be most welcome!

@rukayaj @MichalTorma @vidarbakken would you be able to identify some example datasets or similar that we could use for a bring-your-own-data dathon -- in particular in case nobody actually brings any data :-)

**Comment by vidarbakken** [comment]
The easiest would be to demonstrate one of the datasets we already have published for NMBU. Then the data will also be recognizable for the group.

**Comment by rukayaj** [comment]
I had an idea that @dagendresen and @vidarbakken were covering this. Do we need more people to go?

**Comment by vidarbakken** [comment]
I see from the program that there is a focus on using R. Was that the intention with this seminar? I can participate on Wednesday, but not to teach about R.

**Comment by rukayaj** [comment]
I hope it's ok if I don't attend, I'm taking some leave for a few days.

**Comment by dagendresen** [comment]
Workshop successfully completed
From the GBIF node attending: Dag and Vidar

https://www.gbif.no/events/2023/data-and-stats-forum-at-mina-nmbu.html
