### ISSUE TITLE
Data publishing workshop in Bergen 13-14th March 2023

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#129]
Venue: at the museum in Bergen
Dates: tentative dates, 13-14 March 2023
Focus on data publishing (all species groups)

**Comment by kkongshavn** [comment]
After [workshop on Nansen Legacy](https://www.gbif.no/events/2022/nansen-legacy-tromso.html)  there was talk of making something in Bergen, maybe similar [to seminar in 2016](https://www.gbif.no/events/2016/data-publishing-seminar-in-bergen.html  ). 

The idea now is to have a half day seminar with topics like "What is GBIF? Kinds of data? How to publish data? How to use data?", and then ~1.5 days where people can work with their data. 

**[Mock up registration form here](https://skjemaker.app.uib.no/view.php?id=14248431)** 

Now we are looking at week 11, March 13-14, 14-15, or 15-16 (the lunch room is booked 14:00-16:00 on the 15th, so ideally maybe Mon-Tues? How does that fit?)

Recap from email: 
From: Katrine Kongshavn <Katrine.Kongshavn@uib.no>
Sent: Monday, January 30, 2023 3:32:41 PM
To: Dag Endresen; Rukaya Sarah Johaadien; Michal Torma
Subject: Sv: GBIF seminar i Bergen
 
Jon Arvid Grynes og  Gunnar Bratbak (som begge er professorer på BIO) var veldig positive til at vi arrangerer en workshop/seminar om GBIF i Bergen. 

Vi diskuterte litt rundt formatet på forrige nodemøte, hvorvidt vi skal ha seminar og så la det gå litt tid før workshop, så folk kan finne frem data og begynne å tenke – eller om vi skal ha f.eks. en halv dag med foredrag - lunsj, og de som bare ville ha informasjon er fristilt - og så 1(1.5) dag(er) med workshop hvor man jobber med egne data. Utgangspunktet var jo litt annerledes i Tromsø hvor det var mange som kom med data fra «Arven etter Nansen»; her vet jeg ikke om folk har noe å stille med før de har fått tenkt seg om.  Innspill? 
Det jeg tenker kan være en relativt enkel ting å sette opp er å ha det på lunsjrommet og Lille kurssal på museet. Eksempelvis i midten av mars eller etter påske, hvordan er deres kalendere da?
Folk melder seg på seminar og/eller workshop via skjemaker (uib sitt påmeldingsskjema, det ser overkommelig ut) med en boks å huke av på om de har data å jobbe med, med et maks antall deltagere og plass avhenger av hvem som har data å jobbe med? (litt avhengig av hvor mange fra GBIF som kommer). Jeg vil tro det er plass til at 20 stk kan arbeide ganske ok på lunsjrommet (evt med overflow inn i kurssalen). 
Jeg antar GBIF kan dekke lunsj og kaffe(/te, snacks) for deltagere i to dager, samt reise og opphold for de av dere som evt kommer for å være med å undervise?   
Hilsen Katrine

**Comment by kkongshavn** [comment]
Way forward:
**Decide on dates** (book rooms!)
**Event page**
**Finish sign up form and distribute**, but who is our
**Target audience** - who do we invite? BIO, dept. of Natural History, but should we also include IMR? What about environmental monitoring agencies (e.g. Rådgivende biologer, Stim, Biota are all nearby)

Sign up deadline...March 1st, or can it be later (the 6th?)? Once we know how many and who, book lunch etc.,  

What am I forgetting? 
All of this needs to happen pretty quickly, since next week begins on Feb 13th - but I think it can work!

**Comment by kkongshavn** [comment]
I made a start on a event page text: 
[Event page text.docx](https://github.com/gbif-norway/helpdesk/files/10721808/Event.page.text.docx)

**Comment by rukayaj** [comment]
@kkongshavn any of those dates is totally fine for me. Probably better to do a later sign up to give more people time to find out about it, I'd say? 

I think it's probably better to cast a wider net and get more people, in terms of who we invite. The more people there are, the more worthwhile it is?

**Comment by kkongshavn** [comment]
How does it work, when and if people come with datasets - how will that get uploaded to GBIF? Must all people participating be able to access an IPT/be part of a publishing institution? 

And - a bit on the side, but we should try to figure it out anyways: I sent an email to the helpdesk a while back (18.jan, title "GRSciColl for the University Museum of Bergen?") asking about how the University of Bergen and the University Museum are listed - I didn't hear back from anyone on that. If we get participants on the workshop who will publish from the University of Bergen, it would be good to figure this out beforehand. Is this your domain, or is there someone else I should ask about it? @rukayaj @dagendresen

**Comment by rukayaj** [comment]
Re your email - yes sorry I should have replied to you, I was on leave and then packing for leaving South Africa so I forgot about it! Maybe it's easiest to have a quick zoom about it, are you free today? 

Regarding the workshop - we will make the participants accounts on the IPT. They should really be part of a publishing institution (UiB for example), but if they are not we can make creating the publishing institution as part of the workshop.

**Comment by rukayaj** [comment]
I see you copied Jenny into the email so maybe it's best if I just reply to that. I will do it now :)

**Comment by rukayaj** [comment]
> I have booked the rooms for 13-14th now.

Great! :)

> ? what do we need to finish the event page, and who can post it? I'll update the registration form with links to the event page once we have it. Is there a stock of nice images/graphics to use for things like this, or do we need to make something?

One of us can post it onto https://www.gbif.no/events/. Shall I make one now? We can just put the UiB logo and GBIF logo maybe?

> ? Which email should we put down in the registration form if people want to check if their data is suitable? [node-staff@gbif.no](mailto:node-staff@gbif.no)?

We can use that if you want to see it too, or helpdesk@gbif.no

> ? Did we settle on who we want to invite/have capacity for?

I think just open it up to everyone and we'll make a plan if there are loads of participants. 

> Thank you for the input on [the text](https://universityofbergen-my.sharepoint.com/:w:/g/personal/katrine_kongshavn_uib_no/EWJ_qf70Z0lHtZMe54112QgBcnSqkaWxYhXBfO6bBK_tlg?e=feu7zl) so far, keep it coming ;) If anyone has a nice short explanation to biologists about what kind of data is of interest, please share!

I think what was on there already seemed ok? I can try and add something...

**Comment by kkongshavn** [comment]
![UiBlogoUM_gray_m](https://user-images.githubusercontent.com/118202468/219375002-d56ebe00-2439-4af6-b524-d15773f2da35.jpg)
Logo for the museum, for the event page. 

I think the text is starting to look ok now, but there's a couple of comments you can see if you have input on

**Comment by kkongshavn** [comment]
Great, thanks @rukayaj 
Can we stick a GBIF logo into the text as well? Maybe have the UMB and a GBIF logo next to each other above "Key details", so we don't get the weird text break? (not sure how easy the page is to format, the UIB ones have very few design options to pick from)

Hyperlink "Registration link" instead of showing the link, at least up top? Or is there a reason not to do it?

Cheers, 
Katrine

**Comment by kkongshavn** [comment]
I will start inviting people today, as time is *flying* - if you have suggestions on who I should reach out to, please do tell! 
Jon Arvid Grytnes and Gunnar Bratbak have gotten the link to the vent page, and I've asked them for help getting word out on BIO. 

Also, does anyone have copies of emails used to invite people to similar events in the past? I'd like to see how it's been phrased.

**Comment by rukayaj** [comment]
Hmm it only gives me an option to upload 1 image, and it doesn't seem to let me change how it aligns or anything. So I think we have to have the logo as it is, sorry! I can insert a GBIF logo in the body of the page separately, but to me it looks a bit weird. 

I changed the registration form link and the helpdesk email link. 

I don't seem to have any example email invitations, but simple and short is always best I think :)

**Comment by dagendresen** [comment]
> Also, does anyone have copies of emails used to invite people to similar events in the past? I'd like to see how it's been phrased.

This is the invitation email we used in 2016:

Seminar Wednesday 14th December about biodiversity informatics, at the University of Bergen
Welcome to a seminar on biodiversity informatics and on open publication of biodiversity data!
The seminar is open to all and is organized by the Global Biodiversity Information Facility (GBIF.no), the Norwegian Biodiversity Information Centre (NBIC, Artsdatabanken.no), and the Department of Biology, University of Bergen.
Venue: "Lille auditorium", Høyteknologisenteret, Marieholmen, Thormøhlensgate 55, Bergen.
Time: Wednesday 14th December 2016, 09:00 - 16:00.
More information and registration form at:
http://www.gbif.no/events/2016/data-publishing-seminar-in-bergen.html

Velkommen til seminar om biodiversitetsinformatikk og åpen publisering av artsdata!
Seminaret er åpent for alle som vil delta og organiseres av Global Biodiversity Information Facility (GBIF.no), Artsdatabanken, og Institutt for biologi, Universitetet i Bergen.
Sted: "Lille auditorium", Høyteknologisenteret, Marieholmen, Thormøhlensgate 55, Bergen
Tid: onsdag 14. Desember 20016, 09:00 - 16:00.
Flere detaljer om seminaret og registreringsformulær finner du her:
http://www.gbif.no/events/2016/data-publishing-seminar-in-bergen.html

**Comment by dagendresen** [comment]
> if you have suggestions on who I should reach out to, please do tell!

I can share the planning document we used in 2016, including who we invited in 2016 by email.

**Comment by kkongshavn** [comment]
Supert, takk @dagendresen! 
It's was advertised to the museum and in the BIO newsletter on Friday - let's hope people can find the time to attend! :)

**Comment by kkongshavn** [comment]
Here's the invite that is being sent to various institutes/itions (I'm either writing directly to relevant people if I know them, or to more administrative email addresses). 

**GBIF data publication workshop in Bergen March 13-14th** 


> 
> _Hei, jeg tror dette kan være av interesse for de som jobber med biodiversitetsdata i Bergen; kan dere hjelpe meg med å spre invitasjonen?_ 
> 
> Velkommen til seminar og workshop om åpen publisering av biodiversitetsdata! 
> 
> Arrangementet er åpent for alle som vil delta, og organiseres av Global Biodiversity Information Facility (GBIF.no) og Universitetsmuseet i Bergen.  
> 
> Det vil bli avholdt 13.-14. mars på Realfagsbygget, Allégaten 41.  
> 
>  [Se lenke](https://www.gbif.no/events/2023/data-publication-workshop---university-museum-of-b.html) for mer informasjon og registrering 
> 
> Hi,   
> The University Museum of Bergen and GBIF* Norway invite you to a workshop in Bergen on open publication of biodiversity data.  
> It will be held at Realfagsbygget (Allégaten 41) on March 13-14th.     
> 
> We hope this might be of interest. More information and registration form can be found on the event page: [Data publication workshop](https://www.gbif.no/events/2023/data-publication-workshop---university-museum-of-b.html).  Feel free to share this invite!   
> 
> Hilsen/kind regards,   
> 
> Katrine Kongshavn    
> 
> *The Global Biodiversity Information Facility, [gbif.org](https://www.gbif.org/)   
> 
> https://www.gbif.no/events/2023/data-publication-workshop---university-museum-of-b.html

**I have (so far) sent invites to the following:** 
- Universitetsmuseet, avdeling for naturhistorie 
- Institutt for biovitenskap: published in newsletter «Bionytt» 
- Ekoevo bio, uib (research group)
- Biota
- Rådgivende biologer
- The Michael Sars Centre
- Havforskningsinstituttet
- NINA Bergen
- STIM Bergen
- NORCE Bergen
- NIVA Bergen
- Centre for Deep Sea Research, Bergen 

If you think of others who should be invited, please let me know!

**Comment by vidarbakken** [comment]
Some travel information by train:

An option is to take the night train on Sunday evening. It leaves at 23:05 from Oslo S. It arrives Bergen at 06:44 next morning. The basic price is NOK 1099. You can combine the ticket  with a resting chair (+ NOK 130) or with your own sleeping cabin (+ NOK 980).

On Tuesday it is possible to take a train leaving Bergen at 15:41. The basic price is NOK 439. It arrives Oslo S at 22:27.

**Comment by kkongshavn** [comment]
So far 4 people have signed up, I do hope there will be more! 🤞 
3 of those have data they want to publish, though - so that is good!

**Comment by rukayaj** [comment]
Any more people sign up, @kkongshavn ? Perhaps if there's only 4 people attending we don't need so many to attend from our side? I'm happy to go, but also happy to step out if it's unnecessary.

**Comment by kkongshavn** [comment]
> Any more people sign up, @kkongshavn ? Perhaps if there's only 4 people attending we don't need so many to attend from our side? I'm happy to go, but also happy to step out if it's unnecessary.

Hi, 
I figured we'd wait until the deadline for signing up (this Friday) and then see how many we have - might be a few stragglers. Right now there's 6 signed up.

**Comment by kkongshavn** [comment]
I'll do the final count after 16 today, but atm: 8 for seminar and workshop (6 of these have data), 2 for seminar only.

We should probably have a meeting early next week and discuss the final program & other details?

**Comment by rukayaj** [comment]
@kkongshavn is Arnfinn registered for the workshop by any chance?

**Comment by kkongshavn** [comment]
> @kkongshavn is Arnfinn registered for the workshop by any chance?

I'll list everyone in the folder we share :)

**Comment by kkongshavn** [comment]
I am pretty available on Monday - a meeting 12-13, but otherwise free. Should we try to meet during Monday (whichever time works for you) and then I/we can send out an email to the participants? 

Help me remember to say that if anyone has food allergies/other dietary concerns and didn't put that in the form, they should let me know asap - I'll try to organize the catering for lunch early next week. That also goes for those of you coming from Oslo :)

**Comment by kkongshavn** [comment]
Ooop, didn't see your message until now @dagendresen . 
Should we meet at 15:10 then? Does that work for everyone? 
I can have a draft ready for the email - nice if those presenting have thought of which topics you want to cover. 

Can those of you coming add your name and dietary preferences to the form (REGISTERED_GBIFDatapublishingseminarin...) in the folder, please? Then I have everything in one place.  

The form hadn't closed after the deadline (now it is), so we have one more signed up for the seminar.

**Comment by kkongshavn** [comment]
Alright, so food is ordered and I'll do a provision run on Friday for snacks, coffee and tea for us. 
Let me know if you think of anything in particular we should have (and that I'll find on a Rema 1000) :) 

Those of you arriving by the night train, will you go and have breakfast somewhere before coming here (please 😅)? I wasn't planning on being here at 0700, but I can be here at 8ish.

**Comment by dagendresen** [comment]
Sure, we will find breakfast and join you 8ish (or 830ish ... you decide)

**Comment by kkongshavn** [comment]
If you want to come here at 0830 on Monday, I'll have some coffee brewing :) Call when you are here. My phone# was in the mail, for those who don't have it. 

I have checked the projectors and everything works today - hopefully no gremlins will attack over the weekend. If you have a Mac or laptop with only USBC-ports, maybe bring an adapter: there should be some here, but they do tend to disappear.

**Comment by rukayaj** [comment]
Just so I remember, we said we'd make a "cheat sheet" of acronyms and technical terms and put it on the event page

**Comment by kkongshavn** [comment]
> Just so I remember, we said we'd make a "cheat sheet" of acronyms and technical terms and put it on the event page

Yes! I think that could be useful for others later on as well - do you want to start on on a google doc and then we can add terms as we think of them (and help each other give good explanations of what they are)? 
Something along the lines of 
**IPT: Integrative Publishing Toolkit.** The primary platform for sharing compatible biodiversity datasets with the GBIF network. Designed for interoperability, the IPT enables the publishing of content in databases, Microsoft Excel spreadsheets, or text files using the open Darwin Core and Ecological Metadata Language standards. [www.gbif.org/ipt](http://www.gbif.org/ipt) 
**ROR: The Research Organization Registry.** A global, community-led registry of open persistent identifiers for research organizations. ROR makes it easy for anyone or any system to disambiguate institution names and connect research organizations to researchers and research outputs. [www.ror.org](http://www.ror.org/) 
etc., etc.? 
I think we definitely should add 
**API**, **GRSciColl,**, **MUSIT**, **DarwinCore**, **OrcID**, **FAIR**.... what else? Plazi, Bionomia etc, names that might get used without an explanation? 

Also: thanks for coming, it was a success I think! I hope everyone had a pleasant trip home.

**Comment by rukayaj** [comment]
I asked around and there are some lists like this already:
https://github.com/PietrH/Abbreviations_and_Acronyms
https://www.idigbio.org/wiki/index.php/Technology_Glossary
https://www.idigbio.org/wiki/index.php/Glossary_of_Terms

Perhaps we want a shorter and simpler one though?

**Comment by kkongshavn** [comment]
> I asked around and there are some lists like this already: https://github.com/PietrH/Abbreviations_and_Acronyms https://www.idigbio.org/wiki/index.php/Technology_Glossary https://www.idigbio.org/wiki/index.php/Glossary_of_Terms
> 
> Perhaps we want a shorter and simpler one though?

Maybe we make our own, shorter version with 10-15 terms that are used in the talks? But we can def. incorporate some of these.

**Comment by rukayaj** [comment]
We can add them here: https://github.com/gbif-norway/helpdesk/wiki/Common-technical-terms-glossary
