### ISSUE TITLE
CESP 2023 project with Slovakia

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#132]
### Exploring developing a CESP project together with the node in [Slovakia](https://www.gbif.org/country/SK/participation).
[Call for proposals for the 2023 Capacity Enhancement Support Programme](https://www.gbif.org/news/54zD9vqmCpyL9dqd24Zd0z/call-for-proposals-for-2023-capacity-enhancement-support-programme-cesp) -- Deadline 2023-03-14
Some examples of previous [CESP](https://www.gbif.org/programme/82219/capacity-enhancement-support-programme) mentoring projects: [Tajikistan & Norway](https://www.gbif.org/project/CESP2022-001/kick-starting-the-biodiversity-data-publication-process-for-tajikistan), (+) [Belarus, Latvia, Lithuania, Poland & Estonia](https://www.gbif.org/project/9BKeb7ka92YPFUjhwv4UL/capacity-building-through-regional-cooperation-for-data-mobilization-in-belarus-latvia-and-lithuania), (+) [Armenia & France](https://www.gbif.org/project/CESP2021-010/mentoring-of-gbif-armenia-by-gbif-france), (+) [Cameroon, Benin & France](https://www.gbif.org/project/CESP2021-002/mentoring-of-gbif-cameroon-by-gbif-benin-and-gbif-france), (+) [South Sudan & Kenya](https://www.gbif.org/project/CESP2021-009/enhancing-capacity-of-gbif-south-sudan), (+) [Zimbabwe & Spain](https://www.gbif.org/project/3Vktr6xaI59hVPi68fCkpO/strengthening-zimbabwes-gbif-node-through-mentoring-by-gbif-spain)

**Comment by MichalTorma** [comment]
The project proposal has been published. Some of the deliverables include attending a data mobilization workshop in Slovakia ([Here to be precise](https://goo.gl/maps/cg6s6FME6t2BRKHp9)) sometimes in Q1-Q2 2024. Another tangible deliverable will be publishing minimum 800 000 records to GBIF. [Here](https://drive.google.com/drive/folders/1RDKWsyeJCCmk60Blyhpgr3q5FO07lQZn?usp=sharing) is the link to the documentation.

**Comment by MichalTorma** [comment]
We have received approval for the project funding. We need to fill in some additional information before 13.9.

**Comment by dagendresen** [comment]
Congratulations - I assume the project admin is in Slovakia (Karel?). And that he will tell you of the details we need to provide?

**Comment by MichalTorma** [comment]
> Congratulations - I assume the project admin is in Slovakia (Karel?). And that he will tell you of the details we need to provide?

He already sent me the list of issues (mostly time schedule and finance-related) and we are planning on meeting this week.

**Comment by dagendresen** [comment]
Final report still pending...??? (Maybe Karol needs some support with the report?)
https://www.gbif.org/project/CESP2023-005/unlocking-slovakias-biodiversity-through-data-publishing

**Comment by MichalTorma** [comment]
I'm sure Karol submitted the final report so I guess that just GBIF didn't publish it yet
