### ISSUE TITLE
CESP 2023 project with Tajikistan

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#133]
### Exploring developing a CESP mentoring project together with the new node in [Tajikistan](https://www.gbif.org/country/TJ/participation)
[Call for proposals for the 2023 Capacity Enhancement Support Programme](https://www.gbif.org/news/54zD9vqmCpyL9dqd24Zd0z/call-for-proposals-for-2023-capacity-enhancement-support-programme-cesp) -- Deadline 2023-03-14
Some examples of previous [CESP](https://www.gbif.org/programme/82219/capacity-enhancement-support-programme) mentoring projects: [Tajikistan & Norway](https://www.gbif.org/project/CESP2022-001/kick-starting-the-biodiversity-data-publication-process-for-tajikistan), (+) [Belarus, Latvia, Lithuania, Poland & Estonia](https://www.gbif.org/project/9BKeb7ka92YPFUjhwv4UL/capacity-building-through-regional-cooperation-for-data-mobilization-in-belarus-latvia-and-lithuania), (+) [Armenia & France](https://www.gbif.org/project/CESP2021-010/mentoring-of-gbif-armenia-by-gbif-france), (+) [Cameroon, Benin & France](https://www.gbif.org/project/CESP2021-002/mentoring-of-gbif-cameroon-by-gbif-benin-and-gbif-france), (+) [South Sudan & Kenya](https://www.gbif.org/project/CESP2021-009/enhancing-capacity-of-gbif-south-sudan), (+) [Zimbabwe & Spain](https://www.gbif.org/project/3Vktr6xaI59hVPi68fCkpO/strengthening-zimbabwes-gbif-node-through-mentoring-by-gbif-spain)

GBIF Tajikistan @samariddinbarotov
Follow up from the [CESP project 2022](https://github.com/gbif-norway/helpdesk/issues/84)

**Comment by rukayaj** [comment]
Some ideas for mentoring tasks:

- providing virtual capacity-building workshops on technical topics: digitisation techniques, data publication, the IPT, data cleaning and validation
- based on the workshop, co-create russian language resources for data publication, data cleaning and digitisation
- job shadowing for a week? 
- develop transfer of knowledge and skills between Tajikistan, Kazakhstan and Uzbekistan

**Comment by samariddinbarotov** [comment]
Hello sorry for late reply!
 My spouse gave birth I became a father again second daughter))))
So about Dags comment, Yes you are right all activate and Deliverable is the same like CESP2022-001. But I dont know what kind of new activate to put
Maybe you can request what kind of an experience Node manager Norway team can transfer for capacity-building. What kind activate if you request I can update. I can tell what is difficalyty for capacity-building which I see during implamantation our CESP project. 1. Unknowing of the language. 2. It is not completely clear yet why publish data why is importatnt. 3. Unknowing  data managment. 4. Difficulty understanding DwC standards. 5. Data cleaning etc. Maybe from the listed problems together will think about activate and Deliverable. What do think!!
About Rukaya ideas  I allredy added in Project description.

**Comment by dagendresen** [comment]
>1. Unknowing of the language. 
>2. It is not completely clear yet why publishing data why is important. 
>3. Unknowing data management. 
>4. Difficulty understanding DwC standards. 
>5. Data cleaning etc. 
>Maybe from the listed problems together, we will think about actions and deliverables.

1) Translation of key manuals, guidelines, and/or the IPT interface to Tajik (or to Russian?)

2) Workshop on data use; on open data value proposition; on data citation; ...?

3) Training on data management; exploring options for your collection management system; ...

4) Training and workshop on Darwin Core; (and other data standards ?)

5) Training and workshop on data cleaning

**Comment by rukayaj** [comment]
I think these 5 suggestions from Dag are great, and some overlap with what I already suggested so they can be combined.

**Comment by dagendresen** [comment]
Assigned project ID, CESP2023-013
Invited to submit a full CESP application with a deadline of 14 June 2023, 23:59 CET
GBIFS suggests combining this proposal with another CESP pre-proposal

**Comment by samariddinbarotov** [comment]
Hello everone!!
Hello everyone!! Dear colleagues what is your suggestion about combining this proposal with another CESP pre-proposal? I asked Farhod he said I m working in my full proposal.  
Or I should to submit it by myself not to combining

**Comment by rukayaj** [comment]
I think it would be a good idea to combine the two!

**Comment by samariddinbarotov** [comment]
Yes, I think so.
I talked with Farhod, and he wants to discuss it during our monthly meeting. Which we have 30 May

**Comment by rukayaj** [comment]
Ok good. Then we can talk about what you want next week.

**Comment by rukayaj** [comment]
Merged this project with #131
