### ISSUE TITLE
BioDATA Advanced intern from South Africa - 1 Feb to 31 May 2024

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#134]
https://docs.google.com/document/d/1p7P_Jub5OjydBwHe3wL2aCIsHemHOKVlrWwoPBC9RmU/edit

**Comment by dagendresen** [comment]
Apropos, we talked with Quentin to find some tasks for a second exchange student from South Africa today. We are planning for the second exchange student to take part in publishing some metabarcoding data Quentin has available to both GBIF (the occurrences) and to Genbank and BOLD (the sequences) with interlinks (through resolvable identifiers, materialSampleIDs).

However, for both two students, somebody need to spend some time to guide them through the data publication and data download/access tasks. Might you have some time to supervise these two students with the IPT etc...? Desalegn and Quentin can work with them on the more data content part, and the overall methodology - but they also need help with the IPT, BOLD, and Genbank data systems. For the latter, I was hoping we could in part lean on the BioMedData and ELIXIR collaboration to achieve.

**Comment by dagendresen** [comment]
I believe that Marcella is aiming at sending the intern project suggestions to Fatima this week.

**Comment by rukayaj** [comment]
> Might you have some time to supervise these two students with the IPT etc...? 

Yep, sure.

**Comment by rukayaj** [comment]
Relevant shared drive link: https://drive.google.com/drive/folders/1LEVBwUJ7N1y-MRyMENSeFn-rZEJoEnCT

**Comment by dagendresen** [comment]
Completed
News item here
https://www.nhm.uio.no/english/research/groups/mana/news/articles/biodata-intern-2024.html
https://www.nhm.uio.no/english/research/projects/biodata-advanced/activities/interns-to-oslo-2024.html
