### ISSUE TITLE
Herbarium specimen label transcription bug

### ISSUE THREAD

**Issue by rukayaj** [gbif-norway/helpdesk#141]
Adding this as a github issue so we don't forget it's an issue @MichalTorma 

We need to make a new branch of the ipt-s3 build which, similar to the main-ipt/ojdbc8 branch does an rsync back the other way, from minio source bucket to the persistent volume claim. 

Or at least we need to copy the source.txt file from the resource directory of each of the ipt datasets... 

This is because any transcription that gets done gets output to the bucket, and we therefore need the bucket changes to be reflected back to what the IPT is actually reading from.

**Comment by rukayaj** [comment]
Do we actually need to do this? We could just have a branch which uses the mounted drive... There are not many datasets on these IPTs, so we won't run into the speed issue...

**Comment by MichalTorma** [comment]
We must first test the [goofys](https://github.com/kahing/goofys) syncing and speed. That would be the fastest solution

**Comment by rukayaj** [comment]
https://github.com/awslabs/mountpoint-s3

**Comment by rukayaj** [comment]
https://github.com/juicedata/juicefs

**Comment by MichalTorma** [comment]
solved with `mc` - Minio CLI in the sidecar. see here https://github.com/gbif-norway/ipt-s3/blob/main/sidecar/sync.sh
