### ISSUE TITLE
Four osteology databases from the University of Bergen

### ISSUE THREAD

**Issue by vidarbakken** [gbif-norway/helpdesk#142]
I have started a migration from four osteology databases from Bergen to a Darwin core format. I will make a script in VBA (excel) that automatically generate all Dwc-files from the databases. The first one for birds are ready for testing. For each database it wil be an occurrence table and a MoF-file. The contact person in Bergen is Hanneke Meijer.

**Comment by vidarbakken** [comment]
Two databases are now published (Birds and Mammals). In addition there are two smaller databases for fish and reptiles/amphibians. A macro excel spredsheet is made for export directly from the Access databases to DwC.

**Comment by vidarbakken** [comment]
The reptiles/amphibians database is now published. I also tried to publish the fish database, but it has duplicates that must be removed before a publication.

**Comment by vidarbakken** [comment]
All four databases are now published with the latest database versions. The exel macro scipt (VBA) works as expected and Hanneke can prepare the DwC files herself for all four databases.

**Comment by kkongshavn** [comment]
I don't see the fish database on gbif.org yet, is it just a matter of waiting for an update to run, or do we need to publish it from the ipt (where I do see it)?

**Comment by vidarbakken** [comment]
Hei,

Den kommer nå (https://www.gbif.org/dataset/b7a6efe5-7bd8-4d51-9772-2b955fd61f95).

Vidar


Den Thu, 26 Oct 2023 04:08:04 -0700, kkongshavn ***@***.***> skrev:
 
 

I don't see the fish database on gbif.org yet, is it just a matter of waiting for an update to run, or do we need to publish it from the ipt (where I do see it)?
