### ISSUE TITLE
LivingNorway Workshop 2023

### ISSUE THREAD

**Issue by ErikKusch** [gbif-norway/helpdesk#144]
On the 24th of May we will have to present a GBIF workshop the LivingNorway Colloquium 2023.

Some key facts about this workshop:
- Duration: 3 hours
- Key talking points we were asked for:
    + A basic introduction to GBIF: how does it work, why use it, how to access data (probably introducing both directly searching/downloading from GBIF, as well as a basic intro to rgbif)
    + What to be aware of when you are beginning to work with GBIF data? Quality control, things to watch out for, etc.
    + Maybe an introduction to some key metadata fields
    + How to cite GBIF data

@kkongshavn and @MichalTorma have volunteered to help out. I believe your involvement will be particularly useful in answering questions I am unable to and in having more hands and eyes ready for the practical exercise which I have yet to put together.

I have combined old presentations, updated some numbers therein and begun to clean them up. The current version of the subsequent set of slides lives in a [GDrive folder](https://drive.google.com/drive/folders/1LzEx9hPHPyXSocAylVibMgBfryDfA5V1?usp=share_link) specifically for this workshop. 

Please make suggestions for changes or additions to the material.

**Comment by kkongshavn** [comment]
Thanks! I'll check out the slides next week, we have a workshop until the end of today

**Comment by MichalTorma** [comment]
Conference was a success, for posterity, here is a link to the info about it (there should be recordings added there in the future): https://livingnorway.no/colloquium/living-norway-colloquium-2023/
