### ISSUE TITLE
common method to map RIs 

### ISSUE THREAD

**Issue by ymgan** [gbif-norway/helpdesk#146]
Following @ErikKusch presentation of network analyses of various European RIs at the BioDT meeting in Warsaw and since our ADVANCE project has a similar deliverable by the end of September 2023, I am wondering if it is possible to set up a meeting together to explore a collaboration in this.

ADVANCE deliverables that could be relevant for this meeting:

- D1.1.3: Overview of existing RI 

and see how that could feed into 
- D1.1.4: Draft VRI architecture

Maybe we can meet in Oslo around the [Nansen Legacy marine data publishing workshop (21-22 Sep)](https://github.com/gbif-norway/helpdesk/issues/143)? We can arrive 1 day in ADVANCE or stay 1 day longer? Maybe we can come up with a paper describing a common method to map RIs? <-- forgot to credit this to Erik's idea 

@antonarctica what do you think?

**Comment by Antonarctica** [comment]
@ymgan I think this is a very good idea.
I support meeting in person in September but an earlier online meeting might be good as well.

the ADVANCE project will need a follow-up committee we already suggested @dagendresen as a possibility in the proposal.


also this paper could be relevant 
https://doi.org/10.1016/j.tree.2023.04.010

**Comment by ErikKusch** [comment]
Absolutely on board with this. I will spend some time looking into previous graph-based applications for RI coordination/overviews (e.g.; [here](https://fairsharing.org/graph/2163) and [here](https://emodnet.ec.europa.eu/en/biology#biology-background)). 

Happy for an on-line meeting whenever before September!

**Comment by ymgan** [comment]
> Absolutely on board with this. I will spend some time looking into previous graph-based applications for RI coordination/overviews (e.g.; [here](https://fairsharing.org/graph/2163) and [here](https://emodnet.ec.europa.eu/en/biology#biology-background)).

These are amazing! I will also have a look at what's out there! I like different things presented in different network graphs (including yours)! :D 

I will meet with Anton next Tuesday (Monday is holiday) and I will put a when2meet here! Have a great weekend bro! 🙌

**Comment by ymgan** [comment]
Hey @ErikKusch,

### when2meet

As promised, here's the when2meet: https://www.when2meet.com/?20217068-GVJEn 
I don't know who to invite, so I put it here.

### Proposed agenda for June meeting

Google doc [here](https://docs.google.com/document/d/18bNcDcEo8ej2-0L-jpOHRUXd-UpsUhz4A1tQEktHMnc/edit?usp=sharing). Please request access. 

- Presentation from each: BioDT and ADVANCE 
   - Identify overlaps and see how we can collaborate
- Discussion on how we can collaborate on relevant common deliverables: 
   - Overview of existing RIs 
   - Draft VRI architecture
- Brief discussions on:
  - Coordination with BioDT so that ADVANCE can develop use cases alongside BioDTs in parallel

Please add/suggest changes however you see fit 😄

**Comment by ErikKusch** [comment]
@ymgan - thanks for leading the charge on this. Access request is out and my availability is entered. The next few weeks will be pretty busy with travels so I will be available earliest in late June.

**Comment by ymgan** [comment]
Thanks @ErikKusch! No worries, when2meet shows the best day is on 23 June! Anton has set up a Zoom calendar invitation for 2023-06-23 at 11am CEST :) See you and @dagendresen !

**Comment by dagendresen** [comment]
:-) I have another meeting (at the campus in person) scheduled to close at 11:00 - so might maybe be a tiny few minutes late walking from one building to the other ...

**Comment by ymgan** [comment]
Booked my flights and accommodation! See y'all on 19 Sep!! 😄
