### ISSUE TITLE
Meeting with FHI

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#15]
Outreach meeting with the FHI about data mobilization Friday 2021-03-12

* [Google Drive folder](https://drive.google.com/drive/folders/1yapljwG7O2qbwzUG1gKXqHLU0jRT_4cK?usp=sharing )
* [Agenda, minutes](https://docs.google.com/document/d/1boZc62bAjn2ymYKQjqEsHtjukZQgblxzrulVhfBDBjs/edit#)

Topics:
* Data quality control and improvement for species occurrence data from the pest industry
* Incentives for the pest industry to mobilize and share their species occurrence data (reference GBIF OpenPSD)
* Available species occurrence data in GBIF and Artskart relevant to FHI
* Data types and terms, properties which FHI works with (and needs)
* Data gaps (coverage taxon, locations, temporal, ...)

**Comment by dagendresen** [comment]
Vidar made a list of possible companies for "skadedyr"
https://www.dropbox.com/s/k8rftqahjha5gw0/SkadedyrFirmaer_Norge.docx?dl=0
https://docs.google.com/document/d/1o9MlGN4CYG9sK-QQzPAwHFjinSnRPzCVZf4Ar8W3thk/edit

**Comment by rukayaj** [comment]
The main conclusion after the meeting was that FHI would go away and survey the four main branches/companies which cover 90% of Norway to determine what data + how to publish. From what I remember and what I understood, there was also a possibility of publishing a checklist dataset of pest species, and sometimes people send them samples to get them identified but this was not very much data (I think?). At any rate we are now waiting to hear back from them.

**Comment by rukayaj** [comment]
Next year (2022) FHI will hire a new person who can possibly handle this. Nothing will happen before this person is hired
