### ISSUE TITLE
Zenodo.org GBIF Norway community

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#150]
None of the shared passwords in our LastPass sharing center works no longer? :-)

**Comment by rukayaj** [comment]
It works for me? I just shared it with you again

**Comment by rukayaj** [comment]
I also noticed you added some documents, so once approved them. There's one left from Columbia, did they add it by mistake?

**Comment by dagendresen** [comment]
Thanks!! Yes, I also assumed the one from Colombia was added by mistake.

**Comment by dagendresen** [comment]
Thanks!!
