### ISSUE TITLE
Environmental Monitoring database (MOD) DNV

### ISSUE THREAD

**Issue by silasprincipe** [gbif-norway/helpdesk#151]
Dear all.

This dataset uploaded on GBIF by GBIF Norway seems valuable for inclusion on OBIS: https://www.gbif.org/dataset/bed78790-cbec-44af-82af-fe78e9692287

In that sense, I would like to ask, could you please include it on the [OBIS network](https://www.gbif.org/network/2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6) so that we can harvest it? 

I appreciate in advance your help.

**Comment by rukayaj** [comment]
Thanks @silasprincipe ! It's been added :) Does it look ok?

**Comment by silasprincipe** [comment]
@rukayaj everything is ok! Thanks for helping us with this dataset :) Cheers!
