### ISSUE TITLE
GB30 GNM one slide node showcase for the nodes meeting in Canberra

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#157]
### Deadline: Slides and/or videos by 13 September 2023

> We would like to invite all of you, independently of whether you are able to participate in the meeting, to consider preparing a slide on your node’s experiences on any of the topics below. We have created a template for this, so please visit [this page](https://globalnodes.gbif.org/en/prep/sharingexperience), download the template, add your slide(s) and then submit them via [this link](https://gbif.app.box.com/f/360afd35002a42bcbe18bc514f3272ee). Alternatively, if you have more to share on these topics, we invite you to prepare a video presentation between 2-5 minutes long. We will make the compiled slides and videos available to all of you ahead of the meeting. We need to receive your slides and/or videos by 13 September 2023.

> The topics for which we would like to request slides or video presentations from the nodes are:
>* **1. Your experiences with the work underway to expand GBIF’s data model**. Share details on how you are engaging with this work, and your perspective on what the new data model will mean for your node in future.
>* **2. Your experiences with GBIF’s capacity development programmes, such as [BID](https://www.gbif.org/bid) and [CESP](https://www.gbif.org/programme/82219/capacity-enhancement-support-programme)**. Share details from your involvement in projects supported by these programmes, and your views on how these programmes can best support the work of nodes going forward.
>* **3. Your experiences of working with the GBIF regional support teams**. Share any interactions you have had with the regional support teams in [Asia](https://www.gbif.org/news/2GCWBqcly9TCvaIfek5bfb/four-contractors-selected-to-provide-project-support-in-asia), and through the [BID programme](http://gbif.org/bid), as well as your ideas for how the regional support teams and nodes can best work together to strengthen and expand GBIF’s community of practice.

Topic 1: Any of us want to describe our experiences with the [new data model](https://www.gbif.org/new-data-model)? Maybe we can ask you, @lhmarsden if you are interested to help us to promote some of your efforts with the [Environmental and community measurements](https://docs.google.com/document/d/1rpxveUfN9MCdo38mJR0LaWerMo5Je0oL6p1Yym5gxH4/edit?usp=sharing) use case?

Topic 2: We could consider reporting from [CESP-2022-001](https://www.gbif.org/project/CESP2022-001/kick-starting-the-biodiversity-data-publication-process-for-tajikistan) - [mentoring in Tajikistan](https://github.com/gbif-norway/helpdesk/issues/84) (@rukaya, @torma)? Together with @samariddinbarotov

Topic 3: Will be much more relevant when the ECA support team is kick-started (any day now). But I believe we do not have anything to report from NO yet?

**Comment by rukayaj** [comment]
I've uploaded the templates to our google drive slides folder: https://drive.google.com/drive/folders/1nKMnJTKP2uKJui0uB_7DuZCx1bDnTEpB

This one we need to use https://docs.google.com/presentation/d/1qyVmP_jbvhDmTYaitvTL1bNNAi8jIoqf/edit?usp=drive_web&ouid=108452084930245973093&rtpof=true

Topic 3: Do we want to mention that we are hosting & providing support services for the Ukraine node still?

Topic 2: Yes I think @samariddinbarotov had some feedback about how they could tweak the structure of the CESP programme a bit, but I don't remember the details now.

**Comment by dagendresen** [comment]
Ukraine BioDATA activities (grant program & Kherson herbarium evacuation) and IPT hosting services are very good suggestions to add!!! (However, maybe under topic 2 - as there is not actually any formal ECA support team in place yet...?)

**Comment by lhmarsden** [comment]
Hi @dagendresen, I didn't do too much I don't think, just outlined an example of why it seems difficult to include community measurements and then commented on the work that other people did. I am in principle happy to contribute a slide, but what exactly do you want?

**Comment by dagendresen** [comment]
I have uploaded our [slides](https://drive.google.com/drive/folders/1nKMnJTKP2uKJui0uB_7DuZCx1bDnTEpB) - extended deadline is today (2023-09-15)

**Comment by rukayaj** [comment]
Closing as complete
