### ISSUE TITLE
Second set of datasets from Naturrestaurering

### ISSUE THREAD

**Issue by rukayaj** [gbif-norway/helpdesk#16]
Jørn requests some templates for an occurrence + MoF extension dataset:

> 1. Se filen Rovfugl_lista. Dette er et ganske komplekst datasett, så her trenger jeg nok en del hjelp. Antagelig i form av en ganske konkret mal, for jeg roter meg litt bort. Datasettet består grovt sett av:
>     - info om observatør (Navn, sted for observasjon (tekstlig beskrevet), tidsrom observatør var i felt)
>     - info om vær (Vindretning, temperatur etc)
>     - info om de observerte fuglene (tidspunkt for observasjon, flygeretning, først observert etc)
>     - Etterhvert også informasjon om hvor mange turbiner som er bygget og hvor mange som er i drift.
> 
> Ikke alle variabler er ført konsekvent, feks kan skydekke være registrert som enten tall eller beskrivende. De litt kryptiske koordinatene (kolonne Z-AO) beskriver punkt for
> xStart/yStart - først observert
> xEnd/yEnd - sluttpunkt for observasjon
> xK1/yK1 etc - punkter hvor fuglen kretser langs denne ruta

And a sampling event dataset: 

> 2. I tillegg har vi flere datasett som ligner det i filen Fugl_meråker. Disse er noe enklere i struktur og metodikk. Metoden er en slags transektmetode der en eller flere observatører har beveget seg gjennom et område og notert ned hvor mange individer man har observert av ulike arter. Antallet er kategorisert i grovere kategorier (I vedlagte fil er det I = 1-5, II = 5-20, III > 20). Stort sett har vi en liste med gps-punkter observatøren har beveget seg via (se filen "rute_observatør") i løpet av dagen. Hva er den beste måten å sette opp en slik type datasett på?

**Comment by dagendresen** [comment]
For birds of prey, we might also need to verify that the regulations on sensitive species data are followed
https://sensitive-artsdata.miljodirektoratet.no/Contentpages/Om.aspx

**Comment by rukayaj** [comment]
Response from Jørn: he is working on these issues and will get back to us with the data:

. Takk for hjelpen så langt! Da skal jeg gyve på grovarbeidet med selve data-rensen. Bla. oversette til engelsk, og konvertere GPS-koordinatene til desimal-grader og ikke ufullstendige UTM-koordinater..

Svar på punktene du etterspør:

Birds of prey:
- Disse dataene trenger så vidt jeg ser ikke skjerming, siden det ikke er hekkedata bare forbiflygning.
- Jeg skal oversette data til engelsk og sette på korrekt måleenhet.
- Jeg tror det holder med bare en lokalitetskolonne.
- Skal separere livsstadium og kjønn.
- Data er samlet av amatører, så ingen av dem har maskinlesbar ID, men jeg skal legge til lokalitetsID.

Meråker:
- Vi har GPS-punkter og rekkefølgen de har blitt passert, så det kan antagelig legges inn i footprintWTK som en LINESTRING?
- H er hekking ja, så legger det inn som behaviour (og omsetter til engelsk)
---
I told him LINESTRING or polygon is fine

**Comment by rukayaj** [comment]
https://ipt.gbif.no/manage/resource?r=naturrestaurering-meraker-birds

https://ipt.gbif.no/manage/resource?r=birdsvikevatnetnorway

Look through for any mistakes, check metadata, and advise on individualCount (feks 1-5, 5-15 og >15).

**Comment by rukayaj** [comment]
Jørn is fixing a few things (see email 28 Apr), he was supposed to let us know when he's done.

**Comment by rukayaj** [comment]
Published: https://www.gbif.org/dataset/91ed9272-492c-4d4d-8070-f9dd24c5f9f3 and https://www.gbif.org/dataset/69227b38-becd-49f3-bfd7-49fabd4e6ea7
