### ISSUE TITLE
Update node work plan 2024 before the November node board meeting

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#161]
The next node board meeting is scheduled for 16th November.

We want to update our [node work plan](https://docs.google.com/document/d/1d4lEnbdE_S18IqykzCnFJ84uAM0vTG18EMyOHTaGA3M/edit?usp=sharing) before the node board meeting so that the board can assess the progress.

We agreed on a deadline 10th November for reviewing and updating the work plan for 2024.
Each node project work package leader to review their own WP section.

Deadline 10 November 2023

**Comment by rukayaj** [comment]
Deadline passed
