### ISSUE TITLE
Algae data publication request from Elisabeth Lundsør via Matthew Good

### ISSUE THREAD

**Issue by rukayaj** [gbif-norway/helpdesk#17]
Algae occurrence data from a PhD project with NorConsult

EL wants to publish the database that compiled in her PhD project, includes marine phytoplankton assemblage data from inner Oslofjorden with some records back to 1898.

They are currently writing a Data Descriptor paper, which we plan to submit to Scientific Data: Scientific Data (nature.com).

**Comment by vidarbakken** [comment]
Yes, I got a reply from Elisabeth and she sent me a sample of the data format. It looked quite good, but it missed coordinates. I sent her a reply. Now I'm just waiting for an updated format. It will probably be a sampling-event dataset.

**Comment by vidarbakken** [comment]
I have received a new excel spreadsheet from Elisabeth. 
[Oslofjord Phytoplankton database_draft.xlsx](https://github.com/gbif-norway/helpdesk/files/6423111/Oslofjord.Phytoplankton.database_draft.xlsx)

I thought of making an event/occurrence dataset. Event is the station and date. A Measurements and Facts file combines the environmental data to the event. The data in the Plankton tab goes to the occurrence. One challenge is that there are two variables for amount (Abundance + unit and Biomass). The unit is Cells/l. Abundance have always values, but not all Biomasses. Any solution for this?

**Comment by dagendresen** [comment]
Maybe you can declare the biomass as [dynamicProperties](http://rs.tdwg.org/dwc/terms/dynamicProperties)?

**Comment by rukayaj** [comment]
When I open it in excel there are some values of "Presence" in the Biomass column, it looks like some strange stuff in the Abundance column too ("+", "cc"....).

**Comment by vidarbakken** [comment]
Yes, that is some old data (1896 and 1897!) without exact values ( "rare" (r), "rather common" (+), "common" (c) and "very common" (cc))

**Comment by vidarbakken** [comment]
Yes, I think the field dynamicProperties can solve it :-)

**Comment by dagendresen** [comment]
Example of a specimen with eMoF: https://www.gbif.org/occurrence/2982146324

**Comment by vidarbakken** [comment]
Elisabeth has delivered a complete dataset. I have migrated it to Darwin core and established a dataset on the IPT. Elisabeth will start to add metadata. She should also take a look at the darwin core data.

**Comment by rukayaj** [comment]
We've now published the dataset https://doi.org/10.15468/gugesq. I will also send an email to Elisabeth asking if she has mapped WoRMS LSIDs anywhere, and if not she can use my google colab in #37 to download the most likely matches to have a look at.

**Comment by rukayaj** [comment]
I have a meeting tomorrow morning 23/06 to go over the dataset.

**Comment by rukayaj** [comment]
We need to: 

1. Add higher taxon ranks to the dataset
2. Publish aphiaID as scientificnameid
3. Change basisofrecord to materialSample

**Comment by rukayaj** [comment]
All of the above tasks are complete but I'm a bit curious because there are a different number of rows in the source file Elisabeth sent to what we have published. So I have sent an email to Elisabeth asking how many records there should be.

**Comment by rukayaj** [comment]
She sent the wrong source file to us this time around, so I need to do the mapping again.

**Comment by rukayaj** [comment]
Newer version on Zenodo: https://zenodo.org/record/5031409#.YNWbRpP7RsY

**Comment by dagendresen** [comment]
Vidar has received an update of the source data - but struggles to match the data records back to the corresponding data records in the published dataset. Need to explore how to match the occurrenceID UUID onto the new updated source dataset :-D

**Comment by vidarbakken** [comment]
I think I have found a method to update the UUID's. First I make a new dataset with new UUID's. Then I use the source data from the previous publication and replace the UUID's in the new dataset with the old one (searching record by record). Hopefully most will match. However, some data are also edited, and there is no unique ID's in the original excel spreadsheet. The new dataset is some smaller as more than 1000 duplicates are removed. Otherwise is should be quite similar - I hope.

**Comment by rukayaj** [comment]
Unfortunately it's not been possible to map the UUIDs across the old version of the new dataset. So that means we're going to have to generate the UUIDs all over again :(

**Comment by vidarbakken** [comment]
We also need to replace the eventID's as well.

**Comment by rukayaj** [comment]
I got a response from them (you can see issue above), so it is fine to go ahead and do the replace. Maybe good idea to tell Elisabeth that she should try to use our version of the dataset (with the UUIDs) if possible in future?

**Comment by rukayaj** [comment]
I think this was published and is all ok now?
