### ISSUE TITLE
Vertebrate records from an Artsprosjekt

### ISSUE THREAD

**Issue by kkongshavn** [gbif-norway/helpdesk#170]
From an Artsprosjekt (NTI projects funded by Artsdatabanken) one of my colleagues has a dataset with a lot of marine invertebrate records, and a few fish (all of it museum material). The invertebrates will be published through musit, but does anyone have suggestions on how to best publish the fish so it turns up in gbif? It’s so far less than 10 records, though it might increase a little before the project ends. I was thinking that maybe she can report them to Artsdatabanken and they can publish it, would that work? @knutanders, input?  

(@vidarbakken, musit "doesn't do" vertebrates, right?)

**Comment by vidarbakken** [comment]
That is correct, MUSIT doesn't cover vertebrates. Why not publish the fishes in Artsobservasjoner? If it is a simple dataset it will work. Many Artsprosjekter publish their data in Artsobservasjoner.

**Comment by kkongshavn** [comment]
> That is correct, MUSIT doesn't cover vertebrates. Why not publish the fishes in Artsobservasjoner? If it is a simple dataset it will work. Many Artsprosjekter publish their data in Artsobservasjoner.

Do they? We have never done that, with the 15+ projects I've been involved in. Before we started using musit, we would send a (DwA) list to Artsdatabanken, and they would add it to Artsobs - but we didn't do it ourselves. 

But if it's possible, it could be a good solution! But would she not then have to upload it as her own (private) observations? That's not ideal, if so.

**Comment by vidarbakken** [comment]
Yes, I think that they have published Artsprosjekter financed by Miljødirektoratet. I will check, but I think you can register institution and dataset name in Artsobservasjoner now.

**Comment by vidarbakken** [comment]
I have been in contact with Knut Anders. It is still not possible to registert institution when reporting through Artsobservasjoner. It is on the plan, but not yet implemented. Maybe Knut Anders can help if you take contact with him?

**Comment by knutanders** [comment]
If you contact me directly Katrine @kkongshavn we can try to work out a solution for this specific dataset. Send me an e-mail :0)

**Comment by kkongshavn** [comment]
The fish collection from Bergen is going online on GBIF, and these records are in there, so it will be solved (soon).
