### ISSUE TITLE
GBIF Norway network seminar in Tromsø in May

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#175]
We are planning a GBIF Norway network meeting in Tromsø (including data publishers and data users in Norway). 

Venue at [UiT The Arctic University Museum of Norway](https://uit.no/tmu)
Dates: Thursday 23/5 and Friday 24/5
Event page at https://www.gbif.no/events/2024/2024-tromso-mai.html
Program at https://www.gbif.no/events/2024/gbif_tromso_seminar_17-04-2024.pdf

Questions
* Possible to have an online stream as well?
* Start planning who to invite - data users.
* Anders to start drafting a program - and decide if we need a program committee.

All node staff and board members are invited to join!

**Comment by dagendresen** [comment]
Travel plans: Dag has booked: Flights Wednesday 2024-05-22 OSL 14:45 - TOS 16:35 SK4422; Friday 2024-05-24 TOS 17:00 - OSL 18:50 SK4423; and hotel Radisson Blue Tromsø.

**Comment by aaltenburger2** [comment]
> Questions
> 
> * Possible to have an online stream as well?

No. Streaming online will not be possible.

**Comment by dagendresen** [comment]
NB! Per 10th May there is NO registered participants!
How do we get participants? Call for all to advertise the event!
Do we want to set a deadline for considering to cancel the event?

**Comment by aaltenburger2** [comment]
I suggest canceling internally but keeping the information online and open for sign-ups. This way, we can have an intensive online workshop with one or two participants instead of none.

**Comment by dagendresen** [comment]
Correction: Seems like we now have 8 people registered

| Name | 	Institute| Thu 23rd May | Fri 24th May | Dinner 23rd |
| - | - | - | - | - |
| Tomasz Kopeć | UiT Norges arktiske universitet | x | x | x|
| Daniel Kumazawa Morais | NFH |  x | x | x|
| Dilli Prasad Rijal | The Arctic University Museum of Norway, UiT |  x | x | x|
| Cristiane P. Bernardo | UIT | x |  | x|
| Eva Chamorro Garrido | UiT The Arctic University of Norway | x | x | x|
| KATARZYNA OSTAPOWICZ | Norwegian Institute for Nature Research (NINA) | x | x | |
| Galina Gusarova | UiT/TMU | x |  | x|
| Diego Brambilla | UiT TMU | x | x | x|

Rules (at UiO) for ordering dinner
https://www.uio.no/om/regelverk/personal/felles/bevertning-representasjon/
Nettskjema for registration no later than 2 days before
https://www.uio.no/for-ansatte/arbeidsstotte/bestille/mat-og-drikke/index.html
