### ISSUE TITLE
Reptilia notes dataset needs new publisher

### ISSUE THREAD

**Issue by andersfi** [gbif-norway/helpdesk#180]
The dataset "reptilia notes" (https://www.gbif.org/dataset/2af62ff7-0608-462e-a8f8-798e323bbd71) are missclasified with NTNU University museum as publisher. Publisher should be "Norsk Feltherpetologisk Forum". If this organization is not active, someone NTNU or NHM could publish on their behalf, but data owner should be stated in the metadata.

**Comment by dagendresen** [comment]
Do we have any contact points at [NFHF](https://www.nfhf.info/norway/)?
The dataset is reported as registered in July 2012 (same 1481 records as today).
Do you want to help update the dataset metadata description to describe NFHF as data source institution - maybe directly on the IPT?

**Comment by rukayaj** [comment]
NFHF doesn't seem to be listed as a data publisher as far as I can see. The NFHF website seems to be run by someone called Leif Yngve Gjerde, but I don't find much information about him online and I don't see an email address anywhere. 

Anyway, I changed the dataset metadata on the IPT.

**Comment by andersfi** [comment]
The organization may be dead. I think we can leave it like this for the moment and see if we get in touch. Even dead datasets needs a publisher and NTNU can be the publisher of this onward unless someone from NFHF steps up. 

Closing the issue.
