### ISSUE TITLE
Contact info Norges arktiske universitetsmuseum (Tromsø museum)

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#21]
## New name and new postmottak email address after a re-organisation

Norges arktiske universitetsmuseum
UiT Norges arktiske universitet
Postboks 6050 Langnes
NO-9037 Tromsø
E-post: postmottak@umak.uit.no

**Comment by dagendresen** [comment]
Heini Emilia Rämä has a user account and can edit metadata on each dataset from UiT from the IPT
https://ipt.gbif.no/

**Comment by dagendresen** [comment]
## GBIF Registry
https://registry.gbif.org/organization/689b40c4-ff31-4cd0-83a5-a7a828f1cd92

### Wikidata
http://www.wikidata.org/entity/Q279724

**Comment by rukayaj** [comment]
I guess this is actually done now and can be closed?

**Comment by dagendresen** [comment]
Yes. We can always re-open if useful.
