### ISSUE TITLE
Darwin Core - How many standards? List?

### ISSUE THREAD

**Issue by mdlux** [gbif-norway/helpdesk#23]
Sometimes I read that Darwin Core is a standard, sometimes that it is a body of standards. How many standards can be identified? Is there a list of those? What does exactly mean "body of standards"?

**Comment by dagendresen** [comment]
Maybe it means that [Darwin Core](https://dwc.tdwg.org/) includes, in addition to the [list of terms](https://dwc.tdwg.org/terms/), also standard for different representations such as "[Simple Darwin Core](https://dwc.tdwg.org/terms/)", "[Darwin Core Archive](https://dwc.tdwg.org/text/)", the "[RDF Guide](https://dwc.tdwg.org/rdf/)" and some other documents - each ratified by TDWG separately (?) from the list of terms?

**Comment by rukayaj** [comment]
Please open again if you still have questions, @mdlux
