### ISSUE TITLE
Query from Lars Erik regarding how to store hybrid info in DwC

### ISSUE THREAD

**Issue by rukayaj** [gbif-norway/helpdesk#26]
I have a question about the DarwinCore fields taxonRank/verbatimTaxonRank and hybrids.
While Corema so far has filled in taxon rank information (i.e. taxonomic rank of the most specific name in the scientificName) only for subspecific taxa (subsp./var./f.), we (i.e. Øyvind) will now start to do this for all taxa.
Corema has so far used, and will continue to use, verbatimTaxonRank rather than taxonRank, simply because the suggested vocabulary for the former uses the abbreviated forms (e.g. subsp.) rather than the full name (subspecies), which corresponds better with how the data are registered in Corema. I guess it really doesn't matter which of the two are used.

BUT we have a couple of questions regarding how to include information about hybrid taxa.
As far as we are aware, there is no specific DwC field to hold information that an occurrence is of a hybrid taxon - or is there?
If not, the only way to detect this is from the hybrid sign (x) in e.g. scientificName, which seems to a not very efficient way to filter out or search for hybrids...

Our question is whether it would be a good solution to include this information in the verbatimTaxonRank field; one solution could then be to use e.g. "sp., hybrid" in this field to indicate that the most specific rank is species, but that it also is a hybrid.
So far maybe so god, but then suddenly a hybrid between different ranks enters the scene, e.g. a species and a subspecies (apparently they do exist, at least in botany) - what do we do then? "Sp./subsp., hybrid"? "Subsp., hybrid" (because subsp. is the most specific of the two taxa involved)? ...?

**Comment by rukayaj** [comment]
My reply: 

GBIF doesn't have hybrid taxa in its backbone, which means that hybrid names won't get matched up, but they do get displayed correctly e.g. https://www.gbif.org/occurrence/3039210069. On this page, if you switch on 'diagnostics' (the three dots on the right of the Record heading), then scroll to the Taxon info, you will see the record was submitted with rank 'hybrid', which was changed/interpreted by GBIF to be 'Species'. 

From this thread https://github.com/gbif/portal-feedback/issues/2013 it seems like you should just put an 'x' in the scientificName. Then there is also this https://github.com/gbif/portal-feedback/issues/1354 which suggests for rank you just put whatever rank the hybridisation occurs at, e.g. 'species'. 

 It does seem a bit weird that they don't have a more formal way of registering hybrid species, and as you say it means that filtering for hybrid species is going to be tricky. But I guess this is the way they are doing it.

**Comment by dagendresen** [comment]
It does matter if taxonRank or verbatimTaxonRank is used in that taxonRank is a controlled value from a vocabulary while verbatimTaxonRank is intended for the description of rank exactly as written (on the label) (... even if this might maybe be considered to be wrong based on current interpretation). If the taxonRank vocabulary would be written as "subsp." then it is important that rank is written exactly this way **to avoid the need for interpretations** -- HOWEVER, the vocabulary for taxonRank includes "subspecies" and not "subsp.". See https://rs.gbif.org/vocabulary/gbif/rank.xml

(The very best would of course be to use the URI and not the label - however not directly supported in Darwin Core).

Bjørn Petter has also asked about the notation for hybrids in Darwin Core. He might have a better answer. I believe the "x" for hybrids should simply be written as part of the scientificName string.

**Comment by rukayaj** [comment]
Thanks Dag, good point, I'll pass it on 👍

**Comment by dagendresen** [comment]
Suggest that we could set up a vocabulary translation from the verbatimTaxon Rank = "sp." to taxonRank = "species" etc for the publication to GBIF step :-) Even if the GBIF portal is often good at guessing :-) it is better to be precise -- besides some users might use the DwC-A directly off the IPT (e.g. because so few extensions are indexed by the GBIF portal)

**Comment by rukayaj** [comment]
To:
Øyvind <oyvind@irisbg.com>;
Lars Erik Johannessen;
Cc:
helpdesk@gbif.no;

Hi both, 

Sorry for the delayed reply.

It also sounds to me like we should actually be using taxonRank rather than verbatimTaxonRank? It sounds as if the value which populates verbatimTaxonRank is input from a drop down or is possibly generated in some way from the name? So, the value we're using here is not actually what is written verbatim on the specimen sheet. So in that case I think you can leave the value as 'species', it doesn't need to be 'sp.'​

If it is a hassle to change I can just do a manual mapping for it in the IPT, so that verbatimTaxonRank maps onto taxonRank. 

If something has been identified to e.g. family level (i.e. the genus is uncertain and the species is uncertain), then 'family' is what should be input in taxonRank. But if it's difficult to deduce the rank due to the uncertainty of the identification maybe it's better that the value is left blank, and GBIF can do its own interpretation.

Best wishes, 
Rukaya

From: Øyvind <oyvind@irisbg.com>
Sent: 13 April 2021 00:17
To: Lars Erik Johannessen; Rukaya Sarah Johaadien
Cc: helpdesk@gbif.no
Subject: Re[4]: taxonRank and hybrids in DarwinCore
 
Hi Lars Erik,

I will set verbatimTaxonRank to "sp." (species), even if the species epithet is unknown (it is still a species?). It's difficult to deduce the precise level based on the taxon name. E.g. unknown species epithet could be given as <space>, 'sp.', 'spec.' and probably other terms.        
Best regards,
Øyvind

Øyvind Rustan
oyvind@irisbg.com
Mobile +47 951 07 280
Compositae AS
www.compositae.no


----- Original Message -----
From: Lars Erik Johannessen (l.e.johannessen@nhm.uio.no)
Date: 04/12/21 18:17
To: Øyvind (oyvind@irisbg.com), Rukaya Sarah Johaadien (r.s.johaadien@nhm.uio.no)
Cc: helpdesk@gbif.no
Subject: RE: Re[2]: taxonRank and hybrids in DarwinCore

Hi Øyvind,


this seems OK to me, but just to be sure; verbatimTaxonRank will be filled in also for higher level taxa, e.g. “genus” if that is the most precise level to which a specimen is determined, or “family” or whatever?


Med vennlig hilsen

Lars Erik

-----------------------------------------

Dr. Lars Erik Johannessen

Samlingsforvalter

NHM DNA-bank, Fugle- og Pattedyrsamlingene


From: Øyvind <oyvind@irisbg.com>
Sent: Monday, April 12, 2021 6:13 PM
To: Lars Erik Johannessen <l.e.johannessen@nhm.uio.no>; Rukaya Sarah Johaadien <r.s.johaadien@nhm.uio.no>
Cc: helpdesk@gbif.no
Subject: Re[2]: taxonRank and hybrids in DarwinCore


Hi Rukaya & Lars Erik,


Thanks for clarifying this issue. Based on your feedback I suggest this handling in Corema:

The hybrid "x" is already in scientificName so no changes are necessary. FYI: The correct hybrid sign is × (typographical x) which is translated to x in the DwC export.
Use verbatimTaxonRank for infraspecific ranks and set it to 'sp.' for species.  

Best regards,
Øyvind

Øyvind Rustan
oyvind@irisbg.com
Mobile +47 951 07 280
Compositae AS
www.compositae.no


----- Original Message -----

From: Lars Erik Johannessen (l.e.johannessen@nhm.uio.no)
Date: 04/12/21 17:43
To: Rukaya Sarah Johaadien (r.s.johaadien@nhm.uio.no), Øyvind (oyvind@irisbg.com)
Cc: helpdesk@gbif.no
Subject: RE: taxonRank and hybrids in DarwinCore


Hi Rukaya,

and thanks for your thoughts and links on this!

@Øyvind: did you get what you need from this?

Corema already includes the hybrid "x" in scientificName, so that is probably already OK (see e.g.https://www.gbif.org/occurrence/1208892507).

However, as mentioned, so far taxonRank has only been filled in for subspecific taxa, but this will now be changed; then hopefully GBIF will also interpret records like this example similarly to the example provided by you Rukaya.

Med vennlig hilsen
Lars Erik
-----------------------------------------

**Comment by rukayaj** [comment]
I think this might be done, but first I need to check all the mappings for the datasets.

**Comment by rukayaj** [comment]
Yes it's done, we are now using taxonRank, and the mappings are checked.
