### ISSUE TITLE
Update institutionCode from NFLI to NIBIO for Norwegian Forest and Landscape Institute datasets

### ISSUE THREAD

**Issue by rukayaj** [gbif-norway/helpdesk#3]
Action: Update all of the institutionCodes from NFLI to NIBIO for relevant datasets

Email thread:

I believe that NFLI is an institute code for the (old) "Norwegian Forest and Landscape Institute" which was merged into NIBIO in 2015. Do you think we should keep NFLI as a non-active institution code in GrSciColl? I believe that the institutionCode in the NIBIO datasets should rather be modified and updated to NIBIO (@Rukaya?).

https://en.wikipedia.org/wiki/Norwegian_Forest_and_Landscape_Institute
https://www.wikidata.org/wiki/Q7061116

Dag
REPLYREPLY ALLFORWARD
Mark as unread

Scientific Collections <scientific-collections@gbif.org>
Tue 2021-02-16 09:45
To:
Dag Endresen;
Cc:
Rukaya Sarah Johaadien;
helpdesk@gbif.no;
Scientific Collections <scientific-collections@gbif.org>;

Dear Dag,
 
Thank you for writing. My apologies for the delayed answer.
I created an entry for the institution and the collections: https://registry.gbif.org/institution/480c22da-d184-45e3-80df-9b8ef9889466
I also restored your permissions on GRSciColl so you can complete the entry (we had done some cleaned up to keep track of editors). We are working on rearranging permissions at the moment so things might change again in the coming weeks (but I will make sure to notify you and Rukaya when that happens).
 
I noticed that the institution code used in the Mycology and Lichen collections was “NFLI”, this means that they won’t be matched to the current entry for NIBIO. However you (or I) could add “NFLI” as an alternative code for NIBIO, which will allow the specimens to be matched to the institution.
 
Let me know if you have any question.
All the best,
Marie
 
--
Marie Grosjean (mgrosjean@gbif.org)
Data Administrator
GBIF Secretariat
Universitetsparken 15
DK-2100 Copenhagen, DENMARK
URL: http://www.gbif.org

Mark as unread

Dag Endresen
Fri 2021-02-12 10:49

Following the "suggest a change" link from the GrSciColl page at GBIF.

I suggest to add NIBIO as new institution to GrSciColl based on information from (and with the code NIBIO)

https://registry.gbif.org/organization/819352ad-c630-44e6-9356-d2c7aaf9866d
http://www.wikidata.org/entity/Q19383916

NIBIO is not a typical collection holding institute, but do hold at least two collection that we publish in GBIF. These collections are distinct (but still somewhat linked trough collaboration) from the collections at the museum in Oslo. (PS: Discussions to merge these collections into the museum collections have stalled, and I believe that NIBIO wishes to maintain these research collections at NIBIO).
NIBIO Mycology collection: https://doi.org/10.15468/ost7wf
NIBIO Lichen collection: https://doi.org/10.15468/zunjtd​

PS: I previously had write access to GrSciColl in the registry for Norwegian institutions and collections...

**Comment by rukayaj** [comment]
List of datasets: https://www.gbif.org/dataset/search?publishing_org=819352ad-c630-44e6-9356-d2c7aaf9866d

Changed NIBIO Mycology collection: https://doi.org/10.15468/ost7wf and NIBIO Lichen collection: https://doi.org/10.15468/zunjtd​, the others all have either NIBIO or **Bioforsk** as institutionCodes. 

So should we also change the Bioforsk institutionCode to NIBIO @dagendresen ? It sounds like it was also part of the merger. It's in Artsprosjektet 2011 - Pseudofungi. 

There are also 'biofokus', 'cbs' and 'opu' listed as other institutionCodes in datasets from this institution, see:
https://www.gbif.org/occurrence/search?institution_code=biofokus&institution_code=cbs&institution_code=opu&publishing_org=819352ad-c630-44e6-9356-d2c7aaf9866d

I will add Biofokus to GrSciColl, but maybe the others are mistakes/typos?

**Comment by dagendresen** [comment]
NIBIO
https://www.wikidata.org/wiki/Q19383916

Great to also update any institution codes BioForsk to NIBIO

**Comment by dagendresen** [comment]
There does not look like there are any records on GBIF with institutionCode = BioForsk
https://www.gbif.org/occurrence/search?institution_code=bioforsk

So adding BioForsk or not to GrSciColl I think is maybe less important...??

**Comment by rukayaj** [comment]
Ok, then I think this issue can be closed
