### ISSUE TITLE
GBIF lecture/webinar at GCU Lahore in Pakistan

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#35]
The [Government College University of Lahore](https://gcu.edu.pk/botany/) in Pakistan joined GBIF as a new [data publisher](https://www.gbif.org/publisher/d5e9316e-8600-45b4-9eb3-f6ba38460ed1) in October 2020 and has asked for an introductory webinar. Pakistan was an associate GBIF member between 2001 and 2017 - but has not established any national GBIF node (yet). Pakistan is part of the Europe and Central Asia GBIF region (ECA).

As the GBIF ECA deputy Dag will [present GBIF at GCU Lahore on 18 May](https://www.gbif.no/events/2021/seminar-at-the-university-of-lahore.html). 

Copy of the [slides as PPTX](https://www.gbif.no/events/2021/documents/2021-05-18--biodiversity-informatics-gbif.pptx).

**Comment by dagendresen** [comment]
1400 registered students participating in the webinar!

**Comment by rukayaj** [comment]
Amazing!
