### ISSUE TITLE
Common data publishing requirements between OBIS and GBIF 

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#37]
* Explore and document common dataset data publishing requirements between OBIS (for marine data) and GBIF. 
* Explore shared data publishers and map datasets between OBIS and GBIF.
* Task group including OBIS (Ward, Abby), GBIF Secretariat (Tim H, Melianie, Laura), GBIF Norway (Dag, Rukaya), and GBIF Colombia (Dario)
* Develop marine data use case example for the nodes training at the Global Nodes Meeting 2021
* Kick-start meeting on 2021-05-17
* [GDoc for mapping of OBIS and GBIF requirements](https://docs.google.com/document/d/1s9_2uL9uX9swUDk9RX0i2sgORx0wAVwivnA2uYQtFe4/edit)

**Comment by dagendresen** [comment]
Could we find a suitable "keyword-tag" for Norwegian Marine datasets and add tags through the Registry... as a possible mechanism to identify "OBIS datasets" mobilized through a national node. Might also maybe look at "keyword-tags" for fulfilling OBIS data requirements? (Such as WorMS LSID PID --> dwc:scientificName).

**Comment by rukayaj** [comment]
Could do 'marine-no' or something?

**Comment by rukayaj** [comment]
Tasks, try to do this before meeting on Thursday 1 July:

- try to find datasets which are marine (by checking if taxa is in worms, can also look at higher taxa) and tagging with e.g. marine-no tag in registry
- if a dataset contains partial records which are marine taxa, then the whole dataset should be tagged as marine, ideally we should show how many are obis records (e.g. percentage)
- Map WoRMS LSIDs to scientificNameID

Nice to have as well;
List of Norwegian datasets in OBIS that we don't have

**Comment by dagendresen** [comment]
Norway in OBIS: https://obis.org/country/161
Datasets in EurOBIS (all datasets?): http://www.eurobis.org/dataset_list

Maybe there are also _unknown unknowns_ --- maybe some datasets on the [IMR IPT](http://gbif.imr.no/ipt/) (etc) perhaps are neither in GBIF nor OBIS...??? --- which of course would be even harder to find...

**Comment by dagendresen** [comment]
OBIS, GBIF Norway, and GBIF Colombia to develop a pre-recorded talk for the Global Nodes Meeting - the deadline for pre-recorded talk is 21 June - optimal length is approx 7 minutes.

Topics for pre-recorded talk:

- Headlines of how OBIS works
- The collaboration between GBIF and OBIS
- The commonalities and differences between GBIF and OBIS
- The benefits of publishing data through both
- Examples of GBIF nodes and OBIS nodes working together now
- Some pointers for a discussion on how the node-level collaboration could look in future

Live GNM session on 1 July 2021 on OBIS and GBIF nodes collaboration.

Possibly plan a training curriculum on publishing marine data (datasets).

**Comment by rukayaj** [comment]
Develop a small service which 1) takes in dataset id, 2) looks it up in GBIF and gets list of scientific names for each record, 3) check to see if record has WoRMS LSIDs in scientificNameID (if possible), 4) counts all of these and returns a percentage of marine records, and hopefully also a percentage of those records with WoRMS LSIDs.

**Comment by rukayaj** [comment]
There is now a Jupyter notebook https://github.com/gbif-norway/marine-species-checker that can be cloned and used by anybody to check what percentage of their dataset is marine (i.e. WoRMS present) species, and it produces a download for them with the WoRMS LSID mapped onto their records, where possible.

**Comment by rukayaj** [comment]
There's an openrefine script from SiB colombia which does something similar: https://github.com/SIB-Colombia/data-quality-open-refine/blob/master/ValTaxonomicAPIWoRMS_ValTaxonomicaAPIWoRMS.txt

**Comment by dagendresen** [comment]
Nice :-) Would it be useful to make a live demonstration on using the tool on one or some Norwegian datasets? Or a slideset to show how and results. Overall goal to explore how compatible our datasets published in GBIF are with OBIS requirements :-)

**Comment by rukayaj** [comment]
Yes, so if possible I'm going to try show a summary of all of our datasets with the marine ones tags, including percentage of marine species (where there's a match in WoRMS). And then i'll show the colab notebook and explain how to do it.

**Comment by dagendresen** [comment]
Would you be able to take the lead on making such a slide set (recording) by Friday so we could send it to Ward (OBIS) -- I am a bit swamped with the BioDATA course but can contribute in the evenings (or in the coffee breaks). The target would be to present an example of a GBIF node with the capacity (and interest to commit) to work with marine datasets to meet the OBIS data requirements - and address OBIS data quality issues when flagged by OBIS.

**Comment by dagendresen** [comment]
Maybe this OBIS tool is useful: http://iobis.github.io/gbif-marine/

**Comment by rukayaj** [comment]
Yes of course, I think we did agree that I should tackle this in the last meeting. Don't stress, I am working on it now and I have been working on it today. I was planning to make the summary of all the datasets and then do the recording which is why there's nothing yet in the slides. Maybe we don't need all the datasets though because it's taking quite a long time to parse the big ones, so I'll exclude some and get just a subset.

**Comment by dagendresen** [comment]
Would be cool to add WoRMS Aphia LSIDs into the DNV dataset

Apropos - the same dataset in [OBIS (64,005 occ)](https://obis.org/institute/19437) and in [GBIF (2,036,474 occ)](https://doi.org/10.15468/q8qykg)

**Comment by rukayaj** [comment]
Some species seem to be missing AphiaIDs in MOD, e.g. Leitoscoloplos acutus. I'm checking with Thomas and adding them in as necessary.

**Comment by rukayaj** [comment]
AphiaID seems to be saved in Artsnavnebase for marine species under 'referanser':

<img width="1032" alt="Screenshot 2021-08-03 at 07 13 43" src="https://user-images.githubusercontent.com/9654499/127962031-b6b38204-5854-472c-b464-7dfea6ced9e5.png">

I am chatting to Stein about the possibility of including this in the marine datasets that we have in MUSIT.

**Comment by rukayaj** [comment]
Andreas Altenburger has sent a request to MUSIT for this data to be included, they said they needed it to come from a MUSIT user.

**Comment by rukayaj** [comment]
From the emails I see Stein said it would need to be a MUSIT-wide change, and we weren't able to get all of the museums to agree to adding aphiaID. The plan is now to include it in the new collection management system.
