### ISSUE TITLE
Map WoRMS LSIDs to scientificNameID

### ISSUE THREAD

**Issue by rukayaj** [gbif-norway/helpdesk#38]
We can do this for a few marine datasets, including DNV

**Comment by dagendresen** [comment]
Another topic is to explore the requirements for the eMoF in OBIS. And explore maybe using the eMoF for our marine datasets. But most important is to try to find data mapping approaches that works as good as possible both in GBIF and OBIS.

**Comment by rukayaj** [comment]
Covered in #37
