### ISSUE TITLE
recordedByID exported from MUSIT includes a comma?

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#43]
Example https://www.gbif.org/occurrence/919165479

recordedBy = "https://www.wikidata.org/wiki/Q21519416 | https://orcid.org/0000-0001-9645-3394," (includes an extra comma)

Interpreted and parsed by GBIF as recordedByID = "https://orcid.org/0000-0001-9645-3394,  https://www.wikidata.org/wiki/Q21519416" (???)

**Comment by rukayaj** [comment]
This is fixed for the relevant datasets now. It turned out to be very easy for me to do it in the IPT, and I don't think it's worth asking the MUSIT developers to fix it on their side, in terms of the amount of time it always takes and the fact that we will be moving to a new system in the future.
