### ISSUE TITLE
TSZA and TSZCh marine datasets from Andreas Altenburger UiT

### ISSUE THREAD

**Issue by rukayaj** [gbif-norway/helpdesk#44]
This has been added into the MUSIT export, and I have added the dataset to the IPT. Andreas is just checking and adding metadata before we publish it.

**Comment by rukayaj** [comment]
@vidarbakken tagging you just so you are aware

**Comment by vidarbakken** [comment]
Ok, good. Do you know the collections included?

**Comment by rukayaj** [comment]
I was hoping he would have filled in the metadata so I could tell you, but I'm not sure. I  just know the collection code is EVERT.

**Comment by rukayaj** [comment]
https://doi.org/10.15468/atayz7 it's up, but there's another TSZCh dataset he wants which I will publish and just keep this issue open to cover that as well.

**Comment by rukayaj** [comment]
https://doi.org/10.15468/ybjufw <- TSZCh
