### ISSUE TITLE
DNV-GL funding withdrawal / redirection

### ISSUE THREAD

**Issue by rukayaj** [gbif-norway/helpdesk#45]
DNV were issued 100 000 NOK funding in order to build an API to expose their data. This was partial funding, and relied on additional funding from Miljødirektoratet which has now fallen through. So we are coming up with other ways for them to use the money. 

DNV suggests that they use our funding in order to update the MOD database taxonomy, and check it against WoRMs. I think this is fine. In Thomas' last email he suggests they send us a list of all valid species in MOD with corresponding LSID/AphiaIDs, but I think this is unnecessary as I will be extracting it from MOD anyway. Or would it be something useful to have for the meeting in #37 . Or is there maybe something else we would prefer them to do?

**Comment by dagendresen** [comment]
If you can extract and add to the DNV dataset on IPT -- would be perfect and no need for a separate list? Maybe useful to publish a checklist of taxa surveyed by the oil companies? Potentially including species that they look for but did not find - yet?

**Comment by rukayaj** [comment]
Hmm well actually in MOD they have records with individualCount =  0, so a list of all the searched for species is actually already available there as well.

**Comment by dagendresen** [comment]
So maybe extracting a checklist might be a useful task for DNA to include in the tasks for the grant?

**Comment by rukayaj** [comment]
Thomas is using the funding to update the taxonomy and match up missing species against WoRMS.

**Comment by rukayaj** [comment]
This was finished a while ago as far as I'm aware, so closing this issue.
