### ISSUE TITLE
Global Nodes Meeting - presentation/demo

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#46]
### The Global Nodes Meeting (GNM) Monday 28 June to Friday 2 July 2021

Includes slots for presentations and demonstrations from Nodes. I have in previous planning of the GNM indicated possible contributions from GBIF Norway on 

> Topic: Adding all Norwegian GBIF data publishers to Wikidata, or the next phase of the BioDATA biodiversity informatics training program, or possibly about museum specimens as MaterialSample. Our already scheduled BioDATA training course events are currently a bit COV-pending. But we plan to launch a new digital BioDATA training course for Georgia on DNA barcoding data mobilization by June. With Dmitry Schigel and Laura Russell.

1. documenting metadata for [Norwegian institutions in Wikidata](https://www.wikidata.org/wiki/Q106706430) & [GBIF Registry](https://registry.gbif.org/node/4f829580-180d-46a9-9c87-ed8ec959b545/organization) & [GrSciColl](https://registry.gbif.org/institution/search?country=NO)
2. next phase of [BioDATA](https://www.nhm.uio.no/english/research/projects/biodata/) (Aug 2021 - July 2025; with South Africa and Russia partnership)
3. collection specimens as `dwc:MaterialSample` with `dwc:materialSampleID` (probably too premature? -- still much thinking required) see https://github.com/gbif-norway/helpdesk/issues/29 & https://github.com/tdwg/dwc/issues/314
  & [https://github.com/gbif-norway/documentation/wiki/Data-publishing---DNA-data](https://github.com/gbif-norway/documentation/wiki/Data-publishing---DNA-data/acda1c4251352f74734bed36c3062790b4d01526)
  & https://github.com/gbif-norway/helpdesk/issues/12
4. marine data  -- maybe a demo for a tool on checking percentage `WoRMS LSID` and WoRMS species names in a dataset ?? (--> see the OBIS session https://github.com/gbif-norway/helpdesk/issues/37 )
5. implementation of `recordedByID` and `identifiedByID` -- and maybe mention the return of data annotations from _Bionomia_ "back" to the MUSIT CMS ??
6. maybe (??) something about _Living Norway_ -- and the _hosted portal_ ??
7. other relevant topics/demos ??

> Pre-recorded presentations:
> We will need all pre-recorded presentations by 21 June at the latest to upload them to the website. We will provide guidelines on how to record the presentations in PowerPoint and will request that these are a maximum of 7 minutes long.

> Demos:
> We will need a description of the demo as soon as possible and by 8 June to add it to the registration form. We would also need any accompanying instructions for participants, links, and other necessary materials by 21 June to upload to the website. Demo sessions can be around 30 minutes long, depending on the theme.

**Comment by dagendresen** [comment]
### [Google Drive folder](https://drive.google.com/drive/u/0/folders/1cgKrAm1dxuJLdjKV5dvTL-ItUsgGEpMw)

(1) [Slides Norwegian data publishers](https://docs.google.com/presentation/d/1Nwz0v7puUx0yVnvmr-P5PIj9XzKoAMLOTUk_EnVlgoY/edit#slide=id.p)

(2) Slides BioDATA Advanced (2021-2025) ...

(4) Slides marine data ...

(5) Slides recordedByID & identifiedByID ...

**Comment by dagendresen** [comment]
## Draft slides abstracts

(1) Institution identifiers and metadata documentation
GBIF has taken over the operation of the GrSciColl (including the GrSciColl registry of collection holding institutions). DiSSCo Prepare is exploring the ROR and Grid registry for research institutions. The TDWG Agent Actions task group, Bionomia, and others in the biodiversity informatics community are exploring the utility of Wikidata to organize Agent metadata (and other data types as well). This lightning talk will describe recent experiences made by GBIF Norway with these Agent registry options and our recommendations to other Nodes. [SLIDES]

(2) BioDATA training on barcoding and metabarcoding data management
The first BioDATA project (2018-2022) was delayed one year because of COVID and will close in 2022. The remaining on-site training events in Armenia and Ukraine will be completed as soon as COVID travel restrictions will allow. A new BioDATA project (2021-2025) was recently granted funding from the Norwegian Agency for International Cooperation and Quality Enhancement in Higher Education (DIKU). BioDATA (2021-2025) will develop and implement a collaborative GBIF community curriculum on sequence-based barcoding and metabarcoding data management with partners from the University in Oslo Natural History Museum (GBIF Norway); South African National Biodiversity Institute (SANBI; GBIF South Africa); and the South-Siberian Botanical Garden (GBIF Russia Team). [SLIDES]

(3) Collections specimens from Occurrence to MaterialSample (occurrenceID to materilaSampleID
The GBIF infrastructure provides support for four types of datasets (1) metadata-only; (2) taxon checklists; (3) sampling event; and (4) species occurrences. Species occurrences are the most prevalent data type and describe the occurrence (sensu dwc:Occurrence) of an organism at a time and place (sensu dwc:Event). However, many of the datasets published from GBIF Norway describe collection specimens and the node struggles to fit these data points into the GBIF data models and the Darwin Core archive applications schemata for the IPT and the regime with mandatory occurrenceIDs (sensu dwc:occurrenceID). It has become obvious that data records for specimens make a much better fit for the draft dwc:MaterialSample core originally developed for describing environment DNA samples. [SLIDES to be developed ?]

(4) Interoperability for marine datasets in GBIF and links to OBIS
GBIF Norway has recently experienced an increased interest in publishing marine datasets from Norwegian data publishers. The efforts from OBIS for building improved interoperability of data models and adaptation and adjustments for the sampling event application schemata as well as successful data mobilization outreach from the node is part of the reason for this expansion of data coverage. However, there remain large data volumes from marine environments not yet mobilized and much work remaining on improving data standards and application schemas for data exchange to meet the requirements from marine data publishers. An ongoing major reorganization of the Norwegian GBIF node aims to include a new (part-time) node staff position to be responsible for marine data and liaison with marine data publishers. The current coordination efforts between OBIS and the GBIF secretariat are also of great help including efforts to identify the data quality and mapping requirements to ensure compliance with both OBIS and GBIF from one single source dataset endpoint. [SLIDES to be developed]

(5) Implementing recordedByID and identifiedByID to the museum collection CMS and integration of the data flow from Bionomia
… [SLIDES to be developed]

(6) Hosted portal for the Living Norway Ecological Data Network
… [SLIDES to be developed ?]

**Comment by rukayaj** [comment]
@dagendresen I've made a new subfolder for recorded presentations put my recording of (4) presentation on google drive here https://drive.google.com/drive/folders/1noSIP6HTuFplz28ZtcSyS0YIMJ7uB4Xg. It's fairly short, 5:19. Is there anything you want me to add to it or change? Unfortunately I couldn't get the cat to stop meowing so that's in there too, I hope it's not too noticeable. Every time I start trying to re-record he just starts meowing again, so I give up!

**Comment by dagendresen** [comment]
I have now uploaded three pre-recorded videos and slidesets.
* [GNM 2021 - GBIF Norway - Marine datasets from Norway (WoRMS LSID) (5m17s)](https://drive.google.com/file/d/1NR9_GAisXNt6cOJ1bfVVchvRj225yIWs/view?usp=sharing)
* [GNM 2021 - GBIF Norway - Node update from Norway (Wikidata, Agent identifiers, MaterialSample) (5m44s)](https://drive.google.com/file/d/1MOa7m2qR0TUpK10hSE3TwWX48P5gwT_f/view?usp=sharing)
* [GNM2021 - GBIF Norway - BioDATA (2021-2025) (3m14s)](https://drive.google.com/file/d/1ZUzifRBYV0GcBjorN9Cdmd5XciKKub_n/view?usp=sharing)

(The marine data video of course identical to the one shared with OBIS last week)
