### ISSUE TITLE
Linux kernel upgrades for our servers

### ISSUE THREAD

**Issue by rukayaj** [gbif-norway/helpdesk#49]
The following RHEL and/or Fedora hosts need a kernel upgrade. The
kernel is usually automatically updated, but a reboot is needed to
complete the update. Therefore, only a reboot is needed in normal
circumstances. Please consider rebooting the following hosts at your
earliest possible convenience:

  Hostname                      Kernel Release          Last Check-in
--------------------------------------------------------------------------------
  data.gbif.uio.no              3.10.0-1062.1.2.el7     1 hour 2 minutes ago
  nhm-ala01.uio.no              3.10.0-1062.4.3.el7     39 minutes ago

This command shows the currently running kernel version (EXAMPLE):

  $ uname -r
  3.10.0-xxx.el7.x86_64

This command shows which kernel version will be running if the host is
rebooted (EXAMPLE):

  # grubby --default-kernel
  /boot/vmlinuz-3.10.0-yyy.el7.x86_64

**Comment by rukayaj** [comment]
data.gbif.uio.no (postgres and mariadb server):
`uname -r` before reboot `3.10.0-1062.1.2.el7.x86_64`
`uname -r` after    reboot `3.10.0-1062.1.2.el7.x86_64`
^ I'm not sure why this one is the same?

nhm-ala01.uio.no ():
`uname -r` before reboot `3.10.0-1062.4.3.el7.x86_64`
`uname -r` after    reboot `3.10.0-1160.31.1.el7.x86_64`

**Comment by dagendresen** [comment]
Maybe looks like the data.gbif.uio.no server was already up-to-date while the nhm-ala01.uio.no was behind ??? Do we still actually plan to use the ALA server? (Maybe for other use than spinning up an ALA portal???)

**Comment by rukayaj** [comment]
I am actually using the ALA server as our "web" server, separate to the database server. So it is actually running all of our docker containers. [More info in our wiki ](https://github.com/gbif-norway/documentation/wiki/List-of-services-and-servers). I rebooted data.gbif.uio.no again but same result. It is a bit weird the version number is lower, I'll ask unix-drift about it.

**Comment by rukayaj** [comment]
I think this is ok now.

**Comment by rukayaj** [comment]
We received another email about this, so I'll have to follow up again with unix-drift@usit.uio.no again.

**Comment by rukayaj** [comment]
Phew ok, this server is now updated. I'm adding this comment as a record for what we finally discovered had happened:

> The reason for the reboot not working was that there were no new kernels installed! Turns out the machine hasn't been updated for several months! One reason "/var" being full, and another that one of the pgdg repoes upstream does not work (anymore?). I cleaned /var somewhat and disabled the failing repository. Turns out there are near 500 packages waiting to be installed! But now there are package conflicts which have to be solved.

Following that:

> data.gbif.uio.no has two yum repositories that are not approved for use
at UiO:

>   docker-ce-stable
>   ius
> 
> The latter is the one making problems in this case. The following needs
> to happen:
> 
> * The repositories listed above should be removed
> * All packages from the repositories should be removed
> * The host should be fully upgraded (yum -y upgrade)
> * The host should be rebooted

After I removed ius, there were more conflicts so I had to remove python36u as well (`sudo yum remove x`). Trond then suggested also removing `ius-release` as well, which I have done. 

I have just sent them an email to confirm it's ok to be running docker on the other server... I'm not sure why it was a problem with this one and not the other? Anyway, no reply yet, I will just keep updating this issue with progress.

**Comment by rukayaj** [comment]
> Strictly speaking it's av violation of our Docker policy, which states that you should use the tools and software that comes with the OS:
https://www.uio.no/tjenester/it/sikkerhet/lsis/tillegg/teknisk/sikring-av-containerbaserte-tjenester.html

> However, so many are violating this part of the policy and are using the docker-ce software, that I feel reluctant pressuring you to fix immediately. Leave it be for now, but we may require action on your part in the future.

Possibly we should find a dedicated server with easy docker deployment in the future.
