### ISSUE TITLE
Support med anvendelse av artslister med taxon data for app-utvikling

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#57]
Are Pileskog from Blåst film is asking for an online virtual meeting to discuss solutions for accessing taxon data and species vernacular names available from the GBIF data portal.
Would you, @rukayaj have time to take the lead on giving him guidance with data access? (If he makes contact with you).

**Comment by rukayaj** [comment]
Yes sure, I haven't received any email from him yet though.
