### ISSUE TITLE
Assessment of new collection management systems to replace MUSIT

### ISSUE THREAD

**Issue by rukayaj** [gbif-norway/helpdesk#60]
The MUSIT collection management system is going to be replaced. A group of users have been testing PlutoF and Specify, and later on Arctos will also be tested and assessed. 

We've had some meetings where we go through PlutoF and Specify together, but naturally the CMS users are interested in different functionality compared to GBIF Norway, who are more interested in publishing data. So I've been in separate conversation with Lauri (who is our technical contact for Specify) and the PlutoF support team to find out how data publishing will work. 

### Specify
Lauri thinks the easiest thing to do regarding data publication will probably be to have a similar set up to what we had for MUSIT. The Specify database will probably be MariaDB, and he suggests that we make database views to compile the data as we want, and then connect them to the IPT. I guess we would be responsible for setting up and maintaining the views, but I've asked him how he sees it working. 
Re ScientificNameID for marine species #37 - he says that it's very easy for them to start importing the WoRMS LSIDs into whatever field we choose. 

### PlutoF
They suggest migrating all of our datasets from the IPT and publishing them using the built-in PlutoF GBIF publication functionality. Seeing as this is a completely different UI I've suggested we do a test run on e.g. the UiO vascular plants dataset. We should probably actually do this with Specify as well, but we have a bit more control there at least so I am a bit more concerned about checking out PlutoF first. 
Re ScientificNameID for marine species  #37 - this is on their to-do list for their taxonomic backbone.

**Comment by dagendresen** [comment]
Apropos, is the [DINA version of Specify](https://www.dina-project.net/wiki/Welcome_to_DINA) maybe still different (forked) from the main Specify CMS evaluated here? I think that DINA might have modules for DNA data management that the standard Specify does not have...

**Comment by rukayaj** [comment]
Lars Erik has been at these meetings, so I guess he's comparing it to Corema for DNA stuff as well. I'm not sure why they aren't considering DINA as well... 

Lauri did mention the specify export to DwC as an option as well. I think it's worth evaluating both ways, then.

**Comment by rukayaj** [comment]
This was completed a while ago. The job is going out to tender.
