### ISSUE TITLE
Nansen Legacy data models

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#64]
Copied here from email helpdesk request 2021-11-10:

This is a short question that requires a lot of contexts. I have tried to be as clear and concise as possible.

I work as a data manager on the Nansen Legacy project, a multidisciplinary project involving 10 Norwegian research institutions. There are many biologists working across the project, and I am trying to encourage them to publish their biodiversity data as DwCA. Many of them will be wanting to publish their data with GBIF, so I would appreciate your feedback on exactly how these data should be structured.

On the cruises, researchers log metadata in sample logs created using a template generator, based on Darwin Core. This is a development of something that was originally started by yourselves I believe.
https://www.sios-svalbard.org/cgi-bin/darwinsheet/?setup=aen

The metadata are cleaned, correcting mistakes and ensuring consistency across the project where possible. They are collected into a single database. The metadata catalogue can be found online on the SIOS webpage.
https://sios-svalbard.org/aen/tools (can be slow to load)

One advantage (of many) of this approach is that the researchers have already logged a lot of their metadata in a standardised way (mostly) at the time of collection. Therefore, it is possible to automatically create elements of a DwCA by harvesting data from this metadata catalogue.

I have been developing a tool that does exactly this. Please see attached an excel file that includes 3 sheets. The research would be able to create their own file and check and fill in any missing metadata. They will also be able to log the data themselves. The idea is that these sheets could be fed into the IPT to create an event core, occurrence extension, and measurementAndFact extension. Some explanations of what is included in each are below since I don't have the XML files at this stage 🙂. I have colored in green anything that I am particularly unsure about, where your feedback would be most appreciated.

### Event Core:

- This includes sampling events. In this case, it is a series of trawls. It could also be hierarchical, like a CTD (parent) with Niskin bottles (children). In this case, the parentEventID term will be included.
- Minimum and maximum depth missing were not included in the metadata catalogue. The user would fill this in.
- Sampling protocols are published with a DOI. I will be populating the dwciri:samplingProtocols section with this DOI at some stage where possible (dwc:samplingProtocols not standardised so not always possible).

### Occurrence Extension

- List of species
- Contains a measurementID column. In some cases, people take measurements for a community of species. Therefore, multiple occurrences might have the same measurementID. Is this a useful addition or should they just link measurements to occurrences via the eventID column? Not useful for this particular dataset, but there will be instructions to remove columns that are not used.
- Would it also be beneficial to include eventDate, decimalLongitude, decimalLatitude in here to make it more easily readable? Or is duplication of fields discouraged?

### MeasurementAndFact Extension  

- Rows 2-17:
- - Mapping of gears used for sampling events (in event core) to controlled vocabularies. I need to do more work on this.

- Rows 18-2586:
- - Any additional metadata is logged in the metadata catalogue for each occurrence. These were logged as specific fields as taken from the template generator, but no comparable Darwin Core term exists in many cases. I have tried to map the measurementType and measurementUnits to controlled vocabularies where possible. The measurementValues were mostly logged as free text so it isn't possible to map these automatically to controlled vocabularies, the users will have to do this themselves (but I suspect won't).
- - In some cases, there isn't a measurementValue where there wasn't one provided. I will probably delete these rows.
- Rows 2587-end:
- - 'Empty' rows where the user's data will go. In the attached example, the researchers divided each specimen (fish) into different tissue types (e.g. liver, gonad...) and took measurements based on these. These measurements (the data themselves) are not included in the metadata catalogue. Therefore the researchers will have to fill in these. However, I hope that by providing them with the measurementID, occurrenceID, and eventID all linked together, they can easily populate these based on the measurementIDs and occurenceIDs that they already have in their data files. I think this will be easier than mapping the IDs to each other themselves. Many of them don't code very much.

Is this a sensible way to structure such a dataset, or would you recommend something different? 

Once we are happy with this, I will add a README on how the researchers should fill in the rest, and some directions on how to use the IPT to generate a DwCA from this. I will most likely also colour code some information to guide the researchers on what needs to be filled in or checked and in what way.

Phew! That was a long one. Thanks for your time.

**Comment by dagendresen** [comment]
Many thanks for your efforts to guide researchers on the Nansen Legacy project on Darwin Core data publication!! Your efforts are much appreciated!

### Dynamic source data import to DwCA

Yes, I believe the spreadsheet template is based on work by the previous data manager at the GBIF node. The current data manager at the GBIF-node is on leave this week, and I am sure she will look into this in much more detail than I can when she is back next week.

The GBIF data publishing toolkit (IPT) has some functionality to build DwCA-datasets from "external" data sources - through (1) simple files (including MS Excel spreadsheets) and (2) through direct SQL database JDBC connections.
https://ipt.gbif.org/manual/en/ipt/2.5/manage-resources#source-data

For example - with the museum databases we previously solved scripted dynamic data publication by pulling data-dumps into a MySQL database in a daily cron-job and connecting this MySQL database to the IPT. Now we have configured a direct JDBC link from the source Oracle database to the IPT instead (and configured the IPT itself to refresh with new data from the source in a daily or weekly routine).
https://ipt.gbif.org/manual/en/ipt/2.5/manage-resources#published-versions

I am not sure if the IPT has any native features to schedule publication from data files on an URL such as directly from on the Nansen Legacy metadata catalog - or if you would need to read these into a SQL database by a cron-job to enable this. Maybe @Rukaya knows more details here?

The GBIF portal expects EML structured metadata based on a slightly simplified GBIF-EML-profile (declared as an XML Schema):
https://rs.gbif.org/schema/eml-gbif-profile/1.1/eml-gbif-profile.xsd
We have normally solved this by entering the EML directly into the IPT, but you could of course generate the EML XML yourself and add it directly into the DwCA by a script.


### MeasurementOrFact

Notice the limitation of the DwCA star schema only supporting one layer of "extensions" and that ALL extension data records always link to the core record. This means that when you have chosen to structure the DwCA as an Event core dataset, all records in the extensions will relate in a one (Event) to many (extension records) relationship. This means that data records in the MeasurementOrFact (MoF) extension will not relate to records in the Occurrence extension!

MoF = https://rs.gbif.org/extension/dwc/measurements_or_facts.xml

OBIS has developed a *hack* to enable direct links between MoF records to Occurrences by adding a column occurrenceID in an ExtendedMeasurementOrFact (eMoF) extension:

eMoF = https://rs.gbif.org/extension/obis/extended_measurement_or_fact.xml

Using this hack, you could (in my interpretation) link from the eMoF extension to *any* globally uniquely identified Occurrences! (published in any DwCA, or in principle also Occurrences not yet published). The GBIF infrastructure does not (yet?) support the eMoF and will not try to interpret such data mappings! But OBIS does!!

Notice that because you have included an occurrenceID to the MoF in your spreadsheet, you are not using the standard DwCA MoF, but the modified OBIS eMoF.

I also notice that the MoF in your spreadsheet includes some columns not supported in the DwCA MoF. I fully agree with your suggestion to use the dwciri version of the terms!!!!! But this is unfortunately not yet (!) supported by the GBIF IPT DwCA infrastructure yet. We did submit a pull request for adding the dwciri terms after an OBIS workshop in Brussels some years back.
https://github.com/gbif/rs.gbif.org/pull/13

This addition of IRI terms was quickly added to the *Sandbox* MoF -- BUT unfortunately not progressed to the *deployment* MoF yet :-(
https://github.com/gbif/rs.gbif.org/commit/90896b2ef8a14efff34cea2ca977696b40b79ed9
https://rs.gbif.org/sandbox/extension/measurements_or_facts.xml

Notice that OBIS has added some *home-made* alternative terms into their eMoF hack:

dwciri:measurementType (in OBIS eMoF --> measurementTypeID)
dwciri:measurementValue (in OBIS eMoF --> measurementValueID)
dwciri:measurementUnit (in OBIS eMoF --> measurementUnitID)


### Occurrence extension

The Occurrence extension does not support adding a measurementID column directly. (See the eMoF OBIS hack instead).

I believe that the GBIF portal will only read the eventDate, decimalLatitude, and decimalLongitude from the Event core record, and not the "duplicated" terms in the Occurrence extension. (You might perhaps build one more layer of hierarchical nested Events with parentEventID - but including more specific date and geo-coordinates in the Occurrence extension will not destroy anything either, even if not read by the GBIF portal).

**Comment by lhmarsden** [comment]
Thanks very much for your detailed reply, Dag. 

I will add eventData, decimalLatitude and decimalLongitude to both the occurrence extension and eMoF extension to aid the researchers in checking their files, and also perhaps making it more human-readable.

I will remove the measurementID from the occurrence extension.

I think XLSX will be easier for the researchers to work with than SQL in this case. Harvesting metadata from the metadata catalogue requires some tricks anyway, so it would not be easy to set this up. 

I will rename the MoF extension to an eMoF extension and rename the columns in line with OBIS's ID terms. I will therefore have to recommend that they publish to OBIS instead of GBIF, until GBIF supports this. 

Some people may be particularly keen on publishing to GBIF. If so I can recommend that they first remove the 'ID' columns and create an MoF extension rather than an eMoF extension. However, including the occurrenceID column in the MoF extension is important for much of our data where we take multiple measurements from the same sample (occurrence). I do not see any easy way to do this in line with what GBIF supports, but maybe you have some ideas?

You say that GBIF does not interpret these mappings. Does this mean datasets can not still be included with an occurrence ID in the MoF extension? Can they be included but these relationships will not be interpretted? The standalone DwCA should still be 'interprettable' by someone who downloads the data.

**Comment by dagendresen** [comment]
Using the DwCA eMoF does not make any practical problem for publishing to GBIF! OBIS and GBIF are in the process of harmonizing and merging the data publishing infrastructure. Publushing to OBIS would thus in practise be the very same as publishing to GBIF - however for OBIS to approve a dataset published (on GBIF or anywhere) they require inclusion of the WoRMS Aphia taxon identifier. To be compliant with OBIS you would thus need to add taxonID to the occurrence tab and populate it with the WoRMS Aphia ID.

https://www.marinespecies.org/index.php
https://doi.org/10.14284/170

When you design the data templates for the Nansen Legacy, you may of course divert from Darwin Core!  The useful tip is to stay interoperable with Darwin Core and the DwCA format for your data to be reusable with the large group of biodiversity researchers that will be able to receive and reuse DwC and in particular DwCA formatted data.

Darwin Core is a minimum set of terms with wide agreement. The Biodiversity Standards society (TDWG) is working to expand the standards to capture more information. And I think that including not-yet standardised terminology that you need in the data templates would be a good strategy. Darwin Core has two pathways to include not-yet standardized information (including in a DwCA). You may use the dynamicPropoerties term in the Occurrence core or extension - or you may use the MoF (or eMoF) extension.

I do not suggest that you replace the XLSX templates with a SQL database. I only wanted to mention that (I do not believe that) the IPT data publishing software can read data directly from a Nansen Legacy data repository dataset URL. And that one solution could be a cron-job that is reading new or updated datasets into a SQL database -- which the IPT is well capable to synchronise data off from. This is of course a service that the GBIF-node can establish for you!!!

Alternatively you could also produce complete and valid DwCA natively in the Nansen Legacy data catalog and publish in GBIF through API data publishing. This is also steps that the GBIF-node (and(/or the GBIF secretariat, and/or the OBIS data manager)) of course can support establishing.

Choosing between the MoF or the eMoF makes in practise no difference for publishing the datasets in GBIF!! GBIF does not index neither the MoF nor the eMoF!! The information published in Mof/eMoF/dynamicProperties will be discoverable in GBIF but will NOT (yet) be searchable through neither the human-readable GBIF portal nor the machine-readable GBIF API.

I am not sure if these extra terms are searchable from the OBIS data portal (and API) yet. But OBIS will be/is anyway fully capable of ingesting datasets published on an IPT in GBIF. I am not aware if OBIS actually has any other datapublishing pathways than IPT (and GBIF).

> You say that GBIF does not interpret these mappings. Does this mean datasets can not still be included with an occurrence ID in the MoF extension? Can they be included but these relationships will not be interpretted? The standalone DwCA should still be 'interprettable' by someone who downloads the data.

You may of course include a measurementID (or any terms you want) in the occurrence tab of the Nansen Legacy template and still be fully compliant to publish the data in GBIF. However, if you use the IPT there is no way to map measurementID to the Occurrence extension (or the Occurrence core for that matter). IPT will thus be able to include measurementID from a column in the Occurrence tab without some data-wrangling. And DwCAs produced by the IPT will never include a measurementID in this place of the data model. However, if you produce the DwCA yourself with measurementID in this position (as a parameter of the Occurrence) you will still be able to publish these DwCA in GBIF (and OBIS if including the WorMS Aphia ID) - but the measurementID in this position will simply be ignored by GBIF during data ingestion. Any user can of course parse the metadata in the GBIF infrastructure to discover the DwCA endpoint with the measurementID intact!! But why??

**Comment by dagendresen** [comment]
@lhmarsden  Including measurementID in the Occurrence data table would limit the number of MoF for each Occurrence to only one MoF per Occurrence?

**Comment by dagendresen** [comment]
@lhmarsden could it be an idea to ask OBIS if they might be interested to join a workshop together - maybe in Svalbard - maybe early next year? To explore developing guidelines (and data templates) for publishing marine biodiversity data together...? 

Might such an event be of interest to OBIS @pieterprovoost @albenson-usgs ??

**Comment by dagendresen** [comment]
See also https://github.com/biodiversity-aq/data-mgt-templates

**Comment by lhmarsden** [comment]
Thanks again Dag.

My idea to include a measurementID in the occurrence extension is for cases where a single measurement is taken based on multiple occurrences. Community measurements, like total organic carbon or similar. I think in most (maybe all cases) the community measurements are based on every occurrence from a single sampling event, so this might not be necessary. However, in theory someone could take a community measurement based on for example half of the occurrences in a sampling event. Currently a MoF or eMoF extension allows me to only relate a measurement to a single occurrence, as far as I am aware. 

This might be an unrealistic example with no real-world cases. So I will remove the measurementID from the occurrence extension as suggested.

My intention was not to limit each occurrence to a single measurement. I was hoping that I could still reference the same occurrence multiple times in the MoF extension. I was trying to make the 'many-to-one' functionality work both ways. But alas, perhaps that is ambiguous and doesn't work.

I would certainly be interested to hear whether such a work should would also be of interest to OBIS. That sounds very interesting indeed!

**Comment by pieterprovoost** [comment]
@lhmarsden We are collecting marine use cases to inform the development of a new data model at GBIF. I don't think your case is totally unrealistic and it seems like a good candidate to add to our our list [here](https://docs.google.com/document/d/1wmhy-pkYLUaPHyfy_BD1-ycT7a1l9lGudYoG_zbX-Yo/edit?usp=sharing). In the current data model relationships between occurrences and measurements can probably be modeled using the [Resource Relationship extension](https://rs.gbif.org/extension/dwc/resource_relation_2018_01_18.xml), but that's going to add some complexity to your templates, and at least at OBIS we are not indexing this extension.

@dagendresen I would definitely be interested in joining such a workshop.

**Comment by dagendresen** [comment]
> However, in theory someone could take a community measurement based on for example half of the occurrences in a sampling event. Currently a MoF or eMoF extension allows me to only relate a measurement to a single occurrence, as far as I am aware.

With an Event Core DwCA you may absolutely relate the MoF to the entire Event -- but then measurements would be for the Event and not for the Occurrences also linked to the Event!

Another way to link a community measurement to a set of Occurrences would be to use the [ResourceRelationship](https://dwc.tdwg.org/terms/#resourcerelationship) extension.

resourceID = your-occurrenceID1
relatedResourceID = your-measurementID1

resourceID = your-occurrenceID2
relatedResourceID = your-measurementID1

resourceID = your-occurrenceID3
relatedResourceID = your-measurementID1

... etc

**Comment by albenson-usgs** [comment]
I haven't fully read through this thread but I'm wondering if the community measurement issue is similar to [this issue](https://github.com/iobis/env-data/issues/10#issuecomment-777087046)?

**Comment by lhmarsden** [comment]
Hi @albenson-usgs yes I believe this issue is similar, but I don't think it is resolved in that thread - unless I missed something. 

I can see how it is possible to record community measurements in a MoF (or eMoF) extension, where the community measurement is taken based on all occurrences in an event. However, not when it is taken based on a subset of the occurrences in an event.

@dagendresen @pieterprovoost I think this would work, though the details aren't 100% clear to me. How would I relate multiple occurrences to a single measurement? Nonetheless, this is probably not a common example, and is therefore probably something I don't need to think about for my half-filled-in templates. We can approach this case-by-case within the project, if there are any cases.

> With an Event Core DwCA you may absolutely relate the MoF to the entire Event -- but then measurements would be for the Event and not for the Occurrences also linked to the Event!

Is this a problem if one is measuring based on the whole community sampled during a single sampling event?

These are probably questions that would be useful to discuss at a workshop or meeting. Where is everyone based? Perhaps if you are all on the mainland it makes sense for me to travel down rather than you up? And do you have a preference for roughly when would (or would not) be good to host this?

**Comment by lhmarsden** [comment]
I gave the example with the ResourceRelationship extension more thought, and can see that this could be done with multiple rows  linking the same measurementID to various observationIDs.

**Comment by lhmarsden** [comment]
@pieterprovoost I have added a case study to https://docs.google.com/document/d/1wmhy-pkYLUaPHyfy_BD1-ycT7a1l9lGudYoG_zbX-Yo/edit#

Let me know if anything else is required.

**Comment by dagendresen** [comment]
>> With an Event Core DwCA you may absolutely relate the MoF to the entire Event -- but then measurements would be for the Event and not for the Occurrences also linked to the Event!

> Is this a problem if one is measuring based on the whole community sampled during a single sampling event?

I believe that reporting DwCA Event core eMoF/MoF measurements for properties of the organisms taking part in the occurrences linked to the event are not directly breaking anything. But I am worried that the relationship might be ambiguous for someone wanting to re-use the data. And that using ResourceRelationship would be less ambiguous.

**Comment by rukayaj** [comment]
@lhmarsden it looks like most of your queries have been answered by Dag and Pieter. I would agree with Dag that using ResourceRelationship is probably the clearest way to associate the community measurements. 

For the data import part I am a little confused, so please correct me if any of these assumptions I'm making are wrong: 

- It looks as if the SIOS database is holding both metadata and the actual data 
- You are have an automatic method of generating some XLSX template spreadsheets from SIOS. These spreadsheets are containing the data (+ metadata?)
- However, these data spreadsheets are not always complete and the researchers will need to fill in more data fields? Or is it just missing metadata the researchers need to fill in? 
- And then it sounds like you are going to manually load these spreadsheets into the IPT? 

I would suggest if you have access to the SIOS database you instead make some database views containing the desired Darwin Core fields, you can make the views so the fields are arranged exactly like in your spreadsheet. You would then be able to connect the IPT directly to the database views. If you need any additional data fields, just add them to the SIOS database. 

The advantage of doing it this way is that there's less manual work so it's more easy to automate, and if there are any changes, corrections or updates to the SIOS data you don't have to manually import those changes into your XLSX extracts. I might be misunderstanding things completely, but this is just what I think at the moment based on my understanding of the situation. I'm also free for a zoom chat if it's easier for you to show me what you mean on video.

**Comment by lhmarsden** [comment]
Thanks @rukayaj 

> It looks as if the SIOS database is holding both metadata and the actual data

The metadata catalogue should only host metadata. Of course one person's metadata is another person's data... but what the owners consider to be data should not be here. This provides an overview of all the data collected.
https://sios-svalbard.org/aen/tools

SIOS also hosts a data access portal, but if the data are already published we don't need to create a DwCA. So far none of the data suitable to be published in a DwCA from the Nansen Legacy project have been published - to my knowledge!

> You are have an automatic method of generating some XLSX template spreadsheets from SIOS. These spreadsheets are containing the data (+ metadata?)

This is in development. It will be a way of harvesting metadata from the metadata catalogue (above). They will need to log the data themselves. The tool won't do anything to create an EML.xml file - metadata like abstract, title, PIs have been poorly recorded in the majority of cases, so the researchers will have to start from scratch here. This should be easy enough if we can find a method compatible with using the IPT.

> However, these data spreadsheets are not always complete and the researchers will need to fill in more data fields? Or is it just missing metadata the researchers need to fill in?

They will never be complete, see above.

> And then it sounds like you are going to manually load these spreadsheets into the IPT?

Ideally. Hopefully we will soon have our own IPT server at SIOS (perhaps using NIRD) that researchers can login to and create their own. For those who don't code, and aren't familiar with XML, I think this will be the easiest. I hope that it will be possible to create all the various extension files using the IPT?

 > I would suggest if you have access to the SIOS database you instead make some database views containing the desired Darwin Core fields, you can make the views so the fields are arranged exactly like in your spreadsheet. You would then be able to connect the IPT directly to the database views. If you need any additional data fields, just add them to the SIOS database.

>The advantage of doing it this way is that there's less manual work so it's more easy to automate, and if there are any changes, corrections or updates to the SIOS data you don't have to manually import those changes into your XLSX extracts. I might be misunderstanding things completely, but this is just what I think at the moment based on my understanding of the situation. I'm also free for a zoom chat if it's easier for you to show me what you mean on video.

A zoom chat would be useful, so we can discuss the details, whether this is compatible with our setup, and if so how this would be configured. 

Some context that might be useful in advance of the meeting.

I have access to the metadata catalogue (as a PostgreSQL database). Since we have a lot of fields which are applicable to only a small subset of the records, we store most non-essential fields in an h-store column, rather than their own column. 
https://www.postgresql.org/docs/9.1/hstore.html

I send a CSV of this database to my colleagues who make this available via SIOS using Drupal. How this is done on Drupal is a black box to me! 

It is more tricky to access metadata from the hstore columns. In the program that I am developing, I first retrieve a subset of the rows (samples) of metadata from the CSV based on desired IDs. I then dump all the hstore fields to separate columns. This functionality would also have to be built in to any method connecting the IPT to the metadata catalogue.    

I don't (and in most cases never will) have access to the data before they are published. We don't want to make these available via the metadata catalogue. Also, sometimes, there isn't a one-to-one relationship between what is in the metadata catalogue at the data. Not everyone logged all their subsamples. Community measurements aren't included either.

**Comment by rukayaj** [comment]
@lhmarsden ok  I see now, thanks for the explanation! Seeing as the metadata catalogue does not contain any of the actual data I think there's not really much point in making a database connection with the IPT. It's not actually possible to connect the IPT to **metadata** in a database, only to **data** in a database. The metadata input interface is totally different from the data input + data mapping interfaces. So I think the approach you describe (generating some templates, including as much metadata as possible, and getting the researchers to fill out all the rest) makes sense. 

I guess the bottleneck the will probably be in getting the researchers to clean + map their data. In my experience people often need some one-on-one help, especially when mapping their own data onto Darwin Core terms. I'm available to help with that if you need any extra hands.

**Comment by lhmarsden** [comment]
@rukayaj Thanks for your offer to help, I will be in touch when we get to that. I agree mapping data onto Darwin Core terms will be a challenge for some people.

**Comment by dagendresen** [comment]
Use case also captured as an [OBIS use case here](https://docs.google.com/document/d/1wmhy-pkYLUaPHyfy_BD1-ycT7a1l9lGudYoG_zbX-Yo/edit#).

**Comment by lhmarsden** [comment]
Hi @dagendresen, @rukayaj, @pieterprovoost, @albenson-usgs,

Would you be available for a chat about the potential workshop to discuss how to publish a wide range of biodiversity data together? I do not have much scheduled before Christmas, and plan to work most of the days over the festive period (except the days everyone has off). So please, suggest a time that is suitable for you. Some time in January is fine too.

We have discussed this in our data management group in the Nansen Legacy project. Some of the staff from several of the Norwegian data centres would also be interested in joining, as would Tove Gabrielsen, who is a biologist who co-leads the data management group and provides a researcher's perspective on things (amongst other things!). We could find more people to join based on what we thing would be useful for the workshop.

As I am the only one based on Svalbard, I think the mainland (probably Oslo) would be the most sensible location if we want it to be a physical workshop, and we could find somewhere suitable to host this. 

I am looking forward to hearing your ideas on what we could discuss and achieve together.

**Comment by dagendresen** [comment]
I recall we have had some productive OBIS data workshops in Brussels. I think that meeting in person will be more effective than virtual, however virtual is also possible. If traveling to Oslo is an alternative, the museum at Tøyen can of course host a workshop.

For an online video chat in the time before New Year, for example, Friday 10/12 and 17/12 are free the full days in my calendar.

**Comment by albenson-usgs** [comment]
I'm available to chat but I'm based in the US so I'm not sure it makes the most sense for me to be involved in the conception of this workshop? I think it might be better to get someone from EurOBIS involved like Joana Beja or Rubin Perez. I don't know their github handles or I would have added them. Sorry!

**Comment by lhmarsden** [comment]
Thanks @albenson-usgs yes I think the US is a bit too far for this kind of thing! Perhaps @pieterprovoost?

**Comment by lhmarsden** [comment]
@pieterprovoost are you available for a meeting next Friday (17th)?

**Comment by pieterprovoost** [comment]
@lhmarsden Yes, works for me! Maybe we should take this conversation to email?

**Comment by dagendresen** [comment]
Draft agenda (for Zoom call 2021-12-17):
   *   Contents of workshop
   *   Target attendees
   *   Date and location of workshop

**Comment by rukayaj** [comment]
Thanks @lhmarsden, I've also forwarded the meeting invitation to Andreas Altenburger @ UiT who is heavily involved in publishing marine data with us as well.

**Comment by dagendresen** [comment]
Planning of workshop is moved to issue https://github.com/gbif-norway/helpdesk/issues/73

**Comment by dagendresen** [comment]
Darwin Core use case developed by the Darwin Core maintenance group at https://docs.google.com/document/d/1rpxveUfN9MCdo38mJR0LaWerMo5Je0oL6p1Yym5gxH4/edit#heading=h.s91o7eupvwg7

**Comment by rukayaj** [comment]
I think discussion of the future data model is happening in the google doc Dag linked to, and we are planning a workshop (#73) where we will try to publish with the current data model. So I am going to close this issue, but if anyone would like it to stay open please go ahead and reopen.
