### ISSUE TITLE
Coordinates from Rana Museum

### ISSUE THREAD

**Issue by vidarbakken** [gbif-norway/helpdesk#70]
I got an excel spreadsheet with some strange coordinates. This is an example:

UTM     KARTREF
VP5852 | 33WVP55
VP5548 | 33WVP54

I have asked him for a comment to this.

**Comment by vidarbakken** [comment]
I got a reply from Rana Museum. Earlier they had Access as a database, but started to use excel instead! They have a long way to go to get a good management system for their collections!
I will guess that the coordinate given in the example is 33W VP 5852. This is not an UTM-reference, but a MGRS-coordinate. The accuracy is 1 km.

**Comment by rukayaj** [comment]
Did you manage to fix their coordinates, @vidarbakken ?

**Comment by vidarbakken** [comment]
I haven't heard anything from them since I sent the last message. I susepect the answer is what I wrote in the previous message. We can close this issue for the moment.

**Comment by dagendresen** [comment]
[MGRS](https://legallandconverter.com/p50.html) [tuple](https://www.earthpoint.us/convert.aspx) 33W VP 58 52 =
Decimal Latitude 66.28508
Decimal Longitude 14.06413
[Which is located in Rana, Norland](https://www.google.com/maps/place/66%C2%B017'06.3%22N+14%C2%B003'50.9%22E/@66.285075,14.06413,10z/data=!4m5!3m4!1s0x0:0xe998ef76c7822bd5!8m2!3d66.285075!4d14.06413)

**Comment by dagendresen** [comment]
[MGRS is a rather common georeference format among Norwegian botanists ;-)](http://botanikk.no/Kart.htm)

**Comment by MichalTorma** [comment]
My guess is that in their notation `VP5852 | 33WVP55` they use the second part (`33WVP55`) for some sort of crude clustering since it only contains coordinates in very low precision of 10km [[1]](https://en.wikipedia.org/wiki/Military_Grid_Reference_System). The first part has a slightly higher precision of 1km (but lacks the UTM grid definition) so when you combine them, you get `33W VP 58 52`. To test if it's true, I've converted the high precision coordinates to WGS86 and converted them back to MGRS at lower precision and as you can see, we got `33WVP55` back
```python
import mgrs
```


```python
mgrs_object = mgrs.MGRS()
```


```python
coors = mgrs_object.toLatLon('33WVP5852')
print(coors)
```

    (66.28507533173716, 14.064129665195587)



```python
low_prcision_mgrs = mgrs_object.toMGRS(coors[0],coors[1], MGRSPrecision=1)
print(low_prcision_mgrs)
```

    33WVP55

**Comment by dagendresen** [comment]
@vidarbakken maybe share the spreadsheet with Michal (if you, Michal can help with batch conversion of the MGRS coordinates?)? If we help them to convert the coordinates - is the collection in other aspects ok to publish? Maybe useful to add their data to the GBIF UAT test portal??? The contact point is Vetle Løveng <velo@helmus.no> -- right?

**Comment by vidarbakken** [comment]
I have found a system for MGRS batch coversion: http://legallandconverter.com/mgrsbatch.html
Before we do anything more I must have a dialogue with Vetle about how to proceede. So far we have only got some examples of data they have. He has just started in the position at the museum.
