### ISSUE TITLE
20 - 22 September: Nansen Legacy - Marine data publishing workshop

### ISSUE THREAD

**Issue by rukayaj** [gbif-norway/helpdesk#73]
### Contents of workshop
Luke asked for this workshop in order to discuss how to publish a wide range of biodiversity data.

### Target attendees
Luke has discussed this in the data management group in the Nansen Legacy project: Some of the staff from several of the Norwegian data centres would also be interested in joining, as would Tove Gabrielsen, who is a biologist who co-leads the data management group and provides a researcher's perspective on things (amongst other things!). We could find more people to join based on what we thing would be useful for the workshop.

### Date and location of workshop
?

**Comment by dagendresen** [comment]
Data flow http://www.eurobis.org/gbif http://www.eurobis.org/data_flow
Overview of (all?) OBIS datasets https://www.gbif.org/network/2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6

**Comment by vidarbakken** [comment]
Agenda:
Contents of workshop
It seems that the focus must be marine data. However, UNIS is also working in the terrestrial environment, but the Nansen project deals only with marine climate and ecosystem. It must be important to discuss data entry and data flow from the project to GBIF/OBIS. Important to make the process as easy as possible for the data contributors which are the researchers or technicians. Is it important that the project reports to GBIF and not OBIS?

Target attendees
It is tempting to invite more research groups working mainly with the marine environment. Some obvious candidates are HI, University of Tromsø, Akvaplan-Niva and Polarinstituttet. There are also other potential candidates. Also a possibility that people can attend online, in combination with a physical meeting. Will slso depend on the corona situation in that period.

Date and location of workshop
I think the best places would be Bergen or Tromsø, It would be good if the meeting could be held by HI to involve them in the project. Longyearbyen is also a possible location (UNIS). Sometime in the first part of next year.

**Comment by rukayaj** [comment]
We could also think about inviting our marine data publishers from the private sector I suppose? I'm thinking of DNV in particular...

**Comment by dagendresen** [comment]
See also 
 * [OBIS session at the GBiF Nodes meeting 2021-07-01](https://gnm2021.gbif.org/sessions/thursday-marine-data-mobilization-session)
 * [Other OBIS events in the GBIF events calendar](https://www.gbif.org/resource/search?offset=0&q=obis&contentType=event&_showPastEvents=true)

**Comment by rukayaj** [comment]
Possible topics:

What data do you have which doesn't fit in with the DwC data model? 
How to structure your data so it fits DwC
Hands on "bring your own data" session
Hands on session on data workflows for each participant (maybe possible to get groupings here?)
Top down - overview of the data models
Bottom down - look at your own data and see how to fit it back up into the models

Logistics: 

There is a NL cruise going out Feb next year. Note - people haven't been really sharing their data even internally up till now.
Multi day workshop? In person ideally, with digital participation optional.
Ideally involve marine institute + polar institute ? 
Tromsø is a good option? Andreas says museum can host maybe 30 people. 

Funding - GBIF Norway can fund the venue + Nansen legacy project  can help with funding too. Participants to pay for their own travel + hotel. Possibly we pay for PhD students flights + accom etc, as needed?

Dates - April 26 - 28?  Maybe first week of May?

Participants - Perhaps this should be a "Nansen Legacy" workshop? I.e. only Nansen Legacy researchers + e.g. OBIS staff + GBIF staff who can help run the workshop, then funding is strictly through the Nansen Legacy Project.

**Comment by rukayaj** [comment]
### Meeting minutes from Luke: 

Output of discussion

A workshop will be held to teach researchers how to create Darwin Core Archives and publish their data. Researchers will bring their own data along and learn how to create a Darwin Core Archive from them (and publish it?). This will also help GBIF/OBIS identify data structures that currently are not easy to fit into a Darwin Core Archive, and therefore where further development of the standard is required.

The Nansen Legacy data policy is that data must be published to a data centre that contributes to SIOS (Data submission | sios-svalbard.org), but could also be published to GBIF/OBIS using the same DOI.

Date: Week commencing Monday 25th April, or the first week of May. Not starting on Monday to allow for travel.

Duration: 2/3 days

Location: Tromso. Luke will contact the Nansen Legacy team about the logistics of this. The University of Tromso, the Norwegian Polar Institute or the Institute of Marine Research were suggested as potential hosts. Digital participation could also be an option.

Funding: Luke will see what Nansen Legacy can contribute. GBIF may also be able to contribute.

Target audience: Nansen Legacy biologists with data

Run by: Luke Marsden, GBIF and OBIS?

AoB:
Luke will have a separate discussion with GBIF and OBIS staff on the data workflow.

**Comment by rukayaj** [comment]
Note from Andreas: I quickly checked. The Arctic University Museum of Norway has currently capacity for 42 workshop attendees including instructors. The technical equipment for digital participation is currently not in place. So the museum is a suboptimal venue for the workshop.

**Comment by lhmarsden** [comment]
Nansen Legacy workshops have to be approved by the project leader team. They are meeting next on 21st January. 

NPI have suggested that they may be able to host.

What sort of technical equipment should a suitable host have? A computer classroom?

**Comment by dagendresen** [comment]
I think that an online personal laptop is sufficient -- for a demo and sandbox-testing of GBIF components. The GBIF data publishing software is server-side. And with no need for installing desktop software.

**Comment by rukayaj** [comment]
If we are planning to have a digital option then some kind of streaming set up would be good...

**Comment by lhmarsden** [comment]
Good news, the project leadership team have discussed this and decided Nansen Legacy can fund the whole workshop.

The Polar Institute in Tromsø will be able to host.

The bad news, they have questioned whether a 3 day workshop is too long. Could someone please outline what we could achieve in 1 day Vs 2 days Vs 3 days? 

I will push for 3 days if necessary.

**Comment by lhmarsden** [comment]
We will get 3 days if we need it, they just want to make sure it is necessary. I think it will take them a lot longer to do it by themselves!

**Comment by dagendresen** [comment]
Day 1 - project meeting to agree on data flow methods
Day 2 (& day 3 ?) - hands-on workshop to
 * prepare Nansen Legacy datasets for GBIF publication
 * mapping to Darwin Core & synchronize with the GBIF IPT

**Comment by lhmarsden** [comment]
Thanks for the quick reply Dag. 

Agree that they won't get into working with their own data until at least start of Day 2. The workshop will have to be very introductory. Maybe even including quick dummy examples that they can try quickly converting themselves. 

The question is then whether publishing their data will take an additional 1 or 2 days. They will often come unorganised in several Excel sheets. In some cases the data will need to be divided into multiple DwCAs. In your experience, can you teach beginners to do this in 1 day following the introductory day? The goal should be that their data are published when they leave.

Since it will be a Nansen Legacy dat workshop, there will need to be some specifics. They should have all used the templates to log their metadata. Some people disregarded these templates when they have incorporated their data, which is a shame because they should have made publishing easier. Data will also need to be published first with a data centre that contributes to SIOS, then published to GBIF with the same DOI.

Of course they may have to complete the workflow afterwards but they should be 90% there and be able to complete the rest with minimal supervision. Thats the dream anyway.

**Comment by dagendresen** [comment]
I believe that we can bring some of the datasets very close to be ready to be published in a one-day hands-on workshop -- and some more datasets ready for publication in two days. I believe that researchers with their own data will learn very much from questions other participants will have about how to map their data.

We also have more programmed curriculum - but maybe too much?

Here is a similar data publication workshop at Fram-huset in Tromsø in 2016:
https://www.gbif.no/events/2016/gbif-data-publishing-tromso.html

See also some of the other data publication workshops in 2016 here:
https://www.gbif.no/events/2016/

**Comment by lhmarsden** [comment]
Do you mean on top of the introductory day 1?

I have looked at the previous workshops. I like the idea of day 2 (and possibly 3) being quite unstructured with instructors being there just to answer individual questions. I think this will be effective.

The introductory day 1 sounds good. We can finalise the content but something like that would be good.

Would it be an option for people to sign up to 2 or 3 days depending on how much time they want to spend or feel that they will need? Or is this a bad idea?

**Comment by dagendresen** [comment]
Yes, I was also thinking of planning for more participants on day 1 - to get an introduction. And to offer a day 2 (and 3?) for people who want to start publishing their own datasets - or wants to take part in watching colleagues publishing their datasets...

**Comment by vidarbakken** [comment]
Do you know how many participants with data you expect from the Nansen Legacy project?

**Comment by lhmarsden** [comment]
There are a lot who have data. Whether they will attend is another question.

We have budgeted for 30.

**Comment by lhmarsden** [comment]
It may also be relevent for me to mention that many people have measurements or facts that they should publish. In my experience, it can take a lot of time to reformat these into the desired format if there are lots of columns that need converting. But maybe I am slow and you have ideas on how to speed this up! :)

**Comment by vidarbakken** [comment]
If Dag, Ruakya, Michel and me participate, we are four teachers to help the partcipants to format their data. Including you we are five.  I have some ideas how Measurement or Facts and dynamic properties data can be converted in excel.

**Comment by rukayaj** [comment]
There's also openrefine (http://openrefine.gbif.no/) which I **think** can do that as well.

**Comment by lhmarsden** [comment]
Thanks for the comments all. I will suggest that we go ahead with a 3 day workshop, but leave participants with the freedom to sign up to which days they want to.

**Comment by pieterprovoost** [comment]
Yes, two extra days after the introductory session sounds good. For some datasets processing will take less than a day, but we'll need a bit more time if we want to discuss issues that come up during the hands on work with the entire group.

We have a number of courses on data publishing at https://classroom.oceanteacher.org/. There's too much there to cover it in a single day, but we can borrow a few topics like taxon matching (if necessary) and using vocabularies with MeasurementOrFact.

We should also decide if we want to have a single opinionated workflow, or if we want to offer several options (Excel only, OpenRefine, R, etc).

**Comment by rukayaj** [comment]
I guess it would depend on the audience, if they have differing levels of technical skills it might be useful to offer several options?

**Comment by lhmarsden** [comment]
I think we can expect a mixed bag in terms of technical expertise. Most people I work with at UNIS have never published a DwCA before. Some have been working with templates using Darwin Core terms however, so some will be able to do this quickly. As long as we clearly communicate who would benefit from 2 vs 3 days, I think we are good.

I think many people should be using scientific names for their taxon, but probably not author and year. Of course reusing topics is a good idea. I think using controlled vocabularies with MeasurementOrFact will be important and will take some time.

**Comment by lhmarsden** [comment]
Would any of these dates work for you?

31st May - 2nd June
7th June - 9th June

Sorry that these are later than we previously discussed. Tove (who co-leads the data management part of the project and is a Biologist) is available on these dates but not the earlier ones. It would be good if she could attend given her position in the project. Also it would give people more notice.

**Comment by vidarbakken** [comment]
I'm eventually available in those periods.

**Comment by lhmarsden** [comment]
I will think about a possible agenda for this meeting early next week. Sorry for the delay, it has been busy.

**Comment by lhmarsden** [comment]
Hi all, provisional agenda here. What do you think? I am awaiting news about the venue, then we can confirm the dates.
https://docs.google.com/document/d/1ybv7gheu1inX3wVT-TwFLcIBXp2asP3tNWvFLco_iww/edit?usp=sharing

Please amend what you feel needs to be amended.

**Comment by rukayaj** [comment]
Looks great to me, Luke!

**Comment by lhmarsden** [comment]
A new large seminar room at the University of Tromsø has been booked for the seminar, 31st May to 2nd June. Save the date!

There is a maximum capacity of 40.

If you are happy with the Agenda, I will neaten it up and circulate it.

**Comment by lhmarsden** [comment]
Unfortauntely, fewer people than I had hoped have signed up for this workshop. This could be in part because some other things are happening at the same time.

I am considering rearranging this to September. What are you availabilities for the weeks commencing Monday 12th September or week commencing 19th September?

Cheers

**Comment by lhmarsden** [comment]
Rearranging this would be coupled with a message from the project leadership team that more people need to be attending this workshop, so this will hopefully boost the numbers.

**Comment by dagendresen** [comment]
Many thanks for your efforts, Luke! I might be in Iceland for another project meeting - however, the current Doodle poll for this other meeting seems to favor late August above September - and if needs be I could prioritize the Nansen Legacy workshop!

**Comment by vidarbakken** [comment]
I can probably attend the workshop in September.

**Comment by lhmarsden** [comment]
I am reluctant to run it in August as I want to avoid the holiday season.

**Comment by dagendresen** [comment]
> I kind of remember something for BioDATA Advanced was planned for Sept, either ZA workshop or Barnaul... But I don't think any dates were finalised?

Yes, there was both a BioDATA Advanced course in Barnaul and an open biodiversity science conference in Novosibirsk planned in September 2022 -- but now of course postponed because of the Russian attack on Ukraine.

**Comment by dagendresen** [comment]
Very good YouTube presentation of the NansenLegacy data management
https://youtu.be/SbGiC5z554k

**Comment by lhmarsden** [comment]
Thanks @dagendresen

**Comment by ymgan** [comment]
Thanks @dagendresen!! I will have a look on Tuesday when I am back to work :) 

@lhmarsden - do you think it's feasible to schedule some time in for the workshop to look at the new gbif data model together? Maybe after the first 2 days when we have seen how the other datasets look like?

**Comment by lhmarsden** [comment]
That should be fine @ymgan

**Comment by ymgan** [comment]
Awesome!! thank you so much for organising @lhmarsden ! Appreciate it!!

**Comment by rukayaj** [comment]
https://www.eventbrite.com/e/bring-and-publish-your-data-workshop-darwin-core-archive-tickets-267411684547?internal_ref=social

**Comment by ymgan** [comment]
Hello, may I know how the is the logistics organized? Do we book the hotel independently or is group reservation available? Do you have hotels recommendation? I read that Nansen Legacy would cover the costs. Do we book first and request reimbursement later? Can you please let me know? 

I need to do some paperwork from my end for every work related travel and it could take long. I will be really grateful if you could provide some of the information mentioned above. Thank you so much for organizing!

**Comment by lhmarsden** [comment]
Hi @ymgan, sorry for the slow reply. I have been on holiday. I will find out about this as soon as possible.

**Comment by lhmarsden** [comment]
Update on this, the member of our admin team who controls these things is on holiday until 1st August. I will chase this up when they return to work.

**Comment by lhmarsden** [comment]
Lena from our Admin team was very quick in replying first thing this morning!

_"Of course the project can cover the expenses of the “teachers”. It might be wise to check with Mona if we should book flights and hotel rooms for these 3-4 people, as the new reimbursement system at UiT is extremely slow in refunding external (outside Nansen Legacy) people. Mona is back next week Monday. I suggest we wait with this decision until then."_

So I will give a good answer next week I hope, but I guess it might be best if we book for you.

**Comment by lhmarsden** [comment]
It would be good to have a short meeting to discuss who will be attending, some logistics, and perhaps what needs to be done or prepared prior to the workshop. Is anyone available the week commencing 8th August? 

Please fill in the poll below:
https://doodle.com/meeting/participate/id/avgVAngb

**Comment by lhmarsden** [comment]
Let's go ahead with Wednesday 10th at 10am on 2pm.

Could someone else please send out a zoom invite? I don't have zoom premium and try to avoid using Teams...

**Comment by dagendresen** [comment]
I made a calendar invitation with a UiO Zoom link. For 10/8 at 10:00. Feel free to share further if others want to join.

**Comment by lhmarsden** [comment]
I have put together a provisional agenda for the meeting on Wednesday. If there is anything else you wish to discuss, feel free to add it.
https://docs.google.com/document/d/1WfYtpzO8iXt0DrZVld8K9lA1h26IXqvxZhYFtCWbc48/edit?usp=sharing

**Comment by lhmarsden** [comment]
Hi, I have spoken to the Nansen Legacy admin team about funding. We will be able to book hotels and flights for you. Will you need other expenses covered, or will GBIF cover these? E.g. buses, taxis, food.

**Comment by dagendresen** [comment]
> Will you need other expenses covered, or will GBIF cover these? E.g. buses, taxis, food.

It is perfectly fine for the GBIF project to cover our other expenses! And sincerely many thanks for covering hotels and flights!!

**Comment by lhmarsden** [comment]
Great, I guess this will be the simplest way.

**Comment by lhmarsden** [comment]
Happy with these flights? 
![image](https://user-images.githubusercontent.com/60346517/184837792-afc6df31-70ca-436e-ada8-4ec2afe5092c.png)

**Comment by dagendresen** [comment]
Dag: Flights are all fine! 
@rukayaj @vidarbakken @MichalTorma ?

**Comment by vidarbakken** [comment]
Hi, I would like to go home on Friday night if possible.

**Comment by lhmarsden** [comment]
Hi @vidarbakken please communicate this in the email, I copied you in, so Mona can be up to date.

**Comment by lhmarsden** [comment]
> Hi, I would like to go home on Friday night if possible.

In principle this shouldn't be an issue, but you will probably have to pay for the extra night in the hotel yourself or if GBIF will fund this. In Nansen Legacy, usually only participants who can't fly home are granted an extra night at a hotel - which is usually us on Svalbard.

**Comment by lhmarsden** [comment]
Scandic Grand is full for those dates apparently. Mona will pick something else suitable.

**Comment by lhmarsden** [comment]
Some of the questions in the survey I just circulated might not be relevant to you. Just provide any answer and I will pay attention only to the relevant questions.

**Comment by vidarbakken** [comment]
I will not need a hotel the last night.

**Comment by lhmarsden** [comment]
> I will not need a hotel the last night.

Okay @vidarbakken please communicate this and your preferred return flight with Mona via email.

**Comment by rukayaj** [comment]
@lhmarsden we were just wondering, has anybody uploaded their data for the workshop yet?

**Comment by dagendresen** [comment]
Draft Agenda as Google Doc https://docs.google.com/document/d/1ybv7gheu1inX3wVT-TwFLcIBXp2asP3tNWvFLco_iww/

**Comment by lhmarsden** [comment]
You can view the data shared here: https://drive.google.com/drive/folders/1DZQo-0l6Cv57wmzsDmKW4Rg2v4yNCYyh

Unfortunately, there is only one dataset shared so far, and we already discussed this one via email.

Additionally, there is a large dataset that 4-5 people will be working with together. These data already look quite a lot like an occurrrence extension, but some columns will be need to be mapped to measurementsorfacts and the event core will need to be created. I however have created a draft of the event core for them. Whilst this is a large dataset, I don't think it will be complicated to convert to DwCA.

I will chase up everyone else since I haven't received many survey responses.

**Comment by lhmarsden** [comment]
I have tried to compile some information from participants concerning the workshop. See linked below:

https://docs.google.com/spreadsheets/d/1b4pRNs1TTp5NW8b7lNVWRVzeQWX9J2Nb/edit?usp=sharing&ouid=109954185656296467293&rtpof=true&sd=true

I have not received any more datasets and don't expect to.

**Some stats**

- Attendees: 18 researchers, 3 data managers, 6 teachers,  7 awaiting reply
- 6 people will work together on a large dataset
- Most people will work individually on their own data
- 2 people have stated that they will work in dummy data that we (you?) will provide
- 3 people will attend remotely (included in above numbers)
- Most people will attend all 3 days. 1 person cannot attend on Thursday.

**Comment by vidarbakken** [comment]
Luke,

I have tried the new tool "Nansen Legacy Darwin Core Event Core and Extensions Generator". It looks good and will make it easier for researchers to convert their data. I have some questions.

Why do you use eventID and parentEventID in the input file when they (correctly) have the names occurrenceID and eventID in the DwC file? Why can't you use the same names in the input file? I also tried to rename the terms in the input file, but then the DwC file was not possible to open.

Do you expect that some researchers will have this format for their data at the workshop?

**Comment by lhmarsden** [comment]
Hi @vidarbakken  thanks for checking this out and providing me with feedback.

The tool pulls data from the metadata catalogue (stored as a CSV file). This table only has an eventID column, not an occurrenceID column. So it reads this column and only this column and pulls relevant metadata from the CSV for the matched record.

The metadata catalogue is a compilation of log sheets created during each cruise. In this case, the user has created an occurrenceID on their own after the cruise.

I hope a lot of the data will be in this format. However, some people have discarded the eventIDs from their data flow and worked on other sheets.

**Comment by lhmarsden** [comment]
> The [SIOS metadata catalogue](https://sios-svalbard.org/metsis/search?f%5B0%5D=collection%3ASIOS&f%5B1%5D=dataset_level%3ALevel-1&f%5B2%5D=project%3ASIOS) is this one? Are there spreadsheet files here in addition to the netCDF files?

No, that is the data access portal/data catalogue.

The Nansen Legacy metadata catalogue is hosted here: https://sios-svalbard.org/aen/tools

**Comment by vidarbakken** [comment]
> Hi @vidarbakken thanks for checking this out and providing me with feedback.
> 
> The tool pulls data from the metadata catalogue (stored as a CSV file). This table only has an eventID column, not an occurrenceID column. So it reads this column and only this column and pulls relevant metadata from the CSV for the matched record.
> 
> The metadata catalogue is a compilation of log sheets created during each cruise. In this case, the user has created an occurrenceID on their own after the cruise.
> 
> I hope a lot of the data will be in this format. However, some people have discarded the eventIDs from their data flow and worked on other sheets.

Is the metadata cataloque (csv) available as a file?

**Comment by lhmarsden** [comment]
I have a copy on my PC, though it is >100Gb. Do you want me to send you it?

**Comment by vidarbakken** [comment]
> I have a copy on my PC, though it is >100Gb. Do you want me to send you it?

Ok, it is so big. Is it possible to see an example of how it is formatted?

**Comment by dagendresen** [comment]
I wonder if the eventID in the metadata catalog is mapping correctly to the occurrenceID concept? A dwc:Event is the intersection of a location and a time, while a dwc:Occurrence is the intersection of a dwc:Event and a dwc:Organism. Will all occurrenceIDs actually identify some organismal presence at a time and location? Will all measurements linked to the occurrenceIDs always be measurements of the Organism present (or in other words, maybe some measurements linked to an occurrenceID might be measurements of the environment?). Maybe all fine - just checking.

**Comment by lhmarsden** [comment]
> I wonder if the eventID in the metadata catalog is mapping correctly to the occurrenceID concept? A dwc:Event is the intersection of a location and a time, while a dwc:Occurrence is the intersection of a dwc:Event and a dwc:Organism. Will all occurrenceIDs actually identify some organismal presence at a time and location? Will all measurements linked to the occurrenceIDs always be measurements of the Organism present (or in other words, maybe some measurements linked to an occurrenceID might be measurements of the environment?). Maybe all fine - just checking.

You are right, it won't map correctly in all cases. The user has to provide only ids that are representative of occurrences. It is not possible to implement a 'one size fits all' solution in this case, but this should help in a lot of cases.

**Comment by lhmarsden** [comment]
> Ok, it is so big. Is it possible to see an example of how it is formatted?

There is a pipe delimited CSV file here for 1 day of 1 cruise:
https://drive.google.com/file/d/1dzWZG1HSQucLLlMfcW9Uzne8Gnz2PvVz/view?usp=sharing

**Comment by lhmarsden** [comment]
Hi all, I have been trying to get in contact with @pieterprovoost to ask whether he or someone from OBIS can give a 30 minute presentation (remotely) introducing OBIS as part of the the workshop. Next Tuesday, 3pm.

Unfortunately, I haven't been able to get in touch with him. Does anyone know anyone else from OBIS who might be able to give a presentation at short notice?

**Comment by dagendresen** [comment]
Did [Yi-Ming Gan](https://orcid.org/0000-0001-7087-2646) of [AntaBif](https://www.biodiversity.aq/about/contacts/) [SCAR](https://www.gbif.org/participant/306) register for the workshop? I noticed she asked for a side-discussion on your GBIF data model use case. AntaBIF and SCAR are sort of [linked to OBIS](https://www.iode.org/index.php?option=com_oe&task=viewGroupRecord&groupID=388).

We could also ask [Abby Benson](https://orcid.org/0000-0002-4391-107X) to present OBIS...? I believe she is the GBIF Node Manager for [OBIS](https://www.gbif.org/network/2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6) or at least for [OBIS USA](https://www.usgs.gov/ocean-biodiversity-information-system-usa).

**Comment by lhmarsden** [comment]
Yes, @ymgan will be joining us :)

**Comment by ymgan** [comment]
Hi, I am the node staff for the Antarctic node of GBIF and OBIS. If the presentation is about OBIS data structure, I can do it but I can't "represent OBIS" in decision making etc.

**Comment by pieterprovoost** [comment]
@ymgan If you could cover this that would be great, I will not be available at the time of the workshop.

**Comment by ymgan** [comment]
Okie! I will do it! Please let me know what should I cover :D

**Comment by ymgan** [comment]
Got it! You're most welcome Luke, Pieter! 

Will also briefly introduce OBIS approach to rich datasets with Event core, extended MeasurementOrFact, and BODC vocabs. Will copy @lhmarsden when I send in my slides to @pieterprovoost latest by Friday AM so that you can provide feedback before the presentation :)

**Comment by rukayaj** [comment]
Abbey at tdwg just presented an obis data mobilisation workshop which was 100% virtual 

https://ioos.github.io/bio_mobilization_workshop/

Some interesting techniques as they had many participants: several "themed" breakout rooms (eg 1 for help formatting dates, some one on one breakouts, a quiet room they can go to but still be connected on zoom ).

**Comment by rukayaj** [comment]
Anyway I guess we can close this now :)

**Comment by rukayaj** [comment]
Interesting - this workshop was unfunded and they won't run another again unless they get funding as it was a lot of people's free time

**Comment by lhmarsden** [comment]
I'd be interested to know from Abby how successful that was. I received good feedback from a few people who attended our workshop online.

Themed break-out rooms sounds like a really good way to structure this.

**Comment by rukayaj** [comment]
Her talk generally was really interesting, I'll post it here when we get the recording later. She was a big fan of these practical hands on kind of workshops, and she said they didn't publish any datasets during the workshop but they are getting them coming in now, a bit like we are too.

**Comment by rukayaj** [comment]
I see that perhaps it's supposed to be private for conference attendees, so I will email it to you @lhmarsden rather than posting on github.

**Comment by dagendresen** [comment]
I believe the TDWG 2022 talks will eventually become openly available on the [TDWG YouTube channel](https://www.youtube.com/channel/UC3k926cEitgTHn0ib9FvJHA) ... when the TDWG secretariat finds time to process and upload them to YouTube. Meanwhile, they have shared the direct Zoom link with the conference attendees :-)
