### ISSUE TITLE
Excel spreadsheet for DwC datasets

### ISSUE THREAD

**Issue by vidarbakken** [gbif-norway/helpdesk#77]
A macro based spreadsheet in excel is made for DwC datasets. It is possible to define datasets for Occurrence and Sample-Event. It is also possible to connect MeasuremensOrFacts (including Extended  MeasuremensorFacts) and SimpleMedia data. When completed the datasets can be exported to tab-text files. It is also possible to make templates of the setup of the different sheets. The templates can later be imported and used in the spreadsheet.

**Comment by vidarbakken** [comment]
I have made a simple user manual for the excel spreadsheet. To be improved!
https://www.dropbox.com/s/0wovc96w3qmswl4/GBIF_DwC_Data.pdf?dl=0

**Comment by rukayaj** [comment]
@vidarbakken I think it would be great if you could make a github repository and add the spreadsheet to that so we have access to the latest version of it as well!

**Comment by vidarbakken** [comment]
Last version from today:
https://www.dropbox.com/s/l3wnz25yrt15j5x/GBIF_DwC_Data_Tool_1_1_Beta_Dist%20.xlsb?dl=0

**Comment by rukayaj** [comment]
> It is not allowed to attach such files (*.xlsb) in GitHub.

Oh yes I forgot about that! Ok I guess dropbox is best for it while it is still getting tested. When you feel like it's ready we can link to it from the [simple excel generator](https://gbif-norway.github.io/dwc-excel-template-generator-js/) and/or the [GBIF.no services](https://www.gbif.no/services/) page.

**Comment by rukayaj** [comment]
I have uploaded this version https://www.dropbox.com/s/l3wnz25yrt15j5x/GBIF_DwC_Data_Tool_1_1_Beta_Dist%20.xlsb?dl=0 to here https://static.gbif.no/dwc-generator.xlsb. 

Also added it to the GBIF.no services page. So I guess we can close this issue?

**Comment by dagendresen** [comment]
If the Excel tool maybe is published in e.g. Zenodo or OSF - together with a user manual? - it could get a DOI to enable easier citation if useful. An abstract presented at TDWG could also provide a nice software citation anchor :-)
Anyway, the static.gbif.no also looks nice.

**Comment by rukayaj** [comment]
Great idea, it would be perfect to have it in Zenodo - and then Vidar can more easily manage the versions too. What do you think @vidarbakken ?

**Comment by rukayaj** [comment]
All done!

**Comment by vidarbakken** [comment]
A second version is published in Zenodo (1.2 beta). Today I have updated the spreadsheet with dynamicProperties which is saved in json format. The date registration is also extended to cover date periods. These two last updates are not yet published. They need some more testing before publishing.

**Comment by dagendresen** [comment]
In Zenodo at: https://doi.org/10.5281/zenodo.5886995
