### ISSUE TITLE
DLN FAIR data award 2021 / Ebbe Nielsen challenge 2022 - Deadline 14 August 2022

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#79]
Do we want to nominate one of the Norwegian GBIF data publishers to the 

## Ebbe Nielsen challenge 2022
https://www.gbif.org/article/1G82GL7jw08kS0g6k6MuSa/ebbe-nielsen-challenge

## Young Researcher Award 2022
https://www.gbif.org/news/6PzaBymtwAEvbpXYtb4d1y/call-for-nominations-to-the-2022-gbif-young-researchers-award

## DLN FAIR data award 2021
https://www.digitallifenorway.org/services/funding/Call_for_FAIR_data_award_nominees.html

Maybe some of the datasets are more "FAIR" than others :-)

Do we want to nominate the LivingNorwayR team (Matthew Grainger, Joseph Chipperfield, and Erlend Nilsen)?
https://github.com/LivingNorway/LivingNorwayR

ArtsOraklet by Wouter Koch could also be a good candidate?
https://orakel.artsdatabanken.no/
https://www.artsdatabanken.no/Pages/310901/Artsorakelet_i_2021-versjon

**Comment by rukayaj** [comment]
The deadline for this passed :)
