### ISSUE TITLE
Full dataset from Stephen Barstow

### ISSUE THREAD

**Issue by rukayaj** [gbif-norway/helpdesk#8]
> Now I’ve completed the big job of removing all the private pictures and references that identify people  with their full name.
> Note that each bed is still demarked by a line beginning like 6. POND BED NORTH (PBN) in the first column.
> Note also that under #28 are pictures of some other organisms like birds, butterflies and moths, molluscs and other insects.
> The format is the same and Bed 5 which I previously sent is not included.

This new dataset needs to get published, and the images should also get moved and resized.

**Comment by dagendresen** [comment]
We might need to consider a strategy to make sure we have the capacity to ensure the image URLs are persistent -- if stored at the gbif.no server (URL)? Maybe consider PURL -- or an upgrade to HANDLE (including for our UUIDs?)

**Comment by rukayaj** [comment]
I have uploaded the new dataset, added PURLs for the images, and archived the original files in Zenodo. SB will check and make sure that no further changes are necessary.

**Comment by rukayaj** [comment]
He seems to be happy with it.
