### ISSUE TITLE
Biorehab Klepsland - data publisher

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#81]
**Biorehab Klepsland** is considering establishing a data node (publisher) in GBIF.
Currently, they publish terrestrial inventory data in ArtsObservasjoner.
(1) Might wish to **move** Occurrence data from ArtsObs dataset to the new data-node
(2) Would want to publish from Excel spreadsheet formats
(3) Wants to publish species occurrences from locations outside of Norway
(4) Might want to **combine** use of ArtsObs with own datasets on own data node
Contact point: Jon Klepsland <jonklepsland@gmail.com>

**Comment by dagendresen** [comment]
Answered by email, confirmed an offer from the GBIF node for services and support to establish their new data publisher.

**Comment by dagendresen** [comment]
New data publisher at: https://www.gbif.org/publisher/62be3b7c-4882-461a-8570-3cd8e4579a46
Registry entry at: https://registry.gbif.org/organization/62be3b7c-4882-461a-8570-3cd8e4579a46

**Comment by rukayaj** [comment]
I've made him a dataset and put it on the IPT, he's going to fill in the metadata and then we will publish.

**Comment by rukayaj** [comment]
https://www.gbif.org/dataset/128c56d8-2210-4a7d-949a-35d49558c9dd now published
