### ISSUE TITLE
CESP 2022 project with Tajikistan

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#84]
### [CESP - Capacity Enhancement Support Programme](https://www.gbif.org/programme/82219/capacity-enhancement-support-programme)

[Call for proposals for the 2022 Capacity Enhancement Support Programme](https://www.gbif.org/news/4EvtI94McmmHGaLCyTk6JB/call-for-proposals-for-the-2022-capacity-enhancement-support-programme) -- Deadline 2022-02-01

* [CESP2022-001](https://www.gbif.org/project/CESP2022-001/kick-starting-the-biodiversity-data-publication-process-for-tajikistan) (CESP project page)
* https://tajik.ipt.gbif.no/
* [Tajikistan](https://www.gbif.org/country/TJ/participation) GBIF country page

Some example mentoring projects:
* [Belarus, Latvia, Lithuania, Poland & Estonia](https://www.gbif.org/project/9BKeb7ka92YPFUjhwv4UL/capacity-building-through-regional-cooperation-for-data-mobilization-in-belarus-latvia-and-lithuania)
* [Armenia & France](https://www.gbif.org/project/CESP2021-010/mentoring-of-gbif-armenia-by-gbif-france)
* [Cameroon, Benin & France](https://www.gbif.org/project/CESP2021-002/mentoring-of-gbif-cameroon-by-gbif-benin-and-gbif-france)
* [South Sudan & Kenya](https://www.gbif.org/project/CESP2021-009/enhancing-capacity-of-gbif-south-sudan)
* [Zimbabwe & Spain](https://www.gbif.org/project/3Vktr6xaI59hVPi68fCkpO/strengthening-zimbabwes-gbif-node-through-mentoring-by-gbif-spain)

**Comment by dagendresen** [comment]
The new node in Tajikistan is working on a draft with a preliminary topic title «Risk assessment, impact of GMOs on biodiversity through needs assessment and training»

**Comment by rukayaj** [comment]
This sounds like a good idea. It says that we need to submit concept notes, I'm not sure what those are. I guess the GBIF Grants portal probably has a thing which guides you through it. Do you have a GBIF Grants portal account? 

Is the draft that the Tajikistan node is working on to do with this CESP thing - and does it involve us? Have you spoken to them already about it? I am happy to participate and attend a planning meeting but not really sure what I need to do here.

**Comment by dagendresen** [comment]
Yes, concept note is written in the GBIF grants portal - where I have been part of both writing the OpenPSD, and providing reviewing of proposals in the past. I am preparing a reply to TJ now :-)

**Comment by dagendresen** [comment]
Draft text for proposal: https://docs.google.com/document/d/1asu4J34Pul5g8KzgDgjAHaf3_IuKVH8LrEOuoMgLHWk/edit#

**Comment by rukayaj** [comment]
I have added a little to it, but it would be ideal to get a better picture of the situation in Tajikistan (the node hasn't published any data at all yet, it looks like?). So it would be nice to have a meeting to talk to Samariddin and ask exactly what they need - how much help with the actual digitisation they'd require vs the data publication (if we actually can help with that?), and so on.

**Comment by samariddinbarotov** [comment]
Hello everybody

**Comment by rukayaj** [comment]
I will reopen this again when (!!! fingers-crossed) we get approval :)

**Comment by dagendresen** [comment]
The biodiversity data publication CESP project for Tajikistan with the assigned **Project ID: CESP2022-001**, is invited to submit a full proposal for the CESP program, with the **deadline before 3 May 2022, 23:59 CET**

**Comment by rukayaj** [comment]
@samariddinbarotov would you like to have a meeting about this in the near future, or perhaps sometime in April?

**Comment by dagendresen** [comment]
Hi Rukaya, Samariddin is on holiday this week. A Zoom meeting in April is likely perfect :-)

**Comment by samariddinbarotov** [comment]
Can you send me Partner written confirmation template please!!

**Comment by samariddinbarotov** [comment]
I found it in a site GBIF!

**Comment by rukayaj** [comment]
@samariddinbarotov did you manage to find out the dimensions/measurements of your herbarium specimens?

**Comment by rukayaj** [comment]
Imaging equipment possibility: https://www.czurscan.com/

**Comment by samariddinbarotov** [comment]
Yes, dimensions/measurements of our herbarium specimens is format A3 11,7 x 16,5 inch.

**Comment by samariddinbarotov** [comment]
Imaging equipment yes it so good. there are different model. 
Super Early Bird: ET24 Pro * 1
$399 USD $798 USD (50% OFF)
Save 399 USD from the MSRP at $798, which is 50% off, limited offer. Ship worldwide!
Included Items
**CZUR ET24 Pro**
**Instructions**
Foot Pedal
Hand Button
Work Mat
Travellers' Convertors
Estimated Shipping
May 2022
Only 2 left
Ships worldwide.
What do you think?????

**Comment by rukayaj** [comment]
> Yes, dimensions/measurements of our herbarium specimens is format A3 11,7 x 16,5 inch.

Great, thanks for this! Good to know that it's not really large A2 or anything... 

I just discussed with Eirik a bit more and we think that we can actually get a better deal with a camera and camera stand set up for the same amount of money or less. I've added some info to the document.

**Comment by MichalTorma** [comment]
One think we should consider is that when scanning anything for collections, whichever solution we choose, it should be capable of producing at least 300 dpi resolution. For A3 format, theoretical minimum would be 17.4 Megapixels - of course aspect ratio and 'dead' borders make the resolution requirements higher. It is also important to consider ease of use - how many scans are we talking here? @samariddinbarotov

**Comment by dagendresen** [comment]
The draft proposal deliverables indicate GBIF publication for the approx 10 000 herbarium specimens already in the CMS BRAHMS. Not sure if the plan is to make 10 000 photos? (Yes, storage space could be significant - maybe store full-size images on an external SSD??)

**Comment by MichalTorma** [comment]
Yeah storage needed at 10k scans would be significant but manageable (~100Gi). I was more concerned about the quality and resolution of the potential camera.

**Comment by samariddinbarotov** [comment]
Hello 
My question about barcode  and QR - cod
1.  IPT Cloud has a place for uploading QR code or barcode?  
2. Generating qr- code is easy the link which you sent https://qr.gbif.no/. But, how to attach a qr- code to an object?

Our Institute herbarium has barcode  approx 10 000 herbarium specimens already in the CMS BRAHMS which just for BRAHMS which BRAHMS gave them. Is it possible to use the available barcodes of herbarium sheets in a IPT cloud? 

But as we know we have additional partniors herbariums which they dont have barcode.

**Comment by rukayaj** [comment]
Hi @samariddinbarotov ! 

1. The IPT cloud has a place for uploading the QR code or barcode numbers, yes. They will make up your materialSampleIDs and occurrenceIDs. 

2. Yes, it is possible to use the available barcodes of the herbarium sheets you have already. So each code is decoding into a series of numbers (possibly with letters?), and we would just store that code in a record.

**Comment by samariddinbarotov** [comment]
Great! We get it

**Comment by rukayaj** [comment]
Here is a diagram to help visualise it:
![cesp-project-diagram](https://user-images.githubusercontent.com/9654499/164219453-a8e9bad7-4f28-43d7-a67b-e8de489415c3.png)

**Comment by rukayaj** [comment]
I started a planning document here: https://docs.google.com/document/d/15_Q9KDX8gvlHPu4EZrg0ZFEEEnu2bcuikLXjMTVNujk/edit#

**Comment by dagendresen** [comment]
>Our Institute herbarium has barcode approx 10 000 herbarium specimens already in the CMS BRAHMS which just for BRAHMS which BRAHMS gave them. Is it possible to use the available barcodes of herbarium sheets in a IPT cloud?

From a BRAHMS user manual:
`the BARCODE field is a normal character field with default size 15 ... (e.g. IAN 0001234)`
<img width="870" alt="Screenshot 2022-06-03 at 07 16 00" src="https://user-images.githubusercontent.com/4330242/171790961-dae2eace-9ea2-4e74-b953-c8ac6933d8d7.png">

Are the Tajik BRAHMS barcode numbers also similar to this example number from the BRAHMS manual?

I would actually not recommend using something like `IAN 0001234` as either `dwc:occurrenceID` and in particular not as `dwc:materialSampleID`. This would only cause bigger problems later ;-) I would much rather recommend the mapping for such (weak and ambiguous) numbers of types looking similar to `IAN 0001234` to `dwc:catalogNumber` for specimens (MaterialSamples) and to `dwc:recordNumber` for Occurrences.

**Comment by dagendresen** [comment]
> From a BRAHMS user manual

the devil hides in the details ;-)

**Comment by rukayaj** [comment]
> > From a BRAHMS user manual
> 
> the devil hides in the details ;-)

One could also accurately say the devil lies in the user manuals :P Thanks for spotting this!

**Comment by dagendresen** [comment]
:-D 

The one-dimensional barcodes in use at the herbarium here in Oslo are also ONLY coding for the (archaic, but also nicely human-readable) catalogNumber -- I believe this is (unfortunately still) rather common. The (paradigm shifting) understanding for the need for stronger PIDs, and support for these as QR-codes and Data-matrix codes in the CMSes, are only extremely painfully agonizingly slowly crawling their way into the museum collection data management protocols :-D

**Comment by rukayaj** [comment]
I believe the final report for this has been submitted now, so I will close this issue.

**Comment by dagendresen** [comment]
@samariddinbarotov the CESP2022-001 project is still not closed in the GBIF portal ...?? But described with status "in progress". I assume we submitted a final report? And that we are maybe just waiting for the GBIF Secretariat to process this report and flag the project as completed?

https://www.gbif.org/project/CESP2022-001/kick-starting-the-biodiversity-data-publication-process-for-tajikistan

**Comment by samariddinbarotov** [comment]
Dear Dag we already submitted the final report to the CESP portal and it was approved.

**Comment by dagendresen** [comment]
Thanks - just curious because of the strange project status "in progress" from the GBIF portal. I can ask about this in the next Nodes Steering Group Meeting :-)

**Comment by samariddinbarotov** [comment]
Ok, Thank you very much!
I m in Japan now in Tottori Arid Land Center 2 weeks trip
