### ISSUE TITLE
Structured search on datasetname term so we can group and download records

### ISSUE THREAD

**Issue by rukayaj** [gbif-norway/helpdesk#88]
Katrine at UiB needs a way of downloading records from GBIF grouped by datasetName. If I do a free text search like https://www.gbif.org/occurrence/search?q=Artsprosjekt_55-12_PolyNor for "Artsprosjekt_55-12_PolyNor" then we get the correct records, but no way to download them. I checked the advanced search fields but I don't see anywhere to filter on datasetName! Is there a way anybody knows of? @vidarbakken @dagendresen

**Comment by dagendresen** [comment]
I find no datasetName in the [GBIF API documentation](https://www.gbif.org/developer/occurrence) either. But several issues reported for the ["datasetName" as search keyword](https://github.com/search?q=org%3Agbif+datasetName&type=issues) -- including the very [same question](https://github.com/gbif/portal-feedback/issues/3006) from the Field Museum.

**Comment by rukayaj** [comment]
Well the solution here seems to be to use the download endpoint in the API, which I think is ok. I mean it would be nicer if it was in the front end, but at least these searches are possible now, and provide a DOI. 

I've emailed Katrine and Thomas who was also asking about it to let them know. Closing this unless there's anything else we want to add?

**Comment by dagendresen** [comment]
I described a second different use case for multiple datasetID (pseudo projectID) on data records level here: https://github.com/gbif/pipelines/issues/665

> One important reason or rationale is to group records produced or updated from different project funding. Similar to how the GBIF BID, BIFA, and CESP projects list datasets produced by this project funding. However, often we see project funding for georeferencing, or taxonomic validation and desire to "tag" the data records (or actually ultimately rather desire to "tag" the actual real-world collection specimens) that were georeferenced from a specific project funding --> to credit the funder and track fulfillment of the promise to the funder of e.g. georeferencing 10 000 collection specimens...
