### ISSUE TITLE
Tag OpenPSD projects with CESP2019-004 in project ID

### ISSUE THREAD

**Issue by rukayaj** [gbif-norway/helpdesk#91]
We can get a list of all of them (I think?) here:

https://www.gbif.org/dataset/search?q=private-sector&publishing_country=NO

@dagendresen and I already added CESP2019-004 to one Naturrestaurering dataset already. We will check and see if it comes up in a few days in the [GBIF project search](https://www.gbif.org/dataset/search?project_id=CESP2019-004). If it all works we can go ahead and add it to the others.

**Comment by dagendresen** [comment]
[Project ID CESP2019-004](https://www.gbif.org/dataset/search?hosting_org=64795dcb-ad74-41b3-95e5-cc52ba754776&project_id=CESP2019-004) now works as expected for https://doi.org/10.15468/cuocad
But does not work when added as pipe-separated as tested for https://doi.org/10.15468/anbw32
This demonstrates that linking one dataset to multiple projects is not supported (as suspected).
[Free-text search for the project ID](https://www.gbif.org/dataset/search?q=CESP2019-004&hosting_org=64795dcb-ad74-41b3-95e5-cc52ba754776) is an alternative but clearly poor alternative.

**Comment by rukayaj** [comment]
I've tagged all the relevant datasets now, I believe. A few are pipe separated, but there isn't anything we can do about that I think.

**Comment by dagendresen** [comment]
Maybe useful to explore this list: https://docs.google.com/spreadsheets/d/1cAaTx6iht0OmXdhBl-wJ9LGRZy2uwSSirQRYE7Jo0mA/edit#gid=1832589157

**Comment by rukayaj** [comment]
Yes. Well I tagged quite a lot of datasets (everything published by the private sector companies after our openPSD workshop). I see most of them still aren't showing up in the search list https://www.gbif.org/dataset/search?hosting_org=64795dcb-ad74-41b3-95e5-cc52ba754776&project_id=CESP2019-004. Like this one for example https://ipt.gbif.no/resource?r=asplan_kalkskoger you can see was published yesterday with the projectID tag in the IPT, but is not in the search list. I don't know why, but I hope that after a while they get synced.

**Comment by dagendresen** [comment]
Seems like adding project name and project staff did make the trick --> now after reindexing is completed the project ID is displayed in the GBIF portal for the dataset in your example https://doi.org/10.15468/eykmy8
