### ISSUE TITLE
Biofokus missing data

### ISSUE THREAD

**Issue by rukayaj** [gbif-norway/helpdesk#94]
Missing data

Terje Blindheim 
Wed 2022-03-09 14:04
To:
Rukaya Sarah Johaadien;

Hello! Some of our data seems to be missing and we cant find out where the problem is. See catalog number from Biofokus below. This is exported from us, but for some reason not imported to Gbif. Can you help me?

Terje

CatalogNumber	ScientificName
709544	Silene dioica
709726	Rubus fruticosus coll.
709727	Avenella flexuosa
709728	Pteridium aquilinum
709729	Rubus idaeus
709730	Potentilla erecta
709731	Deschampsia cespitosa ssp. cespitosa
709732	Achillea millefolium
709734	Anthriscus sylvestris
709735	Nardus stricta
709736	Hypericum maculatum
709737	Agrostis capillaris
709738	Anthoxanthum odoratum
709739	Carex leporina
709740	Filipendula ulmaria
709741	Rubus idaeus
709742	Vicia cracca
709743	Carex pallescens
709744	Deschampsia cespitosa ssp. cespitosa
709746	Achillea millefolium
709747	Potentilla erecta
709748	Fraxinus excelsior
709750	Hedlundia hybrida
709751	Prunus cerasus
709753	Betula pubescens
709754	Lysimachia thyrsiflora
709755	Crepis paludosa
709756	Comarum palustre
709758	Potentilla erecta
709759	Cirsium palustre
709760	Hypericum maculatum
709761	Carex leporina
709762	Anthoxanthum odoratum
709763	Ranunculus acris ssp. acris
709765	Polygala vulgaris
709766	Molinia caerulea
709767	Myrica gale
709768	Erica tetralix
709769	Calluna vulgaris
709770	Eriophorum angustifolium
709771	Menyanthes trifoliata
709773	Carex lasiocarpa
709774	Narthecium ossifragum
709775	Carex rostrata
709776	Betula pubescens
709778	Picea abies
709779	Pinus sylvestris
709781	Veronica officinalis
709782	Dactylis glomerata
709783	Rumex acetosa var. acetosa
709784	Peucedanum palustre
709785	Equisetum fluviatile
709786	Reynoutria japonica
--

**Comment by rukayaj** [comment]
I work on this next week, or if anyone else wants they can look into it. I will forw

**Comment by rukayaj** [comment]
I work on this next week, or if anyone else wants they can look into it.

**Comment by dagendresen** [comment]
For some reason, the dataset source is mapped to the MUSIT SQL database and not to the BioFokus database (since February?). I am not sure what is the database login credentials to the BioFokus database.

**Comment by dagendresen** [comment]
Found a copy of the BioFokus database credentials we used back in June 2019 and updated the IPT configuration. Looks like it is working ...?

**Comment by dagendresen** [comment]
[2022-02-02 | 566 467 records published](https://ipt.gbif.no/resource?r=biofokus&v=1.1994)
[2022-03-10 | 570 092 records published](https://ipt.gbif.no/resource?r=biofokus&v=1.1993)

**Comment by dagendresen** [comment]
PS: Notice that basisOfRecord = HumanObservation and data records are mapped to catalogNumber ?? The values mapped as catalogNumber should be mapped as recordNumber??

**Comment by rukayaj** [comment]
> For some reason, the dataset source is mapped to the MUSIT SQL database and not to the BioFokus database (since February?). 

That is really strange. I don't remember changing this dataset in a long time, and I don't see how the database connection could have changed. Thanks for fixing!! I see you found the db credentials, but they should also be in the shared LastPass password secure notes I think. If they aren't I should add them in there.

Yes to record number, this dataset isn't a collection.

**Comment by rukayaj** [comment]
I have updated the SQL to rename catalogNumber to recordNumber, and also updated the mapping to recordNumber.

**Comment by rukayaj** [comment]
Based on emails I think this is all ok now? So closing...
