### ISSUE TITLE
Biorehab Klepsland - Norge dataset

### ISSUE THREAD

**Issue by MichalTorma** [gbif-norway/helpdesk#96]
We've been contacted by Jon Klepsland with a request for a new dataset publication. It looks similar to the one already [published](https://www.gbif.org/dataset/128c56d8-2210-4a7d-949a-35d49558c9dd) but this one contains mostly fungi. The main difference is the extra column of `Substrate` describing where the fungi were growing. According to [this](https://scan-all-bugs.org/?page_id=1327) reference - when collecting bugs, they are using the `habitat` field for this kind of information. Do you have any better ideas where to put it?

**Comment by dagendresen** [comment]
If `substrate` maybe can be described by `releve` ?? the [GBIF Releve extension](https://rs.gbif.org/extension/gbif/1.0/releve_2016-05-10.xml) enables the description of coverage in each releve.

**Comment by rukayaj** [comment]
Anything I can do to help with this?

**Comment by dagendresen** [comment]
The data publisher is asking for an estimate on when the published dataset is made public?

**Comment by MichalTorma** [comment]
Working on it - sorry I got sidetracked...

**Comment by rukayaj** [comment]
This was published (right?)

**Comment by MichalTorma** [comment]
> This was published (right?)

Yes, it's published [here](https://www.gbif.org/dataset/53f2cda4-a2fd-49f0-b3e5-0782c9770e7c)
