### ISSUE TITLE
Arven etter Nansen joint cruise 3 benthic marine dataset from Andreas @ UiT

### ISSUE THREAD

**Issue by rukayaj** [gbif-norway/helpdesk#97]
This can be our first test run of how we will advise people to do data publication during the Nansen course. He's going to send more information.

**Comment by rukayaj** [comment]
He sent a spreadsheet through. A sample:

| eventID                              | parentEventID                        | eventDate  | eventTime | eventRemarks        | samplingProtocol                          | sampleLocation | recordedBy    | occurrenceRemarks                         | decimalLatitude | decimalLongitude | minimumDepthInMeters | maximumDepthInMeters | _gearType      | scientificName        |
|--------------------------------------|--------------------------------------|------------|-----------|---------------------|-------------------------------------------|----------------|---------------|-------------------------------------------|-----------------|------------------|----------------------|----------------------|----------------|-----------------------|
| 5425873a-94dd-11ec-902e-005056a2bfc1 | 44a6b980-94a3-11ec-8036-eb0c1b9b6bfd | 2022-02-23 | 12:22     | Macrofauna taxonomy | Nansen Legacy version 10 - Campelen trawl | Uit Museum     | Birte Schuppe | Hormathia digitata on top of a Buccinidae | 76.4994         | 31.1935          | 316.47               | 316.47               | Campelen trawl | Buccinidae            |
| c199a1f6-956a-11ec-902e-005056a2bfc1 | 44a6b980-94a3-11ec-8036-eb0c1b9b6bfd | 2022-02-23 | 12:22     | Macrofauna taxonomy | Nansen Legacy version 10 - Campelen trawl | Uit Museum     | Birte Schuppe | Asteroidea                                | 76.4994         | 31.1935          | 316.47               | 316.47               | Campelen trawl | Urasterias linckii    |
| 7f0ac982-94e3-11ec-902e-005056a2bfc1 | 44a6b980-94a3-11ec-8036-eb0c1b9b6bfd | 2022-02-23 | 12:22     | Macrofauna taxonomy | Nansen Legacy version 10 - Campelen trawl | Uit Museum     | Birte Schuppe | Cephalopoda                               | 76.4994         | 31.1935          | 316.47               | 316.47               | Campelen trawl | Bathypolypus arcticus |

He also has some images which he is sorting through. I suggest we use the simple multimedia extension seeing as each event seems to be one occurrence so event core is not a problem. 

Just so I remember - on the original spreadsheet I changed: 
- sampleType (Macrofauna taxonomy for all rows) => eventRemarks
- samplingProtocol (Nansen Legacy version 10 for all rows) => concatenated samplingProtocol and gearType (result: "Nansen Legacy version 10 - Campelen trawl")
- eventRemarks => occurrenceRemarks
- family => scientificName 
- bottomDepth => minimumDepthInMeters, and I added maximumDepthInMeters

Queries:
- sampleLocation - should this be institutionCode? Is it in a collection, does it need a catalogNumber?

**Comment by aaltenburger2** [comment]
sampleLocation - for most there is only a picture. Few will be included in the museum collection as physical specimens. So institutionCode should be used for pictures?

**Comment by rukayaj** [comment]
Discussion with Andreas - 
Use new xlsx file (downloaded from IPT)
Add recordedByID column
Share large images via teams - GBIF Norway will host them on static.gbif.no

**Comment by rukayaj** [comment]
Quick update - Images are now hosted by us. We've decided that it makes more sense for for the dataset to be hosted on http://gbif.imr.no/ipt/ rather than our IPT. I had a quick zoom with Arnfinn and he seemed happy to add the Nansen Legacy Project as a data publisher there and to publish to GBIF. But he is on a cruise for the next week so we will have to do it after he gets back. 

In the meantime @aaltenburger2 and I are making a dwca on the gbif.no IPT so that it's easy to just download it and stick it on http://gbif.imr.no/ipt, ready for publication.

**Comment by rukayaj** [comment]
I've made a wikidata entry for the cruise so that we can have a better parentEventID than toktnummer which it seems only has meaning here https://toktsystem.imr.no/cruises/

I think we should probably do this for all the Nansen cruises which will have data split into multiple datasets, and we should teach it in the Nansen legacy workshop #73 

This morning I also followed up with Arnfinn re getting a SIOS DOI + publishing.

https://www.wikidata.org/wiki/Q112672532

**Comment by rukayaj** [comment]
He has covid! So perhaps this will only happen after the summer...

**Comment by rukayaj** [comment]
We published this in the end rather than getting Arnfinn to publish it on his IPT. So I am closing this issue.
